### ISSUE TITLE
Helm deploy fails for Azure AD enabled AKS clusters

### ISSUE THREAD

**Issue by JohnSchmeichel** [microsoft/azure-pipelines-tasks#10022]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: HelmDeploy

## Environment
- Server - Azure Pipelines - mseng/Domino/_taskgroup/fa591b82-3820-4bb8-8e73-bcc9dec32648
- Agent - Hosted Ubuntu 1604

## Issue Description

An Azure AD enabled RBAC AKS cluster requires using the clusterAdmin credentials, otherwise an interactive login prompt is presented. Using the Helm Deploy task the clusterUser credentials are used, which blocks the deploy.

### Task logs

[tasklog_19.log](https://github.com/Microsoft/azure-pipelines-tasks/files/3039811/tasklog_19.log)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2019-04-02T21:13:13.7024378Z To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BJWLC87XB to authenticate.
2019-04-02T21:13:13.7025969Z E0402 21:13:13.699661    3564 azure.go:126] Failed to acquire a token: acquiring a new fresh token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Code Expired
```

**Comment by JohnSchmeichel** [comment]
azure-pipelines-tasks/Tasks/HelmDeployV0/src/clusters/armkubernetescluster.ts has the following which defaults to using the clusterUser:
```typescript
var clusterInfo : AKSClusterAccessProfile = await aks.getAccessProfile(resourceGroup, clusterName);
```
The kubectl task allows this to be overridden, but this option is not available on the helm deploy task.

**Comment by Anumita** [comment]
We get the clusteruser creds in the task which is why you are hitting this issue. Could you try creating a kubernetes service connection using azure subscription option? Steps

1. Choose 'Kubernetes Service Connection' connection type.
2. Add a Kubernetes Service connection using Azure subscription type (click on +New button)
![image](https://user-images.githubusercontent.com/8982085/56194588-f4aadf80-6050-11e9-9e09-c013ac3e8a13.png)

3. Choose that connection in the Kubernetes service connection
4. Populate the namespace field with the chosen namespace in the connection

Let me know if this unblocks you or not!

**Comment by Sudharma** [comment]
Hi, Any solution for this problem?

**Comment by bansalaseem** [comment]
@Sudharma Have you tried using the solution that @Anumita mentioned?

**Comment by Sudharma** [comment]
well, all our deployments are automated with terraform and CI/CD this particular option is just a work around AFAIK. However we are managing with the cluster admin role but would like to see how the cli would authenticate with the given Azure AD user.( This user could be a technical user for CI/CD and with proper Azure AD setup)

**Comment by knoxi** [comment]
Hi,
are there any news to this issue? 

We have the same problem here in our automated deployment where we setup an [AKS with application gateway and ingress controller](https://github.com/Azure/application-gateway-kubernetes-ingress).

In the kubernetes deployment task , there is an option "Use cluster admin credentials" for the service connection type "Azure Resource Manager" which we miss in the "Package and deploy Helm charts" task for the same connection type.

**Comment by marc-mueller** [comment]
I second that. Having the same authentication options as with the Kubernetes tasks is absolutely necessary. AAD enabled clusters look promising, but existing build definitions stopped working after using AAD features. 

Especially with fully automated cluster deployments the described workaround is not handy since we do not have a configured kubernetes service connection at the time of cluster creation. 

Thanks for an update!

**Comment by azooinmyluggage** [comment]
Thanks @marc-mueller  and @knoxi 
We are picking this up.

**Comment by azooinmyluggage** [comment]
Done
![image](https://user-images.githubusercontent.com/6857119/61693231-cbcf7000-ad4c-11e9-90af-31439222a3d9.png)
Closing the issue. Let me know if you have any feedback.

**Comment by michaelelleby** [comment]
@azooinmyluggage `useClusterAdmin: true` does not solve the issue, because https://docs.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts is best practice and with this option enabled, `useClusterAdmin` will not work.

**Comment by pravindes** [comment]
I have also same concern, How can we use Azure pipeline without this options "Use cluster administrator credentials" ,
I have added service connection service principal in azure admin group ,still I am facing the same issue to login kubectl task

**Comment by jackliu2006** [comment]
> @azooinmyluggage `useClusterAdmin: true` does not solve the issue, because https://docs.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts is best practice and with this option enabled, `useClusterAdmin` will not work. The solution would be to retrieve an Azure access token for the AKS cluster and authenticate with the token.

Any feedback to the description here please. This comment is still valid. When disable-local-accounts=true then can not `useClusterAdmin`

**Comment by chandlerkent** [comment]
I think this is related to #15802, #17486, and Azure/kubelogin#20
