### ISSUE TITLE
docker@2 docker history --format flag only introduced in 17.0.9

### ISSUE THREAD

**Issue by byroncollins** [microsoft/azure-pipelines-tasks#10423]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Docker

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

Azure Pipelines:
 sdo-online, Te Ara Manaaki, ei-mule-runtime, ei-mule-runtime-70

- Agent: Private
OS: RHEL 7.6
Agent Version: 2.150.3

## Issue Description

The RHEL Docker version 1.13.1 is not compatible with dockerV2.

![image](https://user-images.githubusercontent.com/19849365/58060616-3ede2e00-7bc6-11e9-9cdc-944407aeb990.png)

Is there a minimal version of Docker for this task?

### Task logs

[logs_10365.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3200346/logs_10365.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

414unknown flag: --format
415See 'docker history --help'.
416##[debug]rc:125
417##[debug]success:false
418##[error]unknown flag: --format
419##[debug]Processed: ##vso[task.issue type=error;]unknown flag: --format
420##[error]See 'docker history --help'.
421##[debug]Processed: ##vso[task.issue type=error;]See 'docker history --help'.
422Finishing: push to ACR
`

**Comment by dabasnidhi** [comment]
We have fixed this issue so that the docker task will not fail for old docker versions due to --format flag

**Comment by byroncollins** [comment]
Hi @dabasnidhi a question around the release of the fix
According to the Merge M153. This was released to 2.253.3. We're running 2.254.2 and still seeing this error

`Starting: push to ACR
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, or run a Docker command
Version      : 2.154.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/docker
==============================================================================
sr/bin/docker push ***/ei/mule-ee-runtime:12912
The push refers to a repository [***/ei/mule-ee-runtime]
82d2f05de59e: Preparing
8bd751e53129: Preparing
73bba00e98eb: Preparing
...
9a5bec00fb84: Layer already exists
21c8b525c58c: Layer already exists
8bd751e53129: Pushed
4b14d4850bd6: Pushed
12912: digest: sha256:4cd987a865561fcd7ae6643fef48b65cde99251f73087d85de78428ba81dd272 size: 2831
sr/bin/docker history --format createdAt:{{.CreatedAt}}; layerSize:{{.Size}}; createdBy:{{.CreatedBy}} --no-trunc ***/ei/mule-ee-runtime:12912
sr/bin/docker push ***/ei/mule-ee-runtime:v1.1-Mule4.1.1
unknown flag: --format
See 'docker history --help'.
##[error]unknown flag: --format
##[error]See 'docker history --help'.
The push refers to a repository [***/ei/mule-ee-runtime]
82d2f05de59e: Preparing
8bd751e53129: Preparing
73bba00e98eb: Preparing
59f2dd0c3c92: Preparing
2fd73551dd7d: Preparing
ceb314908860: Preparing
See 'docker history --help'.
##[error]unknown flag: --format
##[error]See 'docker history --help'.
`

**Comment by dabasnidhi** [comment]
Hi @byroncollins , the fix for the issue has been released already in the version 2.154.4.
In order to test I have tried with random unknown flags, and the task did not fail for me, it only logged the exception for unknown flag. So I am unable to infer why it could be failing for you.
Can you please share the generated files for the Docker task in the Agent folder which gets created on your machine when you run the task?
Also request you to re-configure your agent, and run the task on a fresh pipeline.
