### ISSUE TITLE
Warnings for task AzureFileCopy

### ISSUE THREAD

**Issue by jared-hexagon** [microsoft/azure-pipelines-tasks#10767]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureFileCopy  

## Environment
- Server - Azure Pipelines

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      - jaredwilliams
      - AtomixAct3000
      - build ID 12

https://dev.azure.com/jaredwilliams/AtomixAct3000/_build/results?buildId=12

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:   
      - Hosted Windows 2019 with VS2019
      - queue ID 4

## Issue Description

In my yaml when I use `AzureFileCopy@3` to copy files to an Azure Blob I see 2 warnings in the logs and Azure Pipelines reports 2 warnings in the UI and 2 warnings in the email notification about the pipeline succeeding.

The task succeeds anyway but I should not see any warnings at all. It makes it look like my pipeline has issues when in reality it (probably) doesn't. I want to have all successful pipeline jobs and no warnings and errors.

```
##[section]Starting: deploy storybook
==============================================================================
Task         : Azure file copy
Description  : Copy files to Azure Blob Storage or virtual machines
Version      : 3.1.11
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-file-copy
==============================================================================
##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\2.1.0\AzureRM.psd1 -Global
##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
##[warning]The names of some imported commands from the module 'AzureRM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\2.1.0\AzureRM.Profile.psm1 -Global
##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -EnvironmentName AzureCloud
##[command] Set-AzureRmContext -SubscriptionId [removed] -TenantId ***
Uploading files from source path: 'd:\a\1\s\deploy\storybook' to storage account: 'storybookstatic' in container: '$web' with blob prefix: ''
##[command] & "AzCopy\AzCopy.exe" /Source:"d:\a\1\s\deploy\storybook" /Dest:"https://storybookstatic.blob.core.windows.net/`$web" /@:"d:\a\_temp\6763f493-2b89-44a2-921e-c6f2fcb95357" /XO /Y /SetContentType /Z:"AzCopy" /V:"AzCopy\AzCopyVerbose_2b4a416d-cfaa-4055-a568-0daa6a4f8c08.log" /S
[2019/06/27 01:40:08] Transfer summary:
-----------------
Total files transferred: 15
Transfer successfully:   15
Transfer skipped:        0
Transfer failed:         0
Elapsed time:            00.00:00:04
Uploaded files successfully from source path: 'd:\a\1\s\deploy\storybook' to storage account: 'storybookstatic' in container: '$web' with blob prefix: ''
##[section]Finishing: deploy storybook
```

![Screen Shot 2019-06-27 at 9 44 18 am](https://user-images.githubusercontent.com/51193645/60227005-2bf30380-98c0-11e9-895a-8658f3a35fdf.png)

yaml snip:

```

- task: AzureFileCopy@3
  inputs:
    SourcePath: 'deploy/storybook'
    azureSubscription: 'Free Trial([removed])'
    Destination: 'AzureBlob'
    storage: 'storybookstatic'
    ContainerName: '$web'
  displayName: 'deploy storybook'
```

## Troubleshooting

Cannot run locally as I do not have a Windows PC (I use a Windows agent because AzureFileCopy is not available in Ubuntu)

**Comment by vincentdass** [comment]
@jared-hexagon , thanks for reporting the issue.
We have fixed this and will be available in 4-5 weeks.

**Comment by jared-hexagon** [comment]
Cheers

**Comment by kgapos** [comment]
@vincent1173 For what it's worth, this problem still manifests in all 3 versions of the task (v1, v2, v3.preview)
