### ISSUE TITLE
##[error]Unexpected token : in JSON at position 3

### ISSUE THREAD

**Issue by kvansaders** [microsoft/azure-pipelines-tasks#10968]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: .NET Core SDK/runtime installer

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
asmedevops
ASME.Core.Utilities.Mvc.NetCore, #1.0.29

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Hosted VS2017

## Issue Description
This previously worked fine.  Existing build definition now fails at Install .NET Core step with error
##[error]Unexpected token : in JSON at position 3 

### Task logs

[logs_159.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3418223/logs_159.zip)

**Comment by cmiller0352** [comment]
I am getting same issue. Worked fine on Friday, now build in VSTS is showing this same error

**Comment by cmiller0352** [comment]
It's up and working now. I made no changes, but its working fine now.

**Comment by hiyadav** [comment]
Reopen in case you face this again.

**Comment by dmundra** [comment]
@hiyadav, this appears to be happening again for our pipelines. Same error as reported.

**Comment by ranouf** [comment]
Same for me since 5 min, I have an error with no modification in my pipeline.

**Comment by terminalstderr** [comment]
We're having this issue in our Pipelines as well!

**Comment by dmundra** [comment]
Looks like it is working now.

**Comment by hiyadav** [comment]
Hey @dmundra @ranouf @terminalstderr 
This happens when the releases-index.json or releases.json file in https://github.com/dotnet/core is modified incorrectly. It was auto resolved when the dotnet/core team corrected the file.

**Comment by dustinfineout** [comment]
This is happening today.

**Comment by Kengelgon** [comment]
> This is happening today.

Indeed

**Comment by mk-e1** [comment]
Still happening now... @hiyadav Can you give us any update on when this is going to be fixed?

**Comment by Burgyn** [comment]
I have the same problem. Because of this, I cannot release the package.

**Comment by hiyadav** [comment]
Hey, as stated earlier, this must be happening because of some error in releases-index or releases.json files in dotnet/core repo. It should be taken up there for fixing.

However, you can try using version 0 of UseDotNet task. It might get you the sdk/runtime package using fallback logic.

**Comment by dustinfineout** [comment]
This morning, tried updating setup-dotnet to v1.4.0 (above 1.2.0 we were previously using) and the builds are passing. I'm not certain where the fix is, but thought I'd share this resolution.

**Comment by mk-e1** [comment]
> Hey, as stated earlier, this must be happening because of some error in releases-index or releases.json files in dotnet/core repo. It should be taken up there for fixing.
> 
> However, you can try using version 0 of UseDotNet task. It might get you the sdk/runtime package using fallback logic.

Unfortunatelly this didn't work.

> This morning, tried updating setup-dotnet to v1.4.0 (above 1.2.0 we were previously using) and the builds are passing. I'm not certain where the fix is, but thought I'd share this resolution.

We don't have this option since we can just choose between 0.*, 1.*(Preview) and 2.*(Preview)

**Comment by anuragc617** [comment]
@mk-e1 @Burgyn I am unable to reproduce this now. Looks like an issue has been fixed in dotnet/core repository. Closing this issue for now.

**Comment by kucint** [comment]
I still have this problem:

2020-03-09T14:11:34.9661393Z ##[section]Starting: Use .NET Core sdk 3.1.102
2020-03-09T14:11:34.9671747Z ==============================================================================
2020-03-09T14:11:34.9671930Z Task         : .NET Core SDK Installer
2020-03-09T14:11:34.9672075Z Description  : Acquires a specific version of the .NET Core SDK from internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks.
2020-03-09T14:11:34.9672234Z Version      : 0.2.0
2020-03-09T14:11:34.9672462Z Author       : Microsoft Corporation
2020-03-09T14:11:34.9672673Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=853651)
2020-03-09T14:11:34.9672802Z ==============================================================================
2020-03-09T14:11:36.3011321Z Tool to install: .NET Core sdk version 3.1.102.
2020-03-09T14:11:36.3024212Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'c:\agent\_work\_tasks\DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5-176b752bfea6\0.2.0\externals\get-os-platform.ps1'"
2020-03-09T14:11:37.0341484Z Primary:win-x64
2020-03-09T14:11:37.0346020Z Detected platform (Primary): win-x64
2020-03-09T14:11:37.0350029Z Checking if a cached copy exists for this version...
2020-03-09T14:11:37.0373833Z The cache does not contain the requested version of .NET Core. Downloading and installing it now.
2020-03-09T14:11:37.0374615Z Getting URL to download .NET Core sdk version: 3.1.102.
2020-03-09T14:11:37.2261571Z ##[error]Unexpected token : in JSON at position 3
2020-03-09T14:11:37.2365822Z ##[section]Finishing: Use .NET Core sdk 3.1.102

**Comment by AdamRussak** [comment]
Unable to get it to work with suggested solutions above, 
using the task version 0.

##[section]Starting: Use .NET Core runtime 2.1.14
==============================================================================
Task         : .NET Core SDK/runtime installer
Description  : Acquire a specific version of the .NET Core SDK from the internet or local cache and add it to the PATH
Version      : 0.2.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer
==============================================================================
Tool to install: .NET Core runtime version 2.1.14.
[command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'c:\agent01\_work\_tasks\DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5-176b752bfea6\0.2.4\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Checking if a cached copy exists for this version...
The cache does not contain the requested version of .NET Core. Downloading and installing it now.
Getting URL to download .NET Core runtime version: 2.1.14.
##[error]Unexpected token : in JSON at position 3
##[section]Finishing: Use .NET Core runtime 2.1.14

**Comment by anuragc617** [comment]
@kucint and @AdamRussak yes .NET Core SDK/runtime installer 0.2.*  is outdated and broken. You should start using UseDotNetV2 task for installing dotNet sdk as mentioned here https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops.

**Comment by WizX20** [comment]
@anuragc617 That does not work on older TFS on-premise installations and is not a solution.

**Comment by RSchwarzwald-Hexagon** [comment]
Happened to me today

**Comment by j2020v** [comment]
this is happening for us today :(

**Comment by harre096** [comment]
Having this issue today. I didn't change the build and expected it to work. Halp

**Comment by bpummill1** [comment]
Also having this issue today

**Comment by jameswilson281** [comment]
This is happening to us today!

**Comment by Pepsi1x1** [comment]
Having this issue today

**Comment by dnperfors** [comment]
Today it is happening again. First I thought it was because we used a slightly older version of .NET Core, but then again I would expect that I can run older builds just fine without any problems. 
Could this please be solved correctly?

**Comment by lxmaran** [comment]
It's happening again.

**Comment by MikeRixWolfe** [comment]
Happening again today

**Comment by allendgoodner** [comment]
Happening to us today...

**Comment by scb-tomasmortensen** [comment]
Happened here today too. We are using ADS on prem. Switched to 1.* PREVIEW task then entered 3.x as the SDK version. That got it working.

**Comment by bishal-pdMSFT** [comment]
Please us latest version of task (2*). Older version of task is not being updated frequently.

**Comment by dnperfors** [comment]
@bishal-pdMSFT that is not always possible. In our case we have DevOps server 2019 (on premise), which doesn't support yaml release pipelines, therefor we have to use the old task (or use a custom script...)
