### ISSUE TITLE
Pipeline Cache Permissions Error with PR builds of forks

### ISSUE THREAD

**Issue by stefangordon** [microsoft/azure-pipelines-tasks#11013]
Error using CacheBeta:

> Access Denied: Microsoft.TeamFoundation.ServiceIdentity;35644cd7-0bb6-49d4-9b34-a44080e11677:Build:a73f0a6a-a507-4857-93f8-daef87db809b needs the following permission(s) on the resource $ to perform this action: Read pipeline cache entries

I'm having trouble finding reference to this permission in the documentation.  It appears to be because the task is being added in a pull request and isn't in the master version of the pipeline, but if you can't add it in a pull request it would be a challenge to use it. 

What is the right way to solve it?

```
  steps:
  - task: CacheBeta@0
    inputs:
      key: |
        c7n-tox
        $(python.version)
        $(Agent.OS)
      path: $(PIP_DOWNLOAD_CACHE)
```

Same result on Windows and Linux.  

See build here:
https://dev.azure.com/cloud-custodian/cloud-custodian/_build/results?buildId=3409

PR here:
https://github.com/cloud-custodian/cloud-custodian/pull/4451

**Comment by stefangordon** [comment]
I have a workaround by just forcing this into master so I'll close...

**Comment by pvizeli** [comment]
I have the same issue on Home Assistant. Please reopen this ticket.

**Comment by stefangordon** [comment]
I suspect it is probably expected behavior, it just isn't documented at all yet.  

For security reason you can't add cache from the PR/CI build - you'd need to commit that directly to master.  

Would be good to get comment on this though and confirmation?

**Comment by pvizeli** [comment]
If that doesn't work with PR, it's useless for CI.

**Comment by stefangordon** [comment]
In one case I had it work with CI as long as the modification to the pipeline file wasn't happening in CI - but now we saw that fail in another pipeline - so we really need feedback from the product team here I think.

**Comment by owenhuynMSFT** [comment]
There's an existing issue with forked PRs not working:
https://github.com/microsoft/azure-pipelines-tasks/issues/10979

We've investigated into this and fixed the bug but we still need to roll out the fix in the next coupel of days. Can you confirm that it's only affect forked PRs?

**Comment by stefangordon** [comment]
Thanks @owenhuynMSFT - 

Yes these are standard PR's from forks.  Thanks for linking us to the core issue and for the update!

**Comment by owenhuynMSFT** [comment]
Thanks for the confirmation. Part of our security implementation is to prevent using forks as an attack vector which you can read under "Cache Scoping":
https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-caching.md

We suffered a regression in our last release which caused our security checks to fail thus this permission error you are seeing. Our apologies for not having this working, we'll make sure we'll get this one working soon. Thanks for your patience!

**Comment by pvizeli** [comment]
@owenhuynMSFT Yes, only with forked PRs. Thanks for your attention.

**Comment by fadnavistanmay** [comment]
This issue should be fixed. Can you guys please confirm. Closing the issue. Feel free to re-open. Thanks.

**Comment by blueelvis** [comment]
@fadnavistanmay - We are still facing this issue. Getting that exact same error as above. Could you please help us?

/cc: @MrMatt57

**Comment by stefangordon** [comment]
@blueelvis Are you trying to build a PR from a fork that adds a cache task? I believe you need to make this change directly in master.

**Comment by blueelvis** [comment]
Nope. It is not a fork. It is a private repo and we have tried with another
branch as well as with the master. Still getting this issue.

**Comment by zhankezk** [comment]
I am getting "##[error]Access Denied: Project Collection Build Service (xxxxx) needs the following permission(s) on the resource $ to perform this action: Read pipeline cache entries". It's a master branch in Azure DevOps project, a release pipeline. The issue still exists.

**Comment by seanke** [comment]
I'm getting this issue now. How do you fix it?

**Comment by aodj** [comment]
Seeing the same behaviour on Release Pipelines. The [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#known-issues-and-feedback) simply says to check the known issues, which leads here to a closed issue.

**Comment by andyhammar** [comment]
Also having this problem, getting this in a Release pipeline just as @aodj 
Thanks @owenhuynMSFT

**Comment by jotatoledo** [comment]
Do release pipelines support the cache task at all?

**Comment by fadnavistanmay** [comment]
Nope, it doesn't

**Comment by Saibamen** [comment]
> Do release pipelines support the cache task at all?
>> Nope, it doesn't

Any update? (current task version: 2.*)

I want to use cache in release pipelines with UI (without YAML)
