### ISSUE TITLE
Missing localization

### ISSUE THREAD

**Issue by henriksen** [microsoft/azure-pipelines-tasks#11104]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureRmWebAppDeployment
Azure App Service Deploy

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

- Agent - Hosted : 
    - If using Hosted agent, provide agent queue name: Hosted

## Issue Description

When using JSON variable substitution on the Azure App Service Deploy task, I get warnings in my logs for missing localization variables. 
```
##[warning]Can\'t find loc string for key: JSONvariableSubstitution
##[warning]Can\'t find loc string for key: SubstitutingValueonKey
```
### Task logs
```
2019-08-11T17:59:23.0077391Z ##[section]Starting: Deploy Azure App Service
2019-08-11T17:59:23.0149076Z ==============================================================================
2019-08-11T17:59:23.0149195Z Task         : Azure App Service deploy
2019-08-11T17:59:23.0149275Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2019-08-11T17:59:23.0149359Z Version      : 4.156.3
2019-08-11T17:59:23.0149415Z Author       : Microsoft Corporation
2019-08-11T17:59:23.0149500Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment
2019-08-11T17:59:23.0149581Z ==============================================================================
2019-08-11T17:59:23.6076412Z Got service connection details for Azure App Service:'frontend'
2019-08-11T17:59:24.4839252Z ##[warning]Can\'t find loc string for key: JSONvariableSubstitution
2019-08-11T17:59:24.4847042Z JSONvariableSubstitution **/config.json
2019-08-11T17:59:24.4916856Z ##[warning]Can\'t find loc string for key: JSONvariableSubstitution
2019-08-11T17:59:24.4917381Z JSONvariableSubstitution d:\a\_temp\temp_web_package_1609305735341433\config.json
2019-08-11T17:59:24.4918501Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-11T17:59:24.4919020Z SubstitutingValueonKey baseApiUrl
2019-08-11T17:59:24.4919305Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-11T17:59:24.4919632Z SubstitutingValueonKey authority
2019-08-11T17:59:24.4920009Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-11T17:59:24.4920302Z SubstitutingValueonKey redirect_uri
2019-08-11T17:59:24.4920589Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-11T17:59:24.4921063Z SubstitutingValueonKey silent_redirect_uri
2019-08-11T17:59:24.4921367Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-11T17:59:24.4921712Z SubstitutingValueonKey post_logout_redirect_uri
2019-08-11T17:59:24.4926858Z JSON variable substitution applied successfully.
2019-08-11T17:59:24.8790275Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"1"}
2019-08-11T17:59:25.3158920Z Updated App Service Application settings and Kudu Application settings.
2019-08-11T17:59:25.6637059Z Package deployment using ZIP Deploy initiated.
2019-08-11T17:59:30.4573575Z Successfully deployed web package to App Service.
2019-08-11T17:59:35.1485795Z Successfully added release annotation to the Application Insight 
2019-08-11T17:59:35.5219415Z App Service Application URL: 
2019-08-11T17:59:35.5410964Z ##[section]Finishing: Deploy Azure App Service
```

**Comment by eaarora-ms** [comment]
Fixed: https://github.com/microsoft/azure-pipelines-tasks/pull/11108

**Comment by eltoncezar** [comment]
Hi, has this been released already? I'm having the same issue.

**Comment by sidecus** [comment]
I ran into the same issue with azure dev ops "Azure App Service deploy" task.
Anyway to workaround it by ourselves?

**Comment by eaarora-ms** [comment]
@eltoncezar Hi yes it has been released already. Could you please reproduce the logs here after pulling the latest changes from master?

**Comment by jobinjohnpaul** [comment]
Hi @eaarora-ms,
We are still receiving these warnings when running a release task for 'Azure App Service deploy'
Here is a snippet of the warnings that are produced
2019-08-18T23:18:39.4250069Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-18T23:18:39.4250590Z SubstitutingValueonKey InstrumentationKey
2019-08-18T23:18:39.4251029Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-18T23:18:39.4251513Z SubstitutingValueonKey MobileAppsManagement_EXTENSION_VERSION
2019-08-18T23:18:39.4251968Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-18T23:18:39.4252448Z SubstitutingValueonKey HostName
2019-08-18T23:18:39.4252883Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey`

**Comment by RoshanKumarMicrosoft** [comment]
We had already fixed this issue but yet has not be deployed ..It will be available by end of next week.

**Comment by pacorreia** [comment]
> We had already fixed this issue but yet has not be deployed ..It will be available by end of next week.

Ok, meanwhile any suggestion for workaround?

**Comment by skothari120790** [comment]
Hi, we are also facing the same issue. Is the solution available now?

Regards,
Sanjay

**Comment by pacorreia** [comment]
Actually I figured out a workaround, by having copies of appsettings, one for each environment, and a powershell task before deploy task, to copy from these new files to appsettings.json according to the stage.

Working pretty well

**Comment by SumiranAgg** [comment]
The fix is deployed. Please verify. Closing the issue.

**Comment by skothari120790** [comment]
Hi Team,

I am still getting the same issue in Azure App Deploy Task. See below logs :

2019-08-29T10:26:40.4363338Z Task         : Azure App Service deploy
2019-08-29T10:26:40.4363419Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2019-08-29T10:26:40.4363674Z Version      : 4.156.4
2019-08-29T10:26:40.4363735Z Author       : Microsoft Corporation
2019-08-29T10:26:40.4363828Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment

2019-08-29T10:26:48.0316538Z ##[warning]Can\'t find loc string for key: JSONvariableSubstitution
2019-08-29T10:26:48.0316920Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: JSONvariableSubstitution
2019-08-29T10:26:48.0317134Z JSONvariableSubstitution d:\a\_temp\temp_web_package_27948901297720097\assets\config\app-config.json
2019-08-29T10:26:48.0317369Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0317522Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0317866Z SubstitutingValueonKey baseUrl
2019-08-29T10:26:48.0318095Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0318260Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0318941Z SubstitutingValueonKey approvalmatrixUrl
2019-08-29T10:26:48.0319261Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0319465Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0319812Z SubstitutingValueonKey tenant
2019-08-29T10:26:48.0320096Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0320303Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0320503Z SubstitutingValueonKey clientId
2019-08-29T10:26:48.0320793Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0320993Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0321187Z SubstitutingValueonKey redirectUri
2019-08-29T10:26:48.0321460Z ##[warning]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0321662Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: SubstitutingValueonKey
2019-08-29T10:26:48.0321860Z SubstitutingValueonKey postLogoutRedirectUri
2019-08-29T10:26:48.0322400Z JSON variable substitution applied successfully.
loc.messages.JSONvariableSubstitution

Please check this pull request. I do not find any changes made in below pull requests in master branch :
https://github.com/microsoft/azure-pipelines-tasks/pull/11143

Regards,
Sanjay

**Comment by pmcilreavy** [comment]
Yep can confirm this is still happening. Will the fix take a while to propagate perhaps?

**Comment by santhu89** [comment]
> The fix is deployed. Please verify. Closing the issue.

This issue still seems to be happening.

**Comment by todthomson** [comment]
I went back to v3 of the task as a work around.

**Comment by pacorreia** [comment]
The issue should be reopened, as it wasn't fixed

**Comment by pmcilreavy** [comment]
2019-08-30T03:08:25.8480335Z Task         : IIS web app deploy
2019-08-30T03:08:25.8481433Z Description  : Deploy a website or web application using Web Deploy
2019-08-30T03:08:25.8482297Z Version      : 0.156.0
2019-08-30T03:08:25.8483156Z Author       : Microsoft Corporation

**Comment by M4mu5qu3** [comment]
Hi all,
same problem here...

```
2019-09-03T16:53:15.2067929Z ##[section]Starting: IIS Web App Deploy
2019-09-03T16:53:15.2223930Z ==============================================================================
2019-09-03T16:53:15.2223930Z Task         : IIS web app deploy
2019-09-03T16:53:15.2223930Z Description  : Deploy a website or web application using Web Deploy
2019-09-03T16:53:15.2223930Z Version      : 0.156.0
2019-09-03T16:53:15.2223930Z Author       : Microsoft Corporation
2019-09-03T16:53:15.2223930Z Help         : [Learn more about this task](https://go.microsoft.com/fwlink/?linkid=866789)
2019-09-03T16:53:15.2379931Z ==============================================================================
2019-09-03T16:53:18.9508169Z ##[warning]Can\'t find loc string for key: VariableSubstitutionInitiated
2019-09-03T16:53:18.9508169Z VariableSubstitutionInitiated C:\vstsagent\A1\_work\_temp\temp_web_package_52230338484222\Web.Debug.config
2019-09-03T16:53:18.9508169Z ##[warning]Can\'t find loc string for key: SkippedUpdatingFile
2019-09-03T16:53:18.9664170Z SkippedUpdatingFile C:\vstsagent\A1\_work\_temp\temp_web_package_52230338484222\Web.Debug.config
2019-09-03T16:53:18.9664170Z ##[warning]Can\'t find loc string for key: VariableSubstitutionInitiated
2019-09-03T16:53:18.9664170Z VariableSubstitutionInitiated C:\vstsagent\A1\_work\_temp\temp_web_package_52230338484222\Web.config
2019-09-03T16:53:18.9664170Z ##[warning]Can\'t find loc string for key: SubstitutionForXmlNode
2019-09-03T16:53:18.9664170Z SubstitutionForXmlNode appSettings
2019-09-03T16:53:18.9664170Z ##[warning]Can\'t find loc string for key: SubstitutionForXmlNode
2019-09-03T16:53:18.9664170Z SubstitutionForXmlNode configSections
2019-09-03T16:53:18.9664170Z ##[warning]Can\'t find loc string for key: SkippedUpdatingFile
2019-09-03T16:53:18.9664170Z SkippedUpdatingFile C:\vstsagent\A1\_work\_temp\temp_web_package_52230338484222\Web.config
2019-09-03T16:53:18.9664170Z ##[warning]Can\'t find loc string for key: VariableSubstitutionInitiated
2019-09-03T16:53:18.9664170Z VariableSubstitutionInitiated C:\vstsagent\A1\_work\_temp\temp_web_package_52230338484222\packages.config
2019-09-03T16:53:18.9664170Z ##[warning]Can\'t find loc string for key: SkippedUpdatingFile
2019-09-03T16:53:18.9664170Z SkippedUpdatingFile C:\vstsagent\A1\_work\_temp\temp_web_package_52230338484222\packages.config
2019-09-03T16:53:18.9664170Z XML variable substitution applied successfully.

```

**Comment by pacorreia** [comment]
@SumiranAgg please reopen the issue, you should have not closed it

**Comment by SumiranAgg** [comment]
Reopening the issue. The fix is still rolling. Should reach all accounts in another week. Apologies was miscommunication.

**Comment by rahulha** [comment]
There is a simple workaround. Add a task "File transform" right before deployment task and use the same build folder and json file names. It does exact same thing as deployment (Azure app service) task does with transformation. Also its clean workaround.

**Comment by pacorreia** [comment]
Seems a nice workaround, going to test

**Comment by pacorreia** [comment]
@rahulha working like a clock, thanks

**Comment by tegaaa** [comment]
I'm also still seeing this problem as of today.  I don't want to add more tasks then necessary if this is a bug.  I don't really have loc in my application so i'll assume the warning will go away once fixed.

**Comment by SumiranAgg** [comment]
It should be fixed now. Please validate.

**Comment by pacorreia** [comment]
I can say it is ok for me, western Europe region

**Comment by 20shivangi** [comment]
Great!! Thereby I am closing the issue.
Feel free to reopen if facing any issue.

**Comment by cheresier** [comment]
Just got the following message in my deploy logs:

##[warning]Can\'t find loc string for key: FailedToApplySpecialTransformation

Seems that the fix was incomplete.

**Comment by eaarora-ms** [comment]
@cheresier  : Hi, could you please reproduce the logs here? I need to know the task and the task version that you're using.

**Comment by cheresier** [comment]
Sorry -- I have since fixed the underlying problem causing the error and deleted the pipeline run where this error occurred, but here is the information you are looking for:

Starting: FileTransform
==============================================================================
Task         : File transform
Description  : Replace tokens with variable values in XML or JSON configuration files
Version      : 1.156.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/file-transform
==============================================================================

**Comment by eaarora-ms** [comment]
@cheresier Thanks! Was able to reproduce the issue. Opened a PR for the same. The fix should be available soon.

**Comment by ragesh-urolime** [comment]
Hi Team,

I am getting the same error now
![DevOps_error](https://user-images.githubusercontent.com/51899966/70997712-016c5f80-2119-11ea-86a9-ddcb3950818c.JPG)

**Comment by eaarora-ms** [comment]
@ragesh-urolime  Can you please share the task name you're using?

**Comment by ragesh-urolime** [comment]
> @ragesh-urolime Can you please share the task name you're using?

AzureRmWebAppDeployment@4

**Comment by internoQQ** [comment]
@ragesh-urolime  I have the same error as you let me know if you solve it

**Comment by ragesh-urolime** [comment]
> @ragesh-urolime I have the same error as you let me know if you solve it

@internoQQ Sure. I haven't found any solution yet and it's showing up all release pipelines, though there was no changes done to the pipeline.

**Comment by adetayorabiu** [comment]
Getting the same warning messages on **Azure Resource Group Deployment task**

**Comment by eaarora-ms** [comment]
Hi,
We are working on the fix. Although it might take some time for the fix to roll out.

**Comment by eaarora-ms** [comment]
Hi, I have created a PR. It should be merged soon and the fix will roll out in  a few days. 
I am closing this conversation since the warnings are not related. Please feel free to create a new issue and tag me if you need any help.
