### ISSUE TITLE
In Azure Pipelines, the published coverage report fail to display some Unicode characters

### ISSUE THREAD

**Issue by EFanZh** [microsoft/azure-pipelines-tasks#11459]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResults

## Environment

- Server - Azure Pipelines or TFS on-premises?
  - Azure Pipelines
- Agent - Hosted or Private:
  - Hosted

## Issue Description

The published reports fail to display some Unicode characters. See [this page](https://dev.azure.com/EFanZh/a142a4f5-d1aa-4ad6-9e36-c326724a6f11/_apis/test/CodeCoverage/browse/3380364/Code%20Coverage%20Report_49/section_12_3_insertion_and_deletion_mod.htm), line 10 of the source code.

I think that is because the generated page is missing the

```html
<meta charset="UTF-8" />
```

line.

**Comment by kaadhina** [comment]
Thank you for your feedback. We have fixed this and it should get rolled out in a few weeks time. Thanks!

**Comment by EFanZh** [comment]
Hi @kaadhina, I think this issue still exists. See [this page](https://dev.azure.com/EFanZh/a142a4f5-d1aa-4ad6-9e36-c326724a6f11/_apis/test/CodeCoverage/browse/4809904/Code%20Coverage%20Report_174/section_12_3_insertion_and_deletion_mod.htm). Can you check?
