### ISSUE TITLE
[CacheBeta@0] Cache should be updated if its key already exists

### ISSUE THREAD

**Issue by xuhongxu96** [microsoft/azure-pipelines-tasks#11600]
## Required Information

**Bug or Feature.** (Not sure)

**Enter Task Name**: CacheBeta@0 

## Issue Description

The `CacheBeta@0` task will output `Cache with fingerprint 'cmake|Linux|out' already exists.` and won't upload the new files to cache if the cache key already exists.

Is it by design? Anyway, I think it'll be more reasonable to update the cache instead of skipping.

### Task logs

```
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session f9d52ef7-5d7f-4afa-9d2d-64de012f83a4
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `cmake|Linux|out`
Information, There is a cache hit: `cmake|Linux|out`
Information, Used scope: 554;86d018e2-e7e4-42c2-96c4-378013445708;refs/pull/14798/merge;fb34b90b-059d-4cb4-aad8-87645979d24c
Information, Missed on the following scopes: 554;86d018e2-e7e4-42c2-96c4-378013445708;refs/heads/pimpl-and-better-include;fb34b90b-059d-4cb4-aad8-87645979d24c, 554;86d018e2-e7e4-42c2-96c4-378013445708;refs/heads/master;fb34b90b-059d-4cb4-aad8-87645979d24c
Cache with fingerprint `cmake|Linux|out` already exists.
Information, ApplicationInsightsTelemetrySender correlated 1 events with X-TFS-Session f9d52ef7-5d7f-4afa-9d2d-64de012f83a4
```
### Sources

https://github.com/microsoft/azure-pipelines-agent/blob/3d378d9ea9a34e535d2dc62dba6598396f2fb836/src/Agent.Plugins/PipelineCache/PipelineCacheServer.cs#L36-L47

**Comment by johnterickson** [comment]
Hi @xuhongxu96 -
This is by design, but we've only documented half of the design so your confusion is quite understandable. See https://github.com/microsoft/azure-pipelines-tasks/issues/10842 and https://github.com/MicrosoftDocs/vsts-docs/pull/6147

**Comment by xuhongxu96** [comment]
Thanks for your information. **RestoreKeys** is really a great feature! 👍 
Hope the docs will be updated soon.

**Comment by fadnavistanmay** [comment]
Hi @xuhongxu96 - we have updated the docs with the RestoreKeys options. Thanks.

**Comment by AceHack** [comment]
I still don't understand restore keys, can someone please elaborate?  How do I use this to update cache?

**Comment by beatcracker** [comment]
@AceHack You need to use variable that changes on every pipeline run and fallback keys: [Implementing rolling cache in Azure DevOps](https://beatcracker.wordpress.com/2020/09/29/implementing-rolling-cache-in-azure-devops).

#### Example

```yaml
# Implement rolling cache using Git revision as a key to keep cache fresh

– task: Cache@2
  displayName: Cache | build_output
  inputs:
    key: '"build_output" | "$(Build.SourceVersion)"'
    restoreKeys: "build_output"
    path: $(Build.SourcesDirectory)/build_output
```

Note, that restoring with fallback key will yield `inexact` in `cacheHitVar` if you're using it.
