### ISSUE TITLE
"Download Pipeline Artifacts" task fails on UNC artifacts

### ISSUE THREAD

**Issue by avivanoff** [microsoft/azure-pipelines-tasks#11804]
**Type**: Bug

**Enter Task Name**: "Download Pipeline Artifacts"

## Environment
- Server - Azure Pipelines
 - Agent - Private, 2.160.1

## Issue Description

Using "Download Pipeline Artifacts" task to download UNC-base drop artifact results in error:

`Microsoft.TeamFoundation.Build.WebApi.BuildArtifact is not of type PipelineArtifact, FileShare or BuildArtifact`

The artifact was published using "Publish build artifacts" task.

### Task logs

```
#[debug]Evaluating condition for step: 'Download Pipeline Artifact'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Download Pipeline Artifact
==============================================================================
Task         : Download Pipeline Artifacts
Description  : Download build and pipeline artifacts
Version      : 2.1.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
==============================================================================
Download from the specified build: #375528
Download artifact to: D:\III\_work\71\s\
##[debug]Dedup parallelism: 192
##[error]Microsoft.TeamFoundation.Build.WebApi.BuildArtifact is not of type PipelineArtifact, FileShare or BuildArtifact
##[debug]Processed: ##vso[task.logissue type=error;]Microsoft.TeamFoundation.Build.WebApi.BuildArtifact is not of type PipelineArtifact, FileShare or BuildArtifact
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineArtifact.ArtifactProviderFactory.GetProvider(BuildArtifact buildArtifact)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.DownloadAsyncV2(AgentTaskPluginExecutionContext context, PipelineArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV2_0_0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
##[section]Finishing: Download Pipeline Artifact
```

**Comment by ScottLangham** [comment]
I need this too.

**Comment by jahsu-MSFT** [comment]
@avivanoff  Can you show me your build def and logs for uploading and downloading the artifact?

**Comment by avivanoff** [comment]
@jahsu-MSFT, how do you want me to share it with you?

**Comment by jahsu-MSFT** [comment]
@avivanoff yes, I'm trying to understand the scenario you are talking about. You can remove the parts that might contain private info or sensitive data.

**Comment by avivanoff** [comment]
@jahsu-MSFT, most of the logs contain data I do not want public.

Scenario is as this:

1. Build "A" publishes artifact UNC "drop" using "Publish drop artifact" task.
2. Build "B" tries to download artifact "drop" from the latest build "A" using "Download pipeline artifact" task.

**Comment by jahsu-MSFT** [comment]
Could you tell me the specific task name and version for publishing the UNC drop? It's written in the logs I believe.

**Comment by avivanoff** [comment]
@jahsu-MSFT, here you go:
```
==============================================================================
Task         : Publish build artifacts
Description  : Publish build artifacts to Azure Pipelines or a Windows file share
Version      : 1.158.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
==============================================================================
```

**Comment by ScottLangham** [comment]
I can share mine too if you need more info. Here's the failing download log:

`2019-11-22T13:56:22.2164691Z ##[section]Starting: Download Pipeline Artifact
2019-11-22T13:56:22.2698002Z ==============================================================================
2019-11-22T13:56:22.2698146Z Task         : Download Pipeline Artifacts
2019-11-22T13:56:22.2698177Z Description  : Download build and pipeline artifacts
2019-11-22T13:56:22.2698204Z Version      : 2.1.1
2019-11-22T13:56:22.2698238Z Author       : Microsoft Corporation
2019-11-22T13:56:22.2698265Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-pipeline-artifact
2019-11-22T13:56:22.2698289Z ==============================================================================
2019-11-22T13:56:24.3627676Z Download from the specified build: #380369
2019-11-22T13:56:24.3627874Z Download artifact to: F:\Agent02\_work\r1\a\$(Pipeline.Workspace)\DlpEngine_Supporting
2019-11-22T13:56:25.0301596Z ##[error]Microsoft.TeamFoundation.Build.WebApi.BuildArtifact is not of type PipelineArtifact, FileShare or BuildArtifact
2019-11-22T13:56:25.0526501Z ##[section]Finishing: Download Pipeline Artifact`

To upload the artifact, I copy files to a fileshare using robocopy. And then, to associate that path with the build as an artifact, I call the powershell function Write-VstsAssociateArtifact from the VstsTaskSdk version 0.10.0 that I downloaded a year or two ago from https://github.com/Microsoft/vsts-task-lib. At least I think that's the version, 0.10.0 is listed in the VstsTaskSdk.psd1 file that's part of the download. It also says the commit hash is 787a46ec0a2df5b4d12c2e801bd3f319975c054c

**Comment by ScottLangham** [comment]
If I use the rest api to get json for the artifact, it looks like the following. (I've anonymized values in CAPS):

{
  "count": 1,
  "value": [
    {
      "id": ---ARTIFACT ID--,
      "name": "drop",
      "source": "---GUID---",
      "resource": {
        "type": "filepath",
        "data": "\\\\--SERVERNAME--\\--PATH--",
        "properties": {},
        "url": "https://dev.azure.com/--ORAGNIZATION--/--GUID ---/_apis/build/builds/---BUILD_ID---/artifacts?artifactName=drop&api-version=5.1",
        "downloadUrl": "file://---SERVER---/--PATH--"
      }
    }
  ]
}

**Comment by jahsu-MSFT** [comment]
@avivanoff  Can you try using 'download build artifact' task and see if it works? since you published using publish build artifact task.
One thing to note is for copying to a file share (FilePath), the file share artifact must be accessible from the build agent.

**Comment by avivanoff** [comment]
@jahsu-MSFT, “Download build artifacts” works just fine.

**Comment by avivanoff** [comment]
@jahsu-MSFT, any updates on the issue? We are planning to switch build artifacts to pipeline artifacts, and this is one of the issues that prevents us from making the switch.

**Comment by jahsu-MSFT** [comment]
@avivanoff While we are investigating the issue. Can you try using publish pipeline artifact task to publish the fileshare and download it from download pipeline artifact V2 task?

**Comment by avivanoff** [comment]
@jahsu-MSFT, it is amazing how case-inconsistent artifact type names are.
When do you think your changes make it in the build?

**Comment by jahsu-MSFT** [comment]
@avivanoff Which account you are using? We just deployed the new agent version and since we will not do any deployments in late December, the next releases time would be some time in early Jan.

**Comment by avivanoff** [comment]
What do you mean by "account"?

**Comment by jahsu-MSFT** [comment]
@avivanoff I'm assuming you have an AzureDevops account?

**Comment by avivanoff** [comment]
@jahsu-MSFT, yes, we do. We are still on sprint 160, agent 2.160.1.

**Comment by jahsu-MSFT** [comment]
@avivanoff I meant to ask, which AzureDevops account you are using? What's the account name? 
You can find the account name from the Url -  https://dev.azure.com/{account Name}/

**Comment by avivanoff** [comment]
@jahsu-MSFT, ivanti.

**Comment by avivanoff** [comment]
Manually installed 2.162.0 and verified that "Download Pipeline Artifacts" does not fail on UNC artifacts anymore.

**Comment by jahsu-MSFT** [comment]
@avivanoff  Great. Thanks for the update.

**Comment by avivanoff** [comment]
@jahsu-MSFT, is there a way to find out when updates will reach our account?

**Comment by jahsu-MSFT** [comment]
The schedule of agent deployment is delayed since there was some regression. 
@jtpetty Can you please provide better detail on @avivanoff's questions.  
Thanks,

**Comment by jtpetty** [comment]
@avivanoff - We are still working on a bug that we discovered while rolling out 2.162 that we need to address before rolling it out more broadly. I do not have an ETA yet.

**Comment by avivanoff** [comment]
@jtpetty, any updates?

**Comment by jtpetty** [comment]
I hope to have an update today. There was a server-side issue that impacted the customer trying out an agent fix on Friday which delayed us. There server-side issue should be addressed in the next few hours and we can resume testing out agent fixes.

**Comment by avivanoff** [comment]
@jtpetty, anything?

**Comment by jahsu-MSFT** [comment]
@avivanoff We will provide an update once we have any.  
As @jtpetty mentioned, "We hope to publish a new agent release today or tomorrow so that it will be available for anyone wanting to manual update, but will not roll out this new version to customers until after the new year."

**Comment by avivanoff** [comment]
@jahsu-MSFT, we just got 2.163.1. You can resolve this bug.

**Comment by jahsu-MSFT** [comment]
@avivanoff Thanks for the update. Closing this Issue as this is resolved.

**Comment by avivanoff** [comment]
@jahsu-MSFT, actually, I am still getting an error:

![image](https://user-images.githubusercontent.com/29612120/71115854-88145180-2198-11ea-9bf1-e5b1d19841c3.png)

**Comment by avivanoff** [comment]
@jahsu-MSFT, it works in 2.162.0, it is broken in 2.163.1. Please reopen this bug.

**Comment by jahsu-MSFT** [comment]
@jtpetty Is this merge commit in 2.162.0 but not in 2.163.1?

**Comment by jtpetty** [comment]
2.163.1 was a roll forward of 2.160.1 since there was a bug in both 2.161.1 and 2.162.0. There are other issues that prevent us from rolling back an agent version from when it was released.

We are in the process of rolling out 2.163.2 which has a cherry pick of this commit.

**Comment by avivanoff** [comment]
@jtpetty, just tested with 2.163.2, still broken. Please, reopen this bug.

**Comment by avivanoff** [comment]
@jtpetty, @jahsu-MSFT, could you please provide an update?

**Comment by jahsu-MSFT** [comment]
@avivanoff Because of some complications, the version 2.163.1 doesn't have the latest bits. For the latest bits to be deployed to all the accounts, it will most likely happen in early/mid January since most of the staffs are out during this time and we are not going to do any deployments from now to new year's day. 
For now to unblock, can you try manually installing the version 2.162.0? 

Thanks for your patience,

**Comment by avivanoff** [comment]
@jtpetty, @jahsu-MSFT, looks like 2.164.0 has the fix. Any chance our account will get it before the New Year?

**Comment by jtpetty** [comment]
@avivanoff - we will start rolling out 2.164.0 to all accounts after the new year. With so many people out on vacation between now and then, we are unable to push out any major updates.

**Comment by avivanoff** [comment]
@jtpetty, ETA?

**Comment by avivanoff** [comment]
@jtpetty, do you have any updates on rollout state?

**Comment by jtpetty** [comment]
2.164.1 started rolling out this week. There is a minor fix for an unrelated item going in today and we will continue rolling out the agent next week.

**Comment by dalexsoto** [comment]
Unfortunately I am hitting this in 2.164.1

```
Microsoft.TeamFoundation.Build.WebApi.BuildArtifact is not of type PipelineArtifact, FileShare or BuildArtifact
```

**Comment by avivanoff** [comment]
@jtpetty, there are two mode releases. Which one is begin rolled out?

**Comment by jtpetty** [comment]
2.164.3 is currently being rolled out. As an aside, we are also working a way to better communicate agent rollout status.

**Comment by avivanoff** [comment]
@jtpetty, assuming there are no issues, how long does it take to roll out the agent to all rings?

**Comment by jtpetty** [comment]
We roll to one ring per business day, except for Friday, and we have 6 rings.

**Comment by avivanoff** [comment]
@jtpetty, can you tell me which ring our organization "Ivanti" is in? That should give me a good idea when to expect the update.

**Comment by jtpetty** [comment]
@avivanoff - You are in Ring 5. If everything goes smooth, hopefully the update will get rolled out to you on Wednesday.

**Comment by avivanoff** [comment]
@jtpetty, is Ring 5 on schedule?

**Comment by jtpetty** [comment]
@avivanoff - Unfortunately, no. We found a few issues when we got to ring 3. I am working with the team to get the fixes in and released as quickly as we can to get back on track but minimize disruption.

**Comment by avivanoff** [comment]
@jtpetty, what is the new ETA?

**Comment by jtpetty** [comment]
Currently, it Ring 5 is scheduled for Monday 1/27

**Comment by avivanoff** [comment]
@jpetty, @jahsu-MSFT, looks like this fix introduced [other problems](https://github.com/microsoft/azure-pipelines-agent/issues/2755).

**Comment by jahsu-MSFT** [comment]
Closing this ticket and @fadnavistanmay who is taking over the PA feature, please take a look the issue mentioned above.
