### ISSUE TITLE
AzureResourceGroupDeployment@2 warring CorrelationIdForARM

### ISSUE THREAD

**Issue by jpodoba** [microsoft/azure-pipelines-tasks#12060]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeployment@2

- Agent - Hosted: vs2017-win2016

## Issue Description

Getting error when using task AzureResourceGroupDeployment@2 from 19th December 2019. It used to deploy resources. I've tested today as well on different pipelines and the result is the same. I've found similar issue but different task here:

https://github.com/microsoft/azure-pipelines-tasks/issues/11996

### Task logs

```
2019-12-19T08:28:50.1909482Z ##[section]Starting: Deploy Shared Resources
2019-12-19T08:28:50.2020565Z ==============================================================================
2019-12-19T08:28:50.2020690Z Task         : Azure resource group deployment
2019-12-19T08:28:50.2020803Z Description  : Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
2019-12-19T08:28:50.2020892Z Version      : 2.162.2
2019-12-19T08:28:50.2020992Z Author       : Microsoft Corporation
2019-12-19T08:28:50.2021085Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
2019-12-19T08:28:50.2021205Z ==============================================================================
2019-12-19T08:28:50.5958019Z Checking if the following resource group exists: RGContactRepoTest.
2019-12-19T08:28:50.8817152Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:28:50.8825768Z Resource group exists: true.
2019-12-19T08:28:50.8825956Z Creating deployment parameters.
2019-12-19T08:28:50.8852119Z The detected encoding for file 'd:\a\r1\a\_XXX\azuredeploy.json' is 'utf-8'
2019-12-19T08:28:50.8985298Z The detected encoding for file 'd:\a\r1\a\_XXX\TEST.azuredeploy.parameters.json' is 'utf-8'
2019-12-19T08:28:50.8991719Z Starting Deployment.
2019-12-19T08:28:50.9021998Z Deployment name is azuredeploy-20191219-082850-e88f
2019-12-19T08:28:52.7600260Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:28:52.8188205Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:29:07.8675063Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:29:23.2600651Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:29:37.9598566Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:29:53.0076879Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:29:53.0750838Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2019-12-19T08:29:53.0755345Z Successfully deployed the template.
2019-12-19T08:29:53.0833100Z ##[section]Finishing: Deploy Shared Resources
```

Today logs:

```
2020-01-02T07:59:35.6470349Z ##[section]Starting: Deploy DataFactory: Logic
2020-01-02T07:59:35.6588607Z ==============================================================================
2020-01-02T07:59:35.6588790Z Task         : Azure resource group deployment
2020-01-02T07:59:35.6588888Z Description  : Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
2020-01-02T07:59:35.6589071Z Version      : 2.162.2
2020-01-02T07:59:35.6589137Z Author       : Microsoft Corporation
2020-01-02T07:59:35.6589276Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
2020-01-02T07:59:35.6589379Z ==============================================================================
2020-01-02T07:59:36.0829268Z Checking if the following resource group exists: RGContactRepoWE.
2020-01-02T07:59:36.3757794Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-02T07:59:36.3761972Z Resource group exists: true.
2020-01-02T07:59:36.3764962Z Creating deployment parameters.
2020-01-02T07:59:36.3850882Z The detected encoding for file 'd:\a\r1\a\_XXX\arm_template.json' is 'utf-8'
2020-01-02T07:59:36.4331792Z The detected encoding for file 'd:\a\r1\a\_XXX\arm_template_parameters.json' is 'utf-8'
2020-01-02T07:59:36.4361578Z Starting Deployment.
2020-01-02T07:59:36.4398726Z Deployment name is arm_template-20200102-075936-c197
2020-01-02T07:59:38.7763384Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-02T07:59:38.8563842Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-02T07:59:54.0038868Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-02T07:59:54.1409006Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-02T07:59:54.1414384Z Successfully deployed the template.
2020-01-02T07:59:54.1500574Z ##[section]Finishing: Deploy DataFactory: Logic
```

**Comment by bishal-pdMSFT** [comment]
@SumiranAgg isn't this already fixed? or is it the case that ARG task version has not been bumped up with this common change?

**Comment by eaarora-ms** [comment]
@jpodoba  Hi, we have already fixed the issue for all the tasks and it should be available in all the accounts by the end of this week.

**Comment by frackham** [comment]
Is this fixed in v2 as well as v3? 

v3 doesn't seem to support parameterised service connections so I suspect I'll need to live with the warnings?

**Comment by jpodoba** [comment]
> @jpodoba Hi, we have already fixed the issue for all the tasks and it should be available in all the accounts by the end of this week.

Thanks for confirmation @eaarora-ms  I will track that and if issue still will be in task I will let you know

**Comment by eaarora-ms** [comment]
@frackham  It is fixed for both of them yes. You will not see the warnings once the deployment is done in any of the tasks.

**Comment by jpodoba** [comment]
Good morning @eaarora-ms I've checked few minutes ago and issue is still there.
Below are logs:

```
2020-01-09T07:27:22.4833068Z ##[section]Starting: Deploy Shared Resources
2020-01-09T07:27:22.4946934Z ==============================================================================
2020-01-09T07:27:22.4947058Z Task         : Azure resource group deployment
2020-01-09T07:27:22.4947171Z Description  : Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
2020-01-09T07:27:22.4947275Z Version      : 2.162.2
2020-01-09T07:27:22.4947351Z Author       : Microsoft Corporation
2020-01-09T07:27:22.4947445Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
2020-01-09T07:27:22.4947564Z ==============================================================================
2020-01-09T07:27:22.9038239Z Checking if the following resource group exists: RGContactRepoTest.
2020-01-09T07:27:23.2164404Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:27:23.2172635Z Resource group exists: true.
2020-01-09T07:27:23.2173095Z Creating deployment parameters.
2020-01-09T07:27:23.2201205Z The detected encoding for file 'd:\a\r1\a\_XXX\azuredeploy.json' is 'utf-8'
2020-01-09T07:27:23.2340783Z The detected encoding for file 'd:\a\r1\a\_XXX\TEST.azuredeploy.parameters.json' is 'utf-8'
2020-01-09T07:27:23.2351451Z Starting Deployment.
2020-01-09T07:27:23.2385850Z Deployment name is azuredeploy-20200109-072723-b4d6
2020-01-09T07:27:25.7478145Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:27:25.7832751Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:27:40.8597424Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:27:55.9259931Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:28:10.9701962Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:28:26.0291655Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:28:41.0749085Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:28:41.1271914Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:28:41.1273479Z Successfully deployed the template.
2020-01-09T07:28:41.1338805Z ##[section]Finishing: Deploy Shared Resources
```

```
2020-01-09T07:29:22.2007504Z ##[section]Starting: Deploy DataFactory: Logic
2020-01-09T07:29:22.2119139Z ==============================================================================
2020-01-09T07:29:22.2119344Z Task         : Azure resource group deployment
2020-01-09T07:29:22.2119458Z Description  : Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
2020-01-09T07:29:22.2119561Z Version      : 2.162.2
2020-01-09T07:29:22.2119625Z Author       : Microsoft Corporation
2020-01-09T07:29:22.2119733Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
2020-01-09T07:29:22.2119839Z ==============================================================================
2020-01-09T07:29:22.6260775Z Checking if the following resource group exists: RGContactRepoTest.
2020-01-09T07:29:22.9977232Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:29:22.9981633Z Resource group exists: true.
2020-01-09T07:29:22.9983861Z Creating deployment parameters.
2020-01-09T07:29:23.0066391Z The detected encoding for file 'd:\a\r1\a\_XXX\arm_template.json' is 'utf-8'
2020-01-09T07:29:23.0536009Z The detected encoding for file 'd:\a\r1\a\_XXX\arm_template_parameters.json' is 'utf-8'
2020-01-09T07:29:23.0567640Z Starting Deployment.
2020-01-09T07:29:23.0591889Z Deployment name is arm_template-20200109-072923-95a8
2020-01-09T07:29:24.6438448Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:29:24.7010959Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:29:39.7494518Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:29:54.7968611Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:30:09.8706775Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:30:09.9368504Z ##[warning]Can\'t find loc string for key: CorrelationIdForARM
2020-01-09T07:30:09.9376216Z Successfully deployed the template.
2020-01-09T07:30:09.9452919Z ##[section]Finishing: Deploy DataFactory: Logic
```

**Comment by eaarora-ms** [comment]
@jpodoba  Hi, the deployments are still under progress. Please wait until the end of this week. Thank you for the patience.

**Comment by eaarora-ms** [comment]
The fix is rolled out to all accounts. Please let us know if you are still facing the issue.
