### ISSUE TITLE
Docker@2: warning when using  DOCKER_BUILDKIT: 1

### ISSUE THREAD

**Issue by obeyda** [microsoft/azure-pipelines-tasks#12470]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Docker@2  

## Environment
- Server - Azure Pipelines
- Agent - Hosted: 

## Issue Description
When i use `DOCKER_BUILDKIT: 1` in my pipeline i get this warning 
```
##[warning]No data was written into the file /home/vsts/work/_temp/task_outputs/build_****.txt

```

**Comment by taurit** [comment]
I investigated a bit and this might be caused by the fact that when `DOCKER_BUILDKIT` is enabled, Docker seems to [send all output to the _stderr_ and not _stdout_](https://github.com/moby/buildkit/issues/1186). So output of the task can indeed be seen as empty, even though we the logs are available in the DevOps task logs (they come from _stderr_).

At first glance it looks to me like the Docker task needs to be adjusted to this design. I haven't found a workaround so far.

**Comment by sonayak** [comment]
The fix has been checked in. It will be deployed in next release.

**Comment by robearlam** [comment]
Has this fix been rolled out yet as I'm still seeing this error on our builds?

**Comment by ds-ms** [comment]
Yes, this fix has been rolled out; what are the errors you're seeing?

**Comment by robearlam** [comment]
Same warning as in the original post, when I build my images using the following task

```
- task: DockerCompose@0
  displayName: "Build Images"
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'XXXX'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: '$(DOCKER_COMPOSE_ARGS)'
    qualifyImageNames: false
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)-$(Build.SourceBranchName)'
    includeLatestTag: true
```

I get this warning thrown for each tag, for image built
`##[warning]No data was written into the file d:\a\_temp\task_outputs\XXXX.log`

**Comment by ds-ms** [comment]
What's the version of the dockerCompose task in your logs?

**Comment by robearlam** [comment]
The log file for that task opens with....

```
Starting: Build Images
==============================================================================
Task         : Docker Compose
Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
Version      : 0.166.6
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-compose-tsg
==============================================================================
```

Is that what you were referring to?

**Comment by robearlam** [comment]
Any update on this @ds-ms ?

**Comment by Styxxy** [comment]
@ds-ms 

I'm getting the same error. With version 0.175.0

```
==============================================================================
Task         : Docker Compose
Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
Version      : 0.175.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-compose-tsg
==============================================================================
```

**Comment by ds-ms** [comment]
@ajinkya599 could you take a look?

**Comment by keifgwinn** [comment]
We're seeing this 

- task: DockerCompose@0
  displayName: Build frontend & backend
  inputs:
    action: Build services
    dockerComposeFile: docker-compose.prod.yml
    projectName: $(Build.Repository.Name)
    additionalImageTags: $(Build.BuildId)

**Comment by ajinkya599** [comment]
I have fixed the empty file write warning with #14321. This will be rolled-out with our next deployment.
I was not able to repro the behavior for the build case. However, the fix should take care of that too.

**Comment by kconner** [comment]
I've got the same issue with a `docker image save` command run by `Docker@2`:

```
Starting: Save Images
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.181.2
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg
==============================================================================
/usr/bin/docker image save ***/slingshot-docker:test -o /home/vsts/work/1/a/images.tar
##[warning]No data was written into the file /home/vsts/work/_temp/task_outputs/image_1616001124328.txt
Finishing: Save Images
```

Task configuration:

```
  - task: Docker@2
    displayName: Save Images
    inputs:
      containerRegistry: 'ContainerRegistry'
      command: 'image'
      arguments: 'save $(registryFullName)/$(imageRepository):test -o $(Build.ArtifactStagingDirectory)/images.tar'
```

**Comment by groogiam** [comment]
@ajinkya599 This does not appear to fixed. I am getting this warning on my self hosted windows agent.

**Comment by reedptaylor** [comment]
Also getting this error with ```docker image save``` command run by ```Docker@2```

**Comment by bingofingers** [comment]
and docker tag

`##[warning]No data was written into the file /home/vsts/work/_temp/task_outputs/tag_1625079372396.txt
`

**Comment by dimiboi** [comment]
Issue still present as of today.

**Comment by rkydybets** [comment]
The issue is still present.

**Comment by marzulo** [comment]
Please reopen. Same here.

**Comment by NelsonBN** [comment]
Still having this warning with:

```text
Starting: Saving docker image
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.192.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg
==============================================================================
/usr/bin/docker save *** -o /home/vsts/work/1/a/***.tar
##[warning]No data was written into the file /home/vsts/work/_temp/task_outputs/save_1639396292669.txt
Finishing: Saving docker image
```

```yml
- task: Docker@2
  displayName: 'Saving docker image'
  inputs:
    command: save
    arguments: '$(dockerImageName) -o $(Build.ArtifactStagingDirectory)/$(dockerFileName)'
```

**Comment by kanovic** [comment]
Warnining still persistent with:
```
Starting: Save image
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.201.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg
==============================================================================
/usr/bin/docker save --output /home/vsts/work/1/a/frontend-app.tar frontend-app:20220713.1.1
##[warning]No data was written into the file /home/vsts/work/_temp/task_outputs/save_1657879453517.txt
Finishing: Save image
```
```
  - task: Docker@2
    displayName: "Save image"
    inputs:
      command: "save"
      arguments: "--output $(Build.ArtifactStagingDirectory)/frontend-app.tar frontend-app:$(newSemVer)"
      addPipelineData: false
```

**Comment by dougclutter** [comment]
We're getting this too. To work around it, we're using Bash to save our docker image:
```
  - task: Bash@3
    displayName: Save image
    inputs:
      targetType: inline
      script: docker save ${{ variables.imageName }} --output ${{ variables.imageFile }}

```

**Comment by czietsman** [comment]
The issue was fixed for DockerCompose@0 and for the Docker@2 task.

**Comment by xiwenc** [comment]
Please reopen the issue. It's not yet fixed for `Docker@2`, the original report. We are still seeing this warning today.

**Comment by Mertsch** [comment]
Still happening with `Version      : 2.212.1`

**Comment by SBFrancies** [comment]
Also having this issue with docker build - I think it should be reopened /reopen

**Comment by dlerps** [comment]
How is this closed? Still having the same bug with `command: build`
Reopen please!

**Comment by btorsaldivar** [comment]
Well, posting here to confirm that this issue is still NOT resolved. If this help, the warning message only show up on Linux based Agents. I cannot replicate this building windows container images running on Windows Agents


```
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
Version      : 2.214.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-tsg

**Comment by slayoffer** [comment]
Having the same issue on self-hosted Linux agent

**Comment by JtMotoX** [comment]
Since this issue was closed, even though it is unresolved, I have re-opened this issue https://github.com/microsoft/azure-pipelines-tasks/issues/17893.
Please go give it a thumbs up if you are still having this issue.

**Comment by sboulema** [comment]
Still receiving this as a warning using ubuntu-latest from the Azure Pipelines Pool

    =========================================================
    Task         : Docker
    Description  : Build or push Docker images, login or logout, start or stop containers, or run a Docker command
    Version      : 2.221.0
    Author       : Microsoft Corporation
    Help         : https://aka.ms/azpipes-docker-tsg

**Comment by i-Coderr** [comment]
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/76399128/6567f786-9270-463d-8522-1701d89aa561)

**Comment by doc** [comment]
Still seeing this warning with hosted agent and Docker task ...

**Comment by Sam-Tymoshchuk** [comment]
Same for me, any workarounds possible to silence it?
