### ISSUE TITLE
PublishCodeCoverageResults can't find its own html report when the agent is installed to a dir with a space in the name

### ISSUE THREAD

**Issue by DevRCRun** [microsoft/azure-pipelines-tasks#13062]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  PublishCodeCoverageResults@1

## Environment
- Server - Azure Pipelines 
   

- Agent - Hosted or Private: 
    
        - Self hosted agent: vsts-agent-win-x64-2.168.2

    - Windows Server 2019 (1809)

## Issue Description

Task is configured to process a cobertura-coverage.xml produced by jest

```
        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: './coverage/cobertura-coverage.xml'
            failIfCoverageEmpty: true
```
On execution, the task processes this and writes the report to a new (unexpected?) directory

```
Writing report file 'D:\Azure\index.htm'
```

This and other output files representing the source files are written correctly. 
The cobertura-coverage.xml is uploaded as an artifact.

However the task then states

```
Generated code coverage html report: D:\Azure Agent\vsts-agent-win-x64-2.168.2\_work\_temp\cchtml
```

and generates a warning

```
##[warning]Directory not found: 'D:\Azure Agent\vsts-agent-win-x64-2.168.2\_work\_temp\cchtml
```

There is nothing in that _temp directory.

If I specifically set reportDirectory to 'D:\Azure\' within the task it complains 

```
[warning]Ignoring coverage report directory with Html content as we are auto-generating Html content
```

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops doesn't document the reportDirectory option aside to say it's optional.

Have I come across a bug or is my configuration wrong?

Many thanks

**Comment by eps1lon** [comment]
The warning 
> Ignoring coverage report directory with Html content as we are auto-generating Html content


went wait when removing `reportDirectory` in https://github.com/eps1lon/dom-accessibility-api/pull/289.

As far as I could tell this was only a warning. Everything was working as expected.

<details>
<summary>Initialize job log</summary>

```
Starting: Initialize job
Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az101'
Current agent version: '2.170.1'
Operating System
Ubuntu
18.04.4
LTS
Virtual Environment
Environment: ubuntu-18.04
Version: 20200604.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200604.1/images/linux/Ubuntu1804-README.md
Current image version: '20200604.1'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: NodeTool (0.166.2)
Downloading task: CmdLine (2.164.2)
Downloading task: PublishPipelineArtifact (1.2.3)
Downloading task: DownloadPipelineArtifact (2.3.1)
Downloading task: PublishTestResults (2.170.0)
Downloading task: PublishCodeCoverageResults (1.160.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

```
</details>

**Comment by DevRCRun** [comment]
Maybe something specific to windows self hosted agent then? Either with the reportDirectory set or not nothing got uploaded. 

Let me know when your change should be available to the pipeline and I'll give it another try.

**Comment by DevRCRun** [comment]
Ah. Is this the problem? If you look below is it choking on the space in targetdir? That would explain why it's creating a D:\Azure directory in its own initiative!

`2020-06-15T14:41:02.2883739Z [command]"D:\Azure Agent\localservice\_work\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.160.3\net47\ReportGenerator.exe" -reports:./coverage/cobertura-coverage.xml -targetdir:D:\Azure Agent\localservice\_work\_temp\cchtml -reporttypes:HtmlInline_AzurePipelines
2020-06-15T14:41:02.3443418Z 2020-06-15T15:41:02: Arguments
2020-06-15T14:41:02.3444601Z 2020-06-15T15:41:02:  -reports:./coverage/cobertura-coverage.xml
2020-06-15T14:41:02.3445362Z 2020-06-15T15:41:02:  -targetdir:D:\Azure
2020-06-15T14:41:02.3446093Z 2020-06-15T15:41:02:  Agent\localservice\_work\_temp\cchtml
2020-06-15T14:41:02.3446863Z 2020-06-15T15:41:02:  -reporttypes:HtmlInline_AzurePipelines`

**Comment by DevRCRun** [comment]
I can confirm that the space in the directory name where the agent is installed is causing the problem. With the agent installed to a directory without a space in the path the issue does not occur and the report html is correctly uploaded. Renaming the issue to better reflect this.

**Comment by adamconnelly** [comment]
It looks like the change in https://github.com/microsoft/azure-pipelines-tasks/pull/13861 to quote the path to the ReportGenerator.dll causes this task to break on Linux agents. I've added a full description of the problem here: https://github.com/microsoft/azure-pipelines-tasks/issues/13914#issuecomment-731019183.

Can this change be temporarily reverted until a fix that doesn't break the task can be made?

**Comment by ShreyasRmsft** [comment]
@adamconnelly yes. We will try and patch this immediately.

**Comment by DaniilShmelev** [comment]
Hi @DevRCRun, we've fixed this issue, but it may take a few weeks until the changes are deployed. We'll let you know once they're available.

**Comment by anatolybolshakov** [comment]
Hi @DevRCRun we have rolled out the fix for this issue, let me close this since it was fixed - please feel free to reopen it or ask any further questions if it's still actual for you.

**Comment by agray** [comment]
Has this fix been pushed to all regions?  We are in Australia South East.  I have customers saying it is still not working.

**Comment by DaniilShmelev** [comment]
Hi @agray! This change has been deployed to all regions. Could you please provide us with some more information about the Azure DevOps they use (cloud or on-premise), agent (version and if it is self-hosted), the pipeline definition and logs? We're looking forward to hearing from you.

**Comment by agray** [comment]
> Hi @agray! This change has been deployed to all regions. Could you please provide us with some more information about the Azure DevOps they use (cloud or on-premise), agent (version and if it is self-hosted), the pipeline definition and logs? We're looking forward to hearing from you.

Users in our organisation (/colesgroup) are still reporting not being able to see the code coverage information.  What is Microsoft doing to restore service?

**Comment by nishantms** [comment]
Hi @agray , as asked by @DaniilShmelev , can you share more details e.g Pipeline, logs, agent. This help us to debug the issue thoroughly.

**Comment by agray** [comment]
Here is an example app I wrote.  It is a dotnetcore 3 app running nunit3 unit tests and using coverlet/opencover to watch the tests and publish results with reportgenerator.

![image](https://user-images.githubusercontent.com/118102/110725889-7707a280-826c-11eb-9f01-14495b22666f.png)
 
![image](https://user-images.githubusercontent.com/118102/110726000-b6ce8a00-826c-11eb-9742-123d69964e69.png)

![image](https://user-images.githubusercontent.com/118102/110726086-eb424600-826c-11eb-8821-37a62496a4b3.png)

![image](https://user-images.githubusercontent.com/118102/110726182-17f65d80-826d-11eb-8cb8-5df16e6b3443.png)

Problem is the Code Coverage tab has disappeared and not come back.

**Comment by ganesp** [comment]
@agray 
We recommend using the following task to publish the code coverage results:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops

You are using the report generator tool directly, which will generate the report but wont publish it.
Publish code coverage results task uses report generator tool internally to generate the report and then publishes that report to  AzureDevOps as an build artifact.

**Comment by agray** [comment]
@ganesp
Thanks for replying. I looked at that docs link you provided and removed my 'Create Code coverage report' (which was running reportgenerator@4) step as you suggested.  My comment from March 11th still applies.  It does not work.

Extract of my YAML
` # UnitTests
    - task: DotNetCoreCLI@2
      displayName: 'Unit Tests'
      inputs:
        command: test
        projects: '$(APEX_SOLUTION)'
        arguments: '--no-restore -c $(BUILD_CONFIGURATION) /p:CollectCoverage=true /p:CoverletOutput=$(Agent.TempDirectory)/ /p:CoverletOutputFormat=opencover /p:Threshold=50 /p:ThresholdType=branch /p:ThresholdStat=Average /p:Exclude="[Redacted.Views]*"'
        testRunTitle: 'Unit Tests $(Build.DefinitionName) - $(Build.BuildNumber)'

    ## Code Coverage Report    
    #- task: reportgenerator@4
    #  displayName: 'Create Code coverage report'
    #  inputs:
    #    reports: '$(Agent.TempDirectory)/$(RAWOUTPUT)'
    #    targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
    #    reporttypes: 'HtmlInline_AzurePipelines_Dark;SonarQube'
    #    tag: '$(Build.BuildNumber)'
       
    # Publish Code Coverage
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Agent.TempDirectory)/$(RAWOUTPUT)'
        reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'`


This is what I still see in Azure DevOps:

![image](https://user-images.githubusercontent.com/118102/119422889-5916ed80-bd45-11eb-8a96-ea6f637a41a8.png)

I am expecting to see a Code Coverage tab with the reportgenerator HTML report which I used to see.  My YAML pipeline has not changed for over a year.

**Comment by agray** [comment]
@DevRCRun Would you mind please reopening this issue as I don't believe it is fixed.  Open to hearing if there is something I am not seeing or doing correctly.  See my above comment

**Comment by agray** [comment]
I have resolved my issue. https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=netearlierversions#collect-code-coverage-metrics-with-coverlet section helped.  I was the PEBKAC. I updated all my NuGet packages this morning that were compatible with my core3.1 application and emitted cobertura rather than opencover xml from my unit tests.  Thanks all.
