### ISSUE TITLE
[Bash@3] The task doesn't work after upgrading to the 3.177.0 version

### ISSUE THREAD

**Issue by al-cheb** [microsoft/azure-pipelines-tasks#13762]
## Note  
The Bash@3 task doesn't work after upgrading to the 3.176.0 -> 3.177.0 version. The same issue occurs if we change Bash@3 to CommandLine Version: 2.177.0. 

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Bash@3  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/BashV3

## Environment
- Server - Azure Pipelines 
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      project: mseng
      definitionId: 4029
      releaseId: 15399754

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: Ubuntu / 2.164.8
      
## Issue Description
<img width="1215" alt="screen_shot_2020-10-23_at_12 03 47_pm" src="https://user-images.githubusercontent.com/47745270/97036523-a09b8800-1570-11eb-9c59-aa94daaa77b1.png">

The issue doesn't reproduce with 3.176.0 version:
<img width="854" alt="screen_shot_2020-10-23_at_12 02 47_pm" src="https://user-images.githubusercontent.com/47745270/97036720-e5272380-1570-11eb-88f9-f220147fcb76.png">

### Task logs

```
2020-10-23T17:45:54.4600317Z ##[debug]Evaluating condition for step: 'Get Rack'
2020-10-23T17:45:54.4600781Z ##[debug]Evaluating: succeeded()
2020-10-23T17:45:54.4600947Z ##[debug]Evaluating succeeded:
2020-10-23T17:45:54.4601196Z ##[debug]=> True
2020-10-23T17:45:54.4601372Z ##[debug]Result: True
2020-10-23T17:45:54.4601581Z ##[section]Starting: Get Rack
2020-10-23T17:45:54.4604923Z ==============================================================================
2020-10-23T17:45:54.4604989Z Task         : Bash
2020-10-23T17:45:54.4605043Z Description  : Run a Bash script on macOS, Linux, or Windows
2020-10-23T17:45:54.4605142Z Version      : 3.177.0
2020-10-23T17:45:54.4605191Z Author       : Microsoft Corporation
2020-10-23T17:45:54.4605291Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2020-10-23T17:45:54.4605352Z ==============================================================================
2020-10-23T17:45:54.4799111Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2020-10-23T17:45:54.4811794Z ##[debug]System.Exception: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2020-10-23T17:45:54.4813272Z ##[section]Finishing: Get Rack 
```

**Comment by damccorm** [comment]
Hey, we are working on a fix to this right now - in the meantime, upgrading your agents to the most recent version should fix this

**Comment by al-cheb** [comment]
@damccorm, Thank you. Upgrading agents to version 2.175.2 fix the issue. Feel free to close the thread.

**Comment by damccorm** [comment]
I'll keep it open until the issue is fully fixed - thanks for confirming

**Comment by damccorm** [comment]
This should be fixed now!

**Comment by jeisonmp** [comment]
I still receive error

![image](https://user-images.githubusercontent.com/9480995/97064244-e2313080-157a-11eb-86d2-2c84fba60ee3.png)
