### ISSUE TITLE
Unable to locate executable file: 'iotedgedev'

### ISSUE THREAD

**Issue by oliverchristen** [microsoft/azure-pipelines-tasks#14167]
*Type*: Bug

**Enter Task Name**: AzureIoTEdgeV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted
vmImage ubuntu 20.04.1
agent version 2.179.0
AzureIoTEdge task version 2.4.5

## Issue Description
##[error]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

This happened from time to time and solves itself after some hours. But it happens again every few weeks.

All the required informations are found here:
https://developercommunity.visualstudio.com/content/problem/1282804/errorerror-unable-to-locate-executable-file-iotedg-1.html

If full log is required, I can provide it privately.

**Comment by Haeavar** [comment]
We have the same issue. It appears since yesterday without any changes.

AzureIoTEdge task version 2.4.5
Pool: Azure Pipelines
Image: ubuntu-18.04
Agent: Azure Pipelines 4

**Comment by oliverchristen** [comment]
It will disappear after some hours magically probably.
What you could try is to install iotedgedev manually
```
steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'pip install -U iotedgedev'
```

**Comment by randomstring384540** [comment]
+1. Not liking the idea of manually installing dependencies for devops tasks

**Comment by oliverchristen** [comment]
Totally agree. The suggestion is meant as a workaround. 

But for deploying deploment manifests to IoT hub, we switched to custom azure CLI script. This is weirdly much faster than the IoT Edge pipeline task.

**Comment by holmeren** [comment]
I just stumbled upon this issue aswell. Did you just wait a few hours, and ran the pipeline again?

**Comment by randomstring384540** [comment]
Our pipeline still failed today in the moring. Therefore we replaced the devops task with a custom script.

**Comment by holmeren** [comment]
Did the script include the 'pip install -U iotedgedev' mentioned above?

I'm not sure how to install iotedgedev

**Comment by oliverchristen** [comment]
@holmeren This happened to me about three times. In my case it disappeared every time after some hours, when I retried to run the pipeline.
The command `pip install -U iotedgedev` installs iotedgedev.

**Comment by oliverchristen** [comment]
@randomstring384540 could you share your custom script to replace the IoTEdge pipeline task `Generate deployment manifest`?

**Comment by oliverchristen** [comment]
@randomstring384540 Oh, I just saw, its logged in the pipeline run:
`/usr/local/bin/iotedgedev genconfig --file /home/vsts/work/1/s/<path to deployment template>/deployment.template.json --platform amd64 --fail-on-validation-error`

**Comment by holmeren** [comment]
After 14 hours and no success, i tried updating Agent Specification fromubunto-18.04 -> ubunto-20.04, and it seems to work :)

**Comment by anatolybolshakov** [comment]
Hi @holmeren @oliverchristen is this issue still reproducible for you?

**Comment by oliverchristen** [comment]
@anatolybolshakov not for me at the moment.

**Comment by kiranpradeep** [comment]
@anatolybolshakov Yes. It is reproducible for me if I don't specify a build agent. It goes away if I add below to YAML.

```yaml
pool:
  vmImage: ubuntu-latest
```

**Comment by anatolybolshakov** [comment]
@microsoft/akvelon-ecosystem-team this seem to be related to some difference between ubuntu-18.04 and ubuntu-20.04 - do you know if this is some known issue?

**Comment by miketimofeev** [comment]
@anatolybolshakov it's not known. We will take a look

**Comment by miketimofeev** [comment]
@kiranpradeep @holmeren I'm unable to reproduce the issue on Ubuntu 18 Image version **20210330.1**. 
These steps from the task work correctly and I'm able to call iotedgedev:
https://github.com/microsoft/azure-pipelines-tasks/blob/8c190dc05cd7e13575a16e3a25f069f5dfed8452/Tasks/AzureIoTEdgeV2/util.ts#L88-L94
Could you please clarify, on which version do you see the issue? It can be found here
![image](https://user-images.githubusercontent.com/48208649/113873947-f762ea00-97bd-11eb-8b78-adaf89beae33.png)

**Comment by kiranpradeep** [comment]
Version: 20210327.1

**Comment by miketimofeev** [comment]
@kiranpradeep it looks like if you don't specify the vmImage the pipeline will run on Ubuntu **16**.04, which is not supported by the task I guess. 
@anatolybolshakov do you happen to know if the task worked on Ubuntu16?

**Comment by kiranpradeep** [comment]
As on 2021-03-12T12:47:51.4740078Z, the task worked for Ubuntu 16.04.7. The Version field then was 20210302.0.

**Comment by karakal** [comment]
As of today we have the same problem. Our Build-Pipeline is not running anymore with any agent (I event tried the Windows one...)
Environment: ubuntu-18.04
Version: 20210330.1

**Comment by miketimofeev** [comment]
@karakal could you please share the logs?

**Comment by miketimofeev** [comment]
@kiranpradeep @anatolybolshakov it looks like some of the pip modules drop support for python 3.5, which is the default one on Ubuntu 16

**Comment by karakal** [comment]
> 
> 
> @karakal could you please share the logs?

Here you find my log. I removed all private parts of the log, I hope the requested information can be find within....

[azure-pipeline.log](https://github.com/microsoft/azure-pipelines-tasks/files/6277167/azure-pipeline.log)

**Comment by karakal** [comment]
> 
> 
> @kiranpradeep @anatolybolshakov it looks like some of the pip modules drop support for python 3.5, which is the default one on Ubuntu 16

I tried the build on:

- Ubuntu 20.04
- Ubuntu 18.04
- Ubuntu 16.04
- even Windows-2019

The build failed with all agents.

**Comment by miketimofeev** [comment]
@karakal what version of task do you use? 
@anatolybolshakov it seems that for ubuntu 16 we need a workaround regarding cryptolib installation — these steps work:
```
sudo apt install python3-pip
sudo pip3 install --upgrade pip==20.3.4
sudo pip3 install --upgrade cryptography
sudo pip3 install --upgrade iotedgedev
iotedgedev --version
```

**Comment by karakal** [comment]
> 
> 
> @karakal what version of task do you use?

2.* I don't have any other choice?

**Comment by miketimofeev** [comment]
@karakal Sorry, I meant the exact version, found it from the logs — `2021-04-08T07:00:59.8075822Z Version      : 2.4.5`
. 
I'm asking because there are significant changes between versions 2.4.5 and 2.4.6.

**Comment by dastevens** [comment]
I have the same issue, I am using ubuntu-latest, the build started failing when the version number of the Azure IoT Edge was bumped from 2.4.5 (working) to 2.4.6 (no longer working):

![image](https://user-images.githubusercontent.com/13847173/114147477-07dba780-9919-11eb-9c84-f811ef572ca6.png)

![image](https://user-images.githubusercontent.com/13847173/114147493-0b6f2e80-9919-11eb-9f41-1894a012e234.png)

**Comment by dastevens** [comment]
When I pin the task version to 2.4.5 the build passes:

![image](https://user-images.githubusercontent.com/13847173/114156370-cb14ae00-9922-11eb-956b-ed9732408ff0.png)

**Comment by karakal** [comment]
My build fails also with 2.4.5 :-(
![grafik](https://user-images.githubusercontent.com/2448293/114159245-df0ddf00-9925-11eb-9b25-b0a6fc882f2d.png)

**Comment by oliverchristen** [comment]
I think its more related to the vmimage version than the task version. I could think that iotedgedev is preinstalled normally but isn't on some versions of the vmimage.

**Comment by miketimofeev** [comment]
@oliverchristen iotedgedev is not preinstalled on the image, it's being installed during the task

**Comment by karakal** [comment]
So what should we do do get it working again? i should do a productive
release for days now...

Mikhail Timofeev ***@***.***> schrieb am Fr., 9. Apr. 2021,
11:56:

**Comment by oliverchristen** [comment]
@karakal did you try this? What's the result? 
https://github.com/microsoft/azure-pipelines-tasks/issues/14167#issuecomment-808256842

**Comment by karakal** [comment]
> @karakal did you try this? What's the result?
> [#14167 (comment)](https://github.com/microsoft/azure-pipelines-tasks/issues/14167#issuecomment-808256842)

Another error of not matching docker-versions...

[azure-log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/6285733/azure-log.txt)

**Comment by karakal** [comment]
Okay, sorry, with Ubuntu 20.04 the build process did run through...

**Comment by anatolybolshakov** [comment]
@miketimofeev @karakal @oliverchristen thanks for investigation! 
@marianan could you please take a look? Looks like we need to change installation commands here to adopt to last updates:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureIoTEdgeV2/util.ts#L88

> @karakal what version of task do you use?
> @anatolybolshakov it seems that for ubuntu 16 we need a workaround regarding cryptolib installation — these steps work:
> 
> ```
> sudo apt install python3-pip
> sudo pip3 install --upgrade pip==20.3.4
> sudo pip3 install --upgrade cryptography
> sudo pip3 install --upgrade iotedgedev
> iotedgedev --version
> ```

**Comment by marianan** [comment]
@anatolybolshakov we are investigating

**Comment by karakal** [comment]
> 
> > @karakal what version of task do you use?

2.4.5

`Task         : Azure IoT Edge
Description  : Build and deploy an Azure IoT Edge image
Version      : 2.4.5
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/***/devops/pipelines/tasks/build/***-iot-edge
==============================================================================`

**Comment by cindydeng1998** [comment]
Thank you for your comments @anatolybolshakov @karakal and all. At this point, iotedgedev only supports python version 3.6 and python 3.7. The default Python version on Linux 20.04 hosted agents is 3.8, so we anticipate it not working in that environment. The fix provided earlier seems to install an earlier version of iotedgedev from our internal test, 0.81. We are coming out with a fix for this issue and a new version of the DevOps task soon

**Comment by stewartadam** [comment]
@cindydeng1998 several users are reporting the same issue with 18.x though - so I suspect the Python3 issue might be separate from this one.

**Comment by stewartadam** [comment]
Enabling System.Debug and looking at the failed IoT Edge task shows:
```
##[debug]/usr/bin/sudo arg: pip3 install iotedgedev~=3.0.0
##[debug]exec tool: /usr/bin/sudo
##[debug]exec tool: /usr/bin/sudo
##[debug]arguments:
##[debug]arguments:
##[debug]   pip3
##[debug]   pip3
##[debug]   install
##[debug]   install
##[debug]   iotedgedev~=3.0.0
##[debug]   iotedgedev~=3.0.0
##[debug]
##[debug]/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ERROR: Could not find a version that satisfies the requirement iotedgedev~=3.0.0 (from versions: 0.79.0, 0.80.0, 0.81.0, 0.82.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 2.0.0, 2.0.1, 2.0.2, 2.1.0)
ERROR: No matching distribution found for iotedgedev~=3.0.0
```

**Comment by oliverchristen** [comment]
Today it happens to me again as well.

**Comment by MaxThom** [comment]
Same for me, on my self hosted agent and on microsoft hosted agent.

**Comment by oliverchristen** [comment]
@MaxThom [This workaround](https://github.com/microsoft/azure-pipelines-tasks/issues/14167#issuecomment-808256842) works for me.

**Comment by YarekTyshchenko** [comment]
That workaround no longer works:
```
2021-04-16T09:33:13.4529550Z Collecting cryptography>=1.1.0 (from adal~=1.2->azure-cli-core<2.3.0->iotedgedev)
2021-04-16T09:33:13.8438440Z   Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
2021-04-16T09:33:14.0948862Z     Complete output from command python setup.py egg_info:
2021-04-16T09:33:14.0949799Z     
2021-04-16T09:33:14.0950384Z             =============================DEBUG ASSISTANCE==========================
2021-04-16T09:33:14.0951042Z             If you are seeing an error here please try the following to
2021-04-16T09:33:14.0951883Z             successfully install cryptography:
2021-04-16T09:33:14.0952367Z     
2021-04-16T09:33:14.0952928Z             Upgrade to the latest pip and try again. This will fix errors for most
2021-04-16T09:33:14.0954227Z             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2021-04-16T09:33:14.0954929Z             =============================DEBUG ASSISTANCE==========================
2021-04-16T09:33:14.0955526Z     
2021-04-16T09:33:14.0956023Z     Traceback (most recent call last):
2021-04-16T09:33:14.0956579Z       File "<string>", line 1, in <module>
2021-04-16T09:33:14.0957407Z       File "/tmp/pip-build-gUT1Mm/cryptography/setup.py", line 14, in <module>
2021-04-16T09:33:14.0958059Z         from setuptools_rust import RustExtension
2021-04-16T09:33:14.0958618Z     ImportError: No module named setuptools_rust
2021-04-16T09:33:14.0959769Z     
2021-04-16T09:33:14.0960307Z     ----------------------------------------
2021-04-16T09:33:14.1500940Z Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gUT1Mm/cryptography/
2021-04-16T09:33:14.4266925Z You are using pip version 8.1.1, however version 21.0.1 is available.
2021-04-16T09:33:14.4268229Z You should consider upgrading via the 'pip install --upgrade pip' command.
```

This is on:
```
Pool: Azure Pipelines
Image: Ubuntu 16.04
Agent: Hosted Agent
```

**Comment by stewartadam** [comment]
Tagging @cindydeng1998 again, per above there's a confirmed report with older versions of Ubuntu as well, so it's not a Python 3.8-specific issue. Given its intermittency, I think it [might be something on the build agent side causing this](https://github.com/microsoft/azure-pipelines-tasks/issues/14167#issuecomment-818268294).

**Comment by marianan** [comment]
Thanks @stewartadam , we saw this issue a couple times but could not reproduce consistently. We are investigating.

**Comment by marianan** [comment]
@YarekTyshchenko which version of the AzureIoTEdge task is showing the issue? We released yesterday 2.4.7 which should resolve the py3 issues.

**Comment by YarekTyshchenko** [comment]
@marianan It would have been the `2.4.5` i think, the task was specified with `@2` but I also tried actual `2.4.5`.
Upgrading to ubuntu-latest and performing install of iotedgedev via pip works.
I can try `2.4.7` on monday. Is there any docs on what versions of tasks are available?

**Comment by stewartadam** [comment]
From the comment history, it looks like 2.4.6 had it happen for more people but it's been observers with 2.4.5 as well. I'm not sure it's task-version-specific.

Given the pypi packages listed in the debug output were not matching the upstream page, my guess might be old cache on certain build agents.

**Comment by marianan** [comment]
@stewartadam and @YarekTyshchenko thanks for your replies. We updated the AzureIoTEdge task to use python 3 instead of python 2 and we recommend using the latest version of the AzureIoTEdge task - 2.4.7. Please continue updating this thread to let us know if 2.4.7 is still showing the original symptoms.

**Comment by Afikoman** [comment]
Hi,
I'm experiencing the same issue.
On the 13.4 (5 days ago) I successfully worked with the iotedgedev with the Azure DevOps Release, but today it's failing with the error "Unable to locate executable file: 'iotedgedev"

Both were running on Azure Pipelines - Hosted Agent - Ubuntu 20.04.2, agent version 2.184.2.
The difference was in 2 things:
* Ubuntu Version - The working was version 20210405.1, the filed was version 20210412.1.
* Azure  IotEdge version - the working was 2.4.5 (but installed version was 2.1.0) and the failed one is 2.4.7.


Working logs:
Agent:
2021-04-13T14:04:19.2013270Z ##[section]Starting: Initialize job
2021-04-13T14:04:19.2014825Z Agent name: 'Hosted Agent'
2021-04-13T14:04:19.2015302Z Agent machine name: 'fv-az408-330'
2021-04-13T14:04:19.2015582Z Current agent version: '2.184.2'
2021-04-13T14:04:19.2058303Z ##[group]Operating System
2021-04-13T14:04:19.2058680Z Ubuntu
2021-04-13T14:04:19.2058860Z 20.04.2
2021-04-13T14:04:19.2059080Z LTS
2021-04-13T14:04:19.2059259Z ##[endgroup]
2021-04-13T14:04:19.2059519Z ##[group]Virtual Environment
2021-04-13T14:04:19.2059764Z Environment: ubuntu-20.04
2021-04-13T14:04:19.2060042Z Version: 20210405.1
2021-04-13T14:04:19.2060658Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210405.1/images/linux/Ubuntu2004-README.md
2021-04-13T14:04:19.2061174Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210405.1
2021-04-13T14:04:19.2061621Z ##[endgroup]
2021-04-13T14:04:19.2062766Z Current image version: '20210405.1'
2021-04-13T14:04:19.2064900Z Agent running as: 'vsts'

Azure IotEdge:
2021-04-13T14:04:25.7692676Z ##[section]Starting: Azure IoT Edge - Generate deployment manifest
2021-04-13T14:04:25.7702392Z ==============================================================================
2021-04-13T14:04:25.7702819Z Task         : Azure IoT Edge
2021-04-13T14:04:25.7703138Z Description  : Build and deploy an Azure IoT Edge image
2021-04-13T14:04:25.7703451Z Version      : 2.4.5
2021-04-13T14:04:25.7703738Z Author       : Microsoft Corporation
2021-04-13T14:04:25.7704307Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
2021-04-13T14:04:25.7704775Z ==============================================================================
2021-04-13T14:04:26.0595449Z Start generating deployment manifest...
2021-04-13T14:04:26.0618581Z /home/vsts/work/r1/a/Edge-Modules-amd64/drop /home/vsts/work/r1/a
2021-04-13T14:05:18.4038974Z iotedgedev installed with version: version 2.1.0



Failed logs:
Agent:
2021-04-18T06:42:51.1062054Z ##[section]Starting: Initialize job
2021-04-18T06:42:51.1063804Z Agent name: 'Hosted Agent'
2021-04-18T06:42:51.1064295Z Agent machine name: 'fv-az68-795'
2021-04-18T06:42:51.1064568Z Current agent version: '2.184.2'
2021-04-18T06:42:51.1105974Z ##[group]Operating System
2021-04-18T06:42:51.1106270Z Ubuntu
2021-04-18T06:42:51.1106500Z 20.04.2
2021-04-18T06:42:51.1106667Z LTS
2021-04-18T06:42:51.1106895Z ##[endgroup]
2021-04-18T06:42:51.1107101Z ##[group]Virtual Environment
2021-04-18T06:42:51.1107397Z Environment: ubuntu-20.04
2021-04-18T06:42:51.1107618Z Version: 20210412.1
2021-04-18T06:42:51.1108053Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210412.1/images/linux/Ubuntu2004-README.md
2021-04-18T06:42:51.1108523Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210412.1
2021-04-18T06:42:51.1108918Z ##[endgroup]
2021-04-18T06:42:51.1110150Z Current image version: '20210412.1'
2021-04-18T06:42:51.1112385Z Agent running as: 'vsts'

Azure IotEdge:
2021-04-18T06:42:56.2933153Z Task         : Azure IoT Edge
2021-04-18T06:42:56.2933468Z Description  : Build and deploy an Azure IoT Edge image
2021-04-18T06:42:56.2933772Z Version      : 2.4.7
2021-04-18T06:42:56.2934038Z Author       : Microsoft Corporation
2021-04-18T06:42:56.2934620Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
2021-04-18T06:42:56.2935064Z ==============================================================================
2021-04-18T06:42:56.5850052Z Start generating deployment manifest...
2021-04-18T06:42:56.5867301Z /home/vsts/work/r1/a/Edge-Modules-amd64/drop /home/vsts/work/r1/a
2021-04-18T06:43:14.8990993Z ##[error]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by marianan** [comment]
Hello @Afikoman, Ubuntu 20.04 has Python 3.8 by default. IoTEdgeDev is only supported on python 3.6 and 3.7 at the moment. Could you try your pipeline on Ubuntu 18.04 instead and let us know if the issue still happens?

**Comment by YarekTyshchenko** [comment]
Tried version 2.4.7 of the task. It still didn't install iotedgedev. Attempting to install it via `pip install -U iotedgedev` brings back the same cryptography error as before.
 
```
Starting: Azure IoT Edge - Generate deployment manifest
==============================================================================
Task         : Azure IoT Edge
Description  : Build and deploy an Azure IoT Edge image
Version      : 2.4.7
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
==============================================================================
Start generating deployment manifest...
/home/vsts/work/1/s/services/src/XScan/Edge /home/vsts/work/1/s
##[error]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
On

```
Pool: Azure Pipelines
Image: Ubuntu 16.04
Agent: Hosted Agent
```

Technically we don't need to stay at 16.04 so upgrading to latest fixes it, but happy to help, if you want me to debug it further @marianan 

It seems to me that the task should ensure iotedgedev is installed on the agent itself, without having to do it manually?

**Comment by Vic152** [comment]
Hello All, We noticed the same issue:

![image](https://user-images.githubusercontent.com/6089679/115373953-44828b00-a1c4-11eb-9525-e235de6f7b02.png)
![image](https://user-images.githubusercontent.com/6089679/115374070-6419b380-a1c4-11eb-87d5-1af632b60b9d.png)

This is a critical issue with no known workaround. What is the ETA for the fix?

**Comment by Vic152** [comment]
@marianan I tried building with Ubuntu 18.04 with following configuration and it worked:

![image](https://user-images.githubusercontent.com/6089679/115385070-9bda2880-a1cf-11eb-9e44-6e5388aa5483.png)
![image](https://user-images.githubusercontent.com/6089679/115385944-aea12d00-a1d0-11eb-815b-fa3786f3713f.png)

It is not a critical issue for us anymore as the workaround exists. Thanks for your help I will keep you posted, should this issue arise.

**Comment by marianan** [comment]
@YarekTyshchenko and @Vic152 thanks for your follow ups. The issue on Ubuntu 20.04 seems to originate from the python version (3.8) but we have yet to narrow down the root cause. At this point Ubuntu 16.04 and Ubuntu 18.04 are expected to both work well with the Azure IoT Edge V2 task 2.4.7.

**Comment by oliverchristen** [comment]
@marianan @cindydeng1998 For an unknown reason [this](https://github.com/microsoft/azure-pipelines-tasks/issues/14167#issuecomment-808256842) workaround still works for me with vmImage 20.04.

**Comment by karakal** [comment]
> @marianan @cindydeng1998 For an unknown reason [this](https://github.com/microsoft/azure-pipelines-tasks/issues/14167#issuecomment-808256842) workaround still works for me with vmImage 20.04.

For me too. But it doesn't work on Ubuntu 18.04....

**Comment by stewartadam** [comment]
> At this point Ubuntu 16.04 and Ubuntu 18.04 are expected to both work well with the Azure IoT Edge V2 task 2.4.7.

@marianan I can confirm in addition to the folks above that it still fails on 2.4.7, same issue with PyPI package that's available upstream not being found on build agents:

```
##[debug]exec tool: /usr/bin/sudo
##[debug]arguments:
##[debug]arguments:
##[debug]   pip3
##[debug]   pip3
##[debug]   install
##[debug]   install
##[debug]   iotedgedev~=3.0.0
##[debug]   iotedgedev~=3.0.0
##[debug]
##[debug]ERROR: Could not find a version that satisfies the requirement iotedgedev~=3.0.0 (from versions: 0.79.0, 0.80.0, 0.81.0, 0.82.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 2.0.0, 2.0.1, 2.0.2, 2.1.0)
ERROR: No matching distribution found for iotedgedev~=3.0.0

##[debug]which 'iotedgedev'
##[debug]not found
##[debug]task result: Failed
##[error]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]Processed: ##vso[task.issue type=error;]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[debug]Agent.Version=2.185.1
```

**Comment by marianan** [comment]
@stewartadam you are correct; Ubuntu 20.04 defaults to python 3.8 which isn't yet supported by iotedgedev.

**Comment by stewartadam** [comment]
Since specific version of Python and/or dependencies are required, can this task be moved to using a Docker container?

**Comment by marianan** [comment]
Thanks @stewartadam, your suggestion has been added to our backlog. As there are no recent symptoms of this issue, I am closing it.

**Comment by timstokman** [comment]
@marianan I just got this issue again today, so it doesn't seem fixed:

```
2021-05-11T13:12:28.8129340Z ##[section]Starting: Azure IoT Edge - Generate deployment manifest
2021-05-11T13:12:28.8140814Z ==============================================================================
2021-05-11T13:12:28.8141199Z Task         : Azure IoT Edge
2021-05-11T13:12:28.8141510Z Description  : Build and deploy an Azure IoT Edge image
2021-05-11T13:12:28.8141810Z Version      : 2.4.7
2021-05-11T13:12:28.8142073Z Author       : Microsoft Corporation
2021-05-11T13:12:28.8142482Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/azure-iot-edge
2021-05-11T13:12:28.8142923Z ==============================================================================
2021-05-11T13:12:31.7402790Z Start generating deployment manifest...
2021-05-11T13:12:31.7418328Z /home/vsts/work/1/s/code/edgesolution /home/vsts/work/1/s
2021-05-11T13:12:53.4315960Z ##[error]Error: Unable to locate executable file: 'iotedgedev'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
2021-05-11T13:13:54.4662950Z ##[section]Finishing: Azure IoT Edge - Generate deployment manifest
```

**Comment by timstokman** [comment]
@stewartadam It's set to "ubuntu-latest"

**Comment by oliverchristen** [comment]
@marianan since this issue still persists on the default agent, I would suggest to reopen this issue and only close it when the fix is released. What do you think?

**Comment by marianan** [comment]
Hi @oliverchristen , I suggest filing a new issue to track the work for Ubuntu 20.04 support and linking it here. The root cause for this issue has been resolved so I feel that it will be more clear if we start a new thread. Also, supporting Ubuntu 20.04 is already in our backlog but it doesn't hurt to have a tracking thread on GitHub for everyone's awareness. Does this sound like a plan?

**Comment by oliverchristen** [comment]
Thanks for the suggestion @marianan. But I don't see the necessity to start a new thread. The initial issue still persists since it's probably related to Ubuntu 20.04. It would also be nice to link the backlog item for the Ubuntu 20.04 support here. It's not yet, isn't it?
For me it only works with the workaround
`pip install -U iotedgedev`
which I don't understand why this works - but it does. I would rather remove this workaround.

**Comment by karakal** [comment]
I have the same problem and the same workaround "works".
It also doesn't work anymore at all with 18.0.4.

I would also prefer to keep this bug open and not start another thread
anywhere...

Oliver Christen ***@***.***> schrieb am Mi., 12. Mai 2021,
07:47:

**Comment by EmileLombard** [comment]
Hi everyone, if anyone is still having this issue, this is how I solved it: 

Enable debugging logs (set build variable system.debug = true)

From the logs I found these lines: 
##[debug]which 'iotedgedev'
##[debug]not found
##[debug]IOTEDGEDEV_VERSION=undefined
##[debug]The specified iotedgedev version is: 3.0.0

and: 
##[debug]ERROR: Could not find a version that satisfies the requirement iotedgedev~=3.0.0 (from versions: 0.79.0, 0.80.0, 0.81.0, 0.82.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 2.0.0, 2.0.1, 2.0.2, **2.1.0**)

So I just set a build variable to the latest version specified in the logs, in this case: IOTEDGEDEV_VERSION=**2.1.0**

I then just ran the build pipline again and it solved the issue. 

I was running on
pool:
  vmImage: 'ubuntu-latest'

**Comment by NielsPointFWD** [comment]
Dear @oliverchristen ,

Thank you for providing a workaround!
This issue is still present to this day. (Ubuntu-latest)
