### ISSUE TITLE
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

### ISSUE THREAD

**Issue by chugh97** [microsoft/azure-pipelines-tasks#15508]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: Quite a number of tasks are giving this warning  (task: CopyFiles@2)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
   
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
    DWP-SSWAP, project: BCAS, BenefitCapAtlasMI, #20211115.1

- Agent - Hosted 
    
    - If using Hosted agent, provide agent queue name: windows-2019 (Azure pipelines agent)

## Issue Description

##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
This task is giving the warning message.Also a lot of other 3rd party tasks are showing this message.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by tatyana-kostromskaya** [comment]
Hi @chugh97, the target date for Node 6->Node 10 migration is March 31st 2022 at the moment. Until this date you may see these warnings for different tasks. 
It is not a bug, so if you are not a developer of these tasks you can just ignore it.

**Comment by pirminrehm** [comment]
Even if this is a official migration hint, I expect it not to apply to official Azure Pipelines Tasks!

**Comment by johnnyreilly** [comment]
Also seeing this for `UniversalPackages@0`

```
Starting: UniversalPackages
==============================================================================
Task         : Universal packages
Description  : Download or publish Universal Packages
Version      : 0.190.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

```

**Comment by AdamYoblick** [comment]
I agree with some earlier sentiment - it's a little disruptive that built-in AzDO tasks would cause build warnings with no change on our end.

For example, we're also seeing this for the `CopyFiles@2` task in our CI build at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5448082&view=results.

```
Starting: Copy source to staging/src
==============================================================================
Task         : Copy files
Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
Version      : 2.190.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
==============================================================================
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
```

**Comment by tatyana-kostromskaya** [comment]
This warning shows for all tasks which use Node6 handler. It is important to notify all owners of tasks about this deprecation including owners of built-in AzDO tasks.
As soon as tasks are migrated to new handler, these warnings will disappear.


Close this ticket because it is not a bug.

**Comment by krokofant** [comment]
> 
> 
> I agree with some earlier sentiment - it's a little disruptive that built-in AzDO tasks would cause build warnings with no change on our end.
> 
> For example, we're also seeing this for the `CopyFiles@2` task in our CI build at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5448082&view=results.
> 
> ```
> Starting: Copy source to staging/src
> ==============================================================================
> Task         : Copy files
> Description  : Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
> Version      : 2.190.1
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/copy-files
> ==============================================================================
> ##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
> ```

We have 69 warnings in our pipeline and 66 out of those are this warning 😅

**Comment by alexMagicBeans** [comment]
Is there any date to fix this warnings? 

Thanks

**Comment by StingyJack** [comment]
> It is important to notify all owners of tasks about this deprecation including owners of built-in AzDO tasks.

@tatyana-kostromskaya - we dont expect that out of the box, Microsoft created tasks will be creating warnings in our pipelines. 

This issue represents us "feeling free to reach out to the owners of this task to proceed on migration", but instead of using it for that, you have closed it. This is easily construed as you are _not_ going to do the needful and update the tasks as expected (or even to at least quell the warning). Even if you have the intention to fix it, telling us to go log an issue for azure pipelines tasks in a customer feedback site (feedback is not bug reporting) makes no sense at all.

**Comment by TheRealAyCe** [comment]
Having a Microsoft system complain to the user about another Microsoft system feels surreal.

**Comment by tatyana-kostromskaya** [comment]
@StingyJack, sorry for that, it was rude to close it this way. We are not owning all built-in tasks in Azure DevOps.
We migrated all tasks that are owned by us to Node 10 , except CopyFiles. For CopyFiles we have separate ticket: https://github.com/microsoft/azure-pipelines-tasks/issues/15516 that is expected to be fixed in the nearest future.

I just closed this ticket because I shared all info that I had in that moment. We can't just hide this warnings for our tasks, but of course we will do our best to fix the ones that owned by us.

**Comment by taspeotis** [comment]
This should be turned into a feature request to send all warnings from Azure DevOps into a recycle bin. The last time this happened it was a warning that `ubuntu-latest` was being upgraded to the latest version of Ubuntu, which is exactly the point of `ubuntu-latest`.

**Comment by jozefizso** [comment]
> Hi @chugh97, the target date for Node 6->Node 10 migration is March 31st 2022 at the moment. Until this date you may see these warnings for different tasks. It is not a bug, so if you are not a developer of these tasks you can just ignore it.

This is unacceptable. We cannot filter out extreme amount of system generated warning which we have no control of.

**Comment by TheRealAyCe** [comment]
> > Hi @chugh97, the target date for Node 6->Node 10 migration is March 31st 2022 at the moment. Until this date you may see these warnings for different tasks. It is not a bug, so if you are not a developer of these tasks you can just ignore it.
> 
> This is unacceptable. We cannot filter out extreme amount of system generated warnings which we have no control of.

Exactly, if the problem is that different departments are responsible for maintaining the tasks and the environment, they should directly communicate with each other and solve this problem, and not tell the customers who have no control over it. We don't care that you have yet to update "NuGetToolInstaller", "Restore Solution" or "Copy Files". Don't tell us. Tell the Microsoft department. We have absolutely no use for your pseudo-warnings.

**Comment by StingyJack** [comment]
> We can't just hide this warnings for our tasks

@tatyana-kostromskaya  - what do you mean you cant?  Of course you can.

**Comment by johnnyreilly** [comment]
Hello everyone. This is a frustrating issue. It bugs me too. That said, it will get fixed, and one day this will be just a memory. Whilst we're waiting, let's not let frustration make us unkind. We'll get there; it's going to be fine. For the people who do maintain these tasks, thank you very much ❤️🌻

**Comment by AdamCoulterOz** [comment]
@tatyana-kostromskaya I agree its not a "bug" per-say... but the warnings are to users, which caused this to be opened. Users have zero control over fixing this warning, so why tell them? I can understand generally notifying users if a third party task they are using might break soon (e.g. it might have been abandoned / there is no one around to fix it, and the user can choose to move off it before it stops working), but not for built-in first party Microsoft tasks.

**Comment by miqm** [comment]
The warning is also on [Pip Authenticate](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/package/pip-authenticate) task.

The warning says `If you are the user - feel free to reach out to the owners of this task to proceed on migration.` - So we do :)

**Comment by CZEMacLeod** [comment]
For reference - The two tasks I was having issues with were `NuGetToolInstaller@1` (and NuGetToolInstaller@0 although I updated that one which is how I found out it was 'unfixable`) and `NuGetCommand@2`

**Comment by tatyana-kostromskaya** [comment]
Hi all, it was decided to turn off these warnings for in-built Azure DevOps tasks. This change will be roll out soon.

**Comment by Miles-Davies-HORIBA** [comment]
@tatyana-kostromskaya I applaud the intent behind this warning. It will certainly get some traction in the extension authors.

The challenge I face is our pipelines suddenly began failing because we have quality limits set for the number of build warnings. We rely on extensions to fill the functionality holes  from official Microsoft tasks and some specialist tasks we need for our build.

I am reluctant to ease the quality thresholds for what is not related to our quality but to the pipeline implementation quality.

I agree with others that this warning should be 'feature flagged' with default ON but possible to disable at the organization level. This way the objective to raise awareness is achieved but we can make an informed decision about how to manage this at the appropriate level which is the individual organization and not Microsoft I think.

I value the decision to turn off the warnings for in-built devops tasks but this should be a possibility for all tasks not just your own. We can manage this issue with less impact to our pipeline once made aware.

**Comment by anatolybolshakov** [comment]
Hi everyone, just as a quick update - due to issues with increased amount of warnings we are working on disabling of Node 6 warning message for in-the-box tasks and leave warnings only for a custom tasks. We are planning to roll out relevant agent update in the next two days - will keep you posted in the https://github.com/microsoft/azure-pipelines-tasks/issues/15493.

For Node 6 - we are not going to deprecate previous execution handler until all the relevant supported in-the-box tasks will be migrated to the new Node execution handler, please don't worry about it. The main goal of this warning message is to notify custom extensions owners about upcoming agent update - I agreed that this is a fair point not to display them for the pipeline owners.

**Comment by ThisDevOpsNerd** [comment]
> Hi @chugh97, the target date for Node 6->Node 10 migration is March 31st 2022 at the moment. Until this date you may see these warnings for different tasks. It is not a bug, so if you are not a developer of these tasks you can just ignore it.

This is silly!  My developers are getting hundreds of warnings in their pipelines and you want them to just ignore it? We have build failures configured on the number of warnings not increasing. Also if there is literally nothing we can do about this why give us the warnings ?

**Comment by taspeotis** [comment]
> For the people who do maintain these tasks, thank you very much

[They don't maintain the tasks though, the caching task has been broken since 2019](https://github.com/microsoft/azure-pipelines-tasks/issues/11864).

**Comment by tatyana-kostromskaya** [comment]
Changes to disable warnings were released with agent 2.195.1. 

I am closing this ticket as main problem was fixed. Feel free to reopen it in case of further questions related to this issue.

**Comment by StingyJack** [comment]
@tatyana-kostromskaya still getting it for this Microsoft authored task...

https://github.com/MicrosoftPremier/VstsExtensions/blob/master/PostBuildCleanup/en-US/overview.md

**Comment by davesmits** [comment]
What is the current plan about this? we use a 3th party task for DocFX which had this problem in the past; we are considering to fork this build task to overcome the problem since the owner doesn't respond  anymore
