### ISSUE TITLE
VSTest@2: IsValidServiceResponse: Received None command..Service Workflow is not active 

### ISSUE THREAD

**Issue by nick-dempsey** [microsoft/azure-pipelines-tasks#16369]
**Question, Bug, or Feature?**  
Bug

**Task Name**:
Visual Studio Test @ 2

## Environment
Azure Pipelines

- Agent
Self hosted 
Version: 2.204.0
running behind proxy
Windows 10 x64
running as user not service

## Issue Description
I have a test framework built in .net 5.0 using nunit and specflow for a mix of ui & api tests

Running automated test cases from test plans in azure devops no longer works, hangs with message **IsValidServiceResponse: Received None command..Service Workflow is not active**. I created a POC for this in march and it ran without issue, the pipelines have not changed since then.
When I build the framework and run Visual Studio Test - Select Tests using = Test Assemblies then tests run as expected.
I have tried removing and creating a new agent with a fresh PAT, as well as re-associating the test cases. My colleague has a similar setup with a different framework running on a different agent and is getting the same behaviour.
 
There are no exceptions or errors with System.Debug = true in the pipeline logs, or in the agent logs

1. Associate automated test to Test case in Azure DevOps test plan
2. Select test in test plan
3. Run with options
4. Automated test using release stage
5. Select Release pipeline and stage (stage yaml below)
6. Run

steps:
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'
  inputs:
    versionSelector: specificVersion
    testPlatformVersion: 17.1.0
- task: VSTest@2
  displayName: 'Test run for Test plans'
  inputs:
    testSelector: testRun
    vsTestVersion: toolsInstaller
    runInParallel: false
    runTestsInIsolation: false
    codeCoverageEnabled: false

### Task logs
2022-05-26T10:03:38.5717572Z Test run with Id 11480 associated
2022-05-26T10:03:38.7025117Z ##[debug]TestHostStart.Run : Waiting to get a start command or stop/cancel command
2022-05-26T10:03:47.7329569Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:04:07.7761696Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:04:47.8180216Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:05:47.8320276Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:06:47.8539129Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:07:47.8901589Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:08:47.9204292Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:09:47.9486469Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:10:47.9774827Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:11:48.0050134Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:12:48.0580708Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:13:48.0904625Z IsValidServiceResponse: Received None command..Service Workflow is not active
2022-05-26T10:13:48.0932687Z TestExecutionHost.ProcessCommand. Stop Command handled
2022-05-26T10:13:48.0934131Z ##[debug]TestHostStart.Run : TestHost stop/cancel invoked
2022-05-26T10:13:48.0935044Z ##[debug]ExecutionStateResolver.SetNextPhase : Current Phase: TestHostStart
2022-05-26T10:13:48.0935884Z ##[debug]ExecutionStateResolver.SetNextPhase : Next Phase: TestHostEnd
2022-05-26T10:13:48.0936656Z ##[debug]TestExecutionHost.Execute: Current Phase TestHostEnd
2022-05-26T10:13:48.0937774Z ##[debug]VstestAdapter.ExecuteAsync : Starting Execution
2022-05-26T10:13:48.0951753Z ##[debug]ProceedAfterAbortedTestCase : False
2022-05-26T10:13:48.0994512Z ##[debug]SliceDetailsStore.NormalizeSettings : No Slice details or run information
2022-05-26T10:13:48.0995375Z ##[debug]VstestAdapter.ExecuteAsync : Returning
2022-05-26T10:13:48.1008207Z ##[debug]TestHostEnd.Run : CancellatationRequested: True : RunCreated : True : RunCompleted : False
2022-05-26T10:13:48.1919421Z ##[debug]TestHostEnd.Run: Run not completed. Waiting for the stop event
2022-05-26T10:13:48.1920348Z ##[debug]TestHostStop.Run : Logging the test run details
2022-05-26T10:13:48.2303548Z Test run '11480' is in 'InProgress' state with 'Total Tests' : 1 and 'Passed Tests' : 0.
2022-05-26T10:13:48.2305757Z ##[error]Test run 11480 did not complete yet.

Can provide full logs privately

**Comment by nick-dempsey** [comment]
Resolved, believe this was caused by a failure in the BeforeScenario method due to a network issue. building and running in the same pipeline uses cached properties so no issue.

**Comment by wilnicm1** [comment]
@nick-dempsey  I"m having the same issue. I've updated and changed my release on multiple times and still seeing the same error.  I tried different agents and still getting same error.  You said something about the beforescenario method or due to network issue/ cached properties. Can you go into a little explanation.  I've been dealing with the problem and trying to find a solution on on day 3 and i'm not where close to figuring out what its complaining about . 

here is a link where i'm asking this question on stack [vstest-task-failing-after-project-upgraded-to-net5-0](https://stackoverflow.com/questions/73561762/vstest-task-failing-after-project-upgraded-to-net5-0)
