### ISSUE TITLE
[BUG]: AzureFunctionApp Task may result in the WEBSITE_RUN_FROM_PACKAGE AppSetting missing on SCM\Kudu and Validation failures

### ISSUE THREAD

**Issue by FinVamp1** [microsoft/azure-pipelines-tasks#19909]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFunctionApp

### Task version

2.239.1

### Issue Description

1. Deploy a Function App using AzureFunctionApp  v2 
2. The Deployment succeeds but Validation Fails.

Validating deployment package for functions app before Zip Deploy
##[warning]"ZipDeploy Validation WARNING: It is recommended to set app setting WEBSITE_RUN_FROM_PACKAGE = 1 unless you are targeting one of the following scenarios: 1. Using portal editing. 2. Running post deployment scripts. 3. Need write permission in wwwroot. 4. Using custom handler with special requirements. NOTE: If you decide to update app setting WEBSITE_RUN_FROM_PACKAGE = 1, you will have to re-deploy your code. "
Package deployment using ZIP Deploy initiated.

3. This is because the App Setting is set but Kudu\SCM isn't aware of it yet.
it looks like the Web App Task knew that Kudu could be out of sync and had some code to wait.

https://github.com/microsoft/azure-pipelines-tasks/blob/259e0d322f201e39e8c78c6e1074a296f702b505/Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts#L171

  tl.debug('retrieving values from Kudu service to check if new values are updated');

        while(noOftimesToIterate > 0) {

            var kuduServiceAppSettings = await kuduService.getAppSettings();

            var propertiesChanged: boolean = true;

            for(var property in addProperties) {

                if(kuduServiceAppSettings[property] != addProperties[property]) {

                    tl.debug('New properties are not updated in Kudu service :(');

                    propertiesChanged = false;

                    break;

                }

            }

This work item is to add this code to the Functions task.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows\Ubuntu

### Relevant log output

```shell
Validating deployment package for functions app before Zip Deploy
##[warning]"ZipDeploy Validation WARNING: It is recommended to set app setting WEBSITE_RUN_FROM_PACKAGE = 1 unless you are targeting one of the following scenarios: 1. Using portal editing. 2. Running post deployment scripts. 3. Need write permission in wwwroot. 4. Using custom handler with special requirements. NOTE: If you decide to update app setting WEBSITE_RUN_FROM_PACKAGE = 1, you will have to re-deploy your code. "
Package deployment using ZIP Deploy initiated.
```

### Full task logs with system.debug enabled

N/A

### Repro steps

```yml
- task: AzureFunctionApp@2
            displayName: 'Azure Functions App Deploy: <myAppName>'
            inputs:
              connectedServiceNameARM: '<mySub>'
              appType: '<apptype>'
              appName: '<myappname>'
              deployToSlotOrASE: true
              resourceGroupName: 'MyRG'
              slotName: 'staging'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              appSettings: '-FinTestAppSetting "Picard"'
              deploymentMethod: 'runFromPackage'
```

**Comment by FinVamp1** [comment]
This should be resolved in https://github.com/microsoft/azure-pipelines-tasks/pull/20191

**Comment by komjera** [comment]
@FinVamp1 Bumping this issue too. As people have pointed out in #18970 this was not resolved in #20191 (or maybe re-introduced in later release).

**Comment by FinVamp1** [comment]
@komjera I was not able to reproduce the issue myself so I implemented additional tracing and the update logic from AzureRMWebAppDeployment@4 which should have helped. I need to see new deployment logs with this error and debug enabled so I can see what is missing. People can either share them here or contact me offline or open a support case.

Thanks,

Finbar

**Comment by komjera** [comment]
@FinVamp1 It's hard to tell which id's and what information in debug logs are safe to share. Please let me know if you need any more information or if i have redacted any information you need. 

I would probably be able to share more logs "offline", how would I do that?

Selected parts from debug logs earlier today below
```
2024-10-21T07:58:02.7231356Z ==============================================================================
2024-10-21T07:58:02.7231509Z Task         : Azure Functions Deploy
2024-10-21T07:58:02.7231591Z Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
2024-10-21T07:58:02.7231724Z Version      : 2.247.1
2024-10-21T07:58:02.7231984Z Author       : Microsoft Corporation
2024-10-21T07:58:02.7232066Z Help         : https://aka.ms/azurefunctiontroubleshooting
2024-10-21T07:58:02.7232163Z ==============================================================================
...
2024-10-21T07:58:16.0826529Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"1"}
2024-10-21T07:58:16.0827067Z ##[debug]Value of WEBSITE_RUN_FROM_PACKAGE has been changed to 1
2024-10-21T07:58:16.0827622Z ##[debug]MSAL - getMSALToken called. force=undefined
2024-10-21T07:58:16.0828216Z ##[debug][Mon, 21 Oct 2024 07:58:16 GMT] : [] : @azure/msal-node@2.11.1 : Info - acquireTokenByClientCredential called
2024-10-21T07:58:16.0829051Z ##[debug][Mon, 21 Oct 2024 07:58:16 GMT] : [e759bfd0-e9c7-41ce-9147-07077df902a5] : @azure/msal-node@2.11.1 : Info - Building oauth client configuration with the following authority: https://login.microsoftonline.com/***/oauth2/v2.0/token.
2024-10-21T07:58:16.0829811Z ##[debug]MSAL - retrieved token - isFromCache?: true
2024-10-21T07:58:16.0830323Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T07:58:16.0830976Z ##[debug][PUT]https://management.azure.com/subscriptions/#REDACTED#/resourceGroups/#REDACTED#/providers/Microsoft.Web/sites/#REDACTED#/config/appsettings?api-version=2016-08-01
2024-10-21T07:58:16.8859135Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 2090.00 MB out of 7167.00 MB, CPU: Usage 9.00%
2024-10-21T07:58:21.8888410Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 2083.00 MB out of 7167.00 MB, CPU: Usage 11.00%
2024-10-21T07:58:26.8995989Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 2079.00 MB out of 7167.00 MB, CPU: Usage 7.00%
2024-10-21T07:58:31.9094695Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 2075.00 MB out of 7167.00 MB, CPU: Usage 7.00%
2024-10-21T07:58:36.9106328Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 2071.00 MB out of 7167.00 MB, CPU: Usage 7.00%
2024-10-21T07:58:41.9278868Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 2066.00 MB out of 7167.00 MB, CPU: Usage 19.00%
2024-10-21T07:58:46.9470457Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 2062.00 MB out of 7167.00 MB, CPU: Usage 5.00%
2024-10-21T07:58:47.2476750Z ##[debug]Correlation ID from ARM api call response : #REDACTED#
2024-10-21T07:58:47.2477651Z Updated App Service Application settings and Kudu Application settings.
...
2024-10-21T07:59:55.2079391Z Validating deployment package for functions app before Zip Deploy
2024-10-21T07:59:55.2197332Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T07:59:55.2198870Z ##[debug][POST]https://$#REDACTED#:***@#REDACTED#.scm.azurewebsites.net/api/zipdeploy/validate?&
2024-10-21T07:59:55.9888134Z ##[debug]loaded affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T07:59:56.9894317Z ##[debug]Validation passed response: {"statusCode":200,"statusMessage":"OK","headers":{"content-length":"425","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 07:59:55 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","pragma":"no-cache","set-cookie":["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"],"x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":{"result":"ZipDeploy Validation WARNING: It is recommended to set app setting WEBSITE_RUN_FROM_PACKAGE = 1 unless you are targeting one of the following scenarios: 1. Using portal editing. 2. Running post deployment scripts. 3. Need write permission in wwwroot. 4. Using custom handler with special requirements. NOTE: If you decide to update app setting WEBSITE_RUN_FROM_PACKAGE = 1, you will have to re-deploy your code. "}}
2024-10-21T07:59:56.9898144Z ##[warning]"ZipDeploy Validation WARNING: It is recommended to set app setting WEBSITE_RUN_FROM_PACKAGE = 1 unless you are targeting one of the following scenarios: 1. Using portal editing. 2. Running post deployment scripts. 3. Need write permission in wwwroot. 4. Using custom handler with special requirements. NOTE: If you decide to update app setting WEBSITE_RUN_FROM_PACKAGE = 1, you will have to re-deploy your code. "
2024-10-21T07:59:56.9900706Z ##[debug]Processed: ##vso[task.issue type=warning;source=TaskInternal;correlationId=ab004575-fdf4-47d7-b370-2b0928b24c19;]"ZipDeploy Validation WARNING: It is recommended to set app setting WEBSITE_RUN_FROM_PACKAGE = 1 unless you are targeting one of the following scenarios: 1. Using portal editing. 2. Running post deployment scripts. 3. Need write permission in wwwroot. 4. Using custom handler with special requirements. NOTE: If you decide to update app setting WEBSITE_RUN_FROM_PACKAGE = 1, you will have to re-deploy your code. "
2024-10-21T07:59:56.9901502Z Package deployment using ZIP Deploy initiated.
2024-10-21T07:59:56.9901873Z ##[debug]Azure_App_Service_Deploy_PackageArtifactAlias=
2024-10-21T07:59:56.9902231Z ##[debug]release.releaseId=undefined
2024-10-21T07:59:56.9902623Z ##[debug]release.releaseName=undefined
2024-10-21T07:59:56.9902996Z ##[debug]system.TeamFoundationCollectionUri=https://#REDACTED#.visualstudio.com/
2024-10-21T07:59:56.9903753Z ##[debug]system.teamProjectId=#REDACTED#
2024-10-21T07:59:56.9904140Z ##[debug]build.requestedfor=#REDACTED#
2024-10-21T07:59:56.9904656Z ##[debug]build.buildId=50983
2024-10-21T07:59:56.9904979Z ##[debug]build.buildNumber=50983
2024-10-21T07:59:56.9905351Z ##[debug]build.sourceVersion=#REDACTED#
2024-10-21T07:59:56.9905736Z ##[debug]build.repository.name=#REDACTED#
2024-10-21T07:59:56.9906105Z ##[debug]build.repository.provider=TfsGit
2024-10-21T07:59:56.9906514Z ##[debug]build.repository.uri=https://#REDACTED#.visualstudio.com/#REDACTED#/_git/#REDACTED#
2024-10-21T07:59:56.9906918Z ##[debug]build.sourcebranchname=26985-dotnet8
2024-10-21T07:59:56.9907263Z ##[debug]build.buildId=50983
2024-10-21T07:59:56.9907988Z ##[debug]release.releaseId=undefined
2024-10-21T07:59:56.9908341Z ##[debug]system.teamproject=#REDACTED#
2024-10-21T07:59:56.9908943Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T07:59:56.9909541Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T07:59:56.9911655Z ##[debug][POST]https://$#REDACTED#:***@#REDACTED#.scm.azurewebsites.net/api/zipdeploy?isAsync=true&deployer=VSTS_FUNCTIONS_V2&message=%7B%22type%22%3A%22deployment%22%2C%22commitId%22%3A%22#REDACTED#%22%2C%22buildId%22%3A%2250983%22%2C%22buildNumber%22%3A%2250983%22%2C%22repoProvider%22%3A%22TfsGit%22%2C%22repoName%22%3A%22#REDACTED#%22%2C%22collectionUrl%22%3A%22https%3A%2F%2F#REDACTED#.visualstudio.com%2F%22%2C%22teamProject%22%3A%22#REDACTED#%22%2C%22buildProjectUrl%22%3A%22https%3A%2F%2F#REDACTED#.visualstudio.com%2F#REDACTED#%22%2C%22repositoryUrl%22%3A%22https%3A%2F%2F#REDACTED#.visualstudio.com%2F#REDACTED#%2F_git%2F#REDACTED#%22%2C%22branch%22%3A%2226985-dotnet8%22%2C%22teamProjectName%22%3A%22#REDACTED#%22%2C%22slotName%22%3A%22production%22%7D
2024-10-21T07:59:57.4906473Z ##[debug]ZIP Deploy response: {"statusCode":202,"statusMessage":"Accepted","headers":{"content-length":"0","date":"Mon, 21 Oct 2024 07:59:57 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","location":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest?deployer=VSTS_FUNCTIONS_V2&time=2024-10-21_07-59-57Z","pragma":"no-cache","retry-after":"30","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"}}
2024-10-21T07:59:57.4908193Z ##[debug]Polling for ZIP Deploy URL: https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest?deployer=VSTS_FUNCTIONS_V2&time=2024-10-21_07-59-57Z
2024-10-21T07:59:57.4909074Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T07:59:57.4909950Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T07:59:57.4910581Z ##[debug][GET]https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest?deployer=VSTS_FUNCTIONS_V2&time=2024-10-21_07-59-57Z
2024-10-21T07:59:58.5281122Z ##[debug]POLL URL RESULT: {"statusCode":202,"statusMessage":"Accepted","headers":{"content-length":"384","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 07:59:58 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","location":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest?deployer=VSTS_FUNCTIONS_V2&time=2024-10-21_07-59-57Z","pragma":"no-cache","retry-after":"30","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":{"id":null,"status":0,"status_text":null,"author_email":null,"author":null,"deployer":null,"message":null,"progress":null,"received_time":"0001-01-01T00:00:00","start_time":"0001-01-01T00:00:00","end_time":null,"last_success_end_time":null,"complete":false,"active":false,"is_temp":false,"is_readonly":false,"url":null,"log_url":null,"site_name":null,"provisioningState":"InProgress"}}
2024-10-21T07:59:58.5283271Z ##[debug]Deployment status: 0 'null'. retry after 5 seconds
2024-10-21T07:59:59.4924618Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 1812.00 MB out of 7167.00 MB, CPU: Usage 6.00%
2024-10-21T08:00:03.5429766Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T08:00:03.5431093Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T08:00:03.5431981Z ##[debug][GET]https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest?deployer=VSTS_FUNCTIONS_V2&time=2024-10-21_07-59-57Z
2024-10-21T08:00:03.8684216Z ##[debug]POLL URL RESULT: {"statusCode":202,"statusMessage":"Accepted","headers":{"content-length":"384","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 08:00:03 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","location":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest?deployer=VSTS_FUNCTIONS_V2&time=2024-10-21_07-59-57Z","pragma":"no-cache","retry-after":"30","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":{"id":null,"status":0,"status_text":null,"author_email":null,"author":null,"deployer":null,"message":null,"progress":null,"received_time":"0001-01-01T00:00:00","start_time":"0001-01-01T00:00:00","end_time":null,"last_success_end_time":null,"complete":false,"active":false,"is_temp":false,"is_readonly":false,"url":null,"log_url":null,"site_name":null,"provisioningState":"InProgress"}}
2024-10-21T08:00:03.8685873Z ##[debug]Deployment status: 0 'null'. retry after 5 seconds
2024-10-21T08:00:04.4955107Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 1809.00 MB out of 7167.00 MB, CPU: Usage 12.00%
2024-10-21T08:00:08.8743723Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T08:00:08.8745287Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T08:00:08.8746246Z ##[debug][GET]https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest?deployer=VSTS_FUNCTIONS_V2&time=2024-10-21_07-59-57Z
2024-10-21T08:00:09.3404266Z ##[debug]POLL URL RESULT: {"statusCode":200,"statusMessage":"OK","headers":{"content-length":"1266","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 08:00:09 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","pragma":"no-cache","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":{"id":"#REDACTED#","status":4,"status_text":"","author_email":"N/A","author":"N/A","deployer":"VSTS_FUNCTIONS_V2","message":"{\"type\":\"deployment\",\"commitId\":\"#REDACTED#\",\"buildId\":\"50983\",\"buildNumber\":\"50983\",\"repoProvider\":\"TfsGit\",\"repoName\":\"#REDACTED#\",\"collectionUrl\":\"https://#REDACTED#.visualstudio.com/\",\"teamProject\":\"#REDACTED#\",\"buildProjectUrl\":\"https://#REDACTED#.visualstudio.com/#REDACTED#\",\"repositoryUrl\":\"https://#REDACTED#.visualstudio.com/#REDACTED#/_git/#REDACTED#\",\"branch\":\"26985-dotnet8\",\"teamProjectName\":\"#REDACTED#\",\"slotName\":\"production\"}","progress":"","received_time":"2024-10-21T07:59:58.3297236Z","start_time":"2024-10-21T07:59:58.8922284Z","end_time":"2024-10-21T08:00:03.4660932Z","last_success_end_time":"2024-10-21T08:00:03.4660932Z","complete":true,"active":true,"is_temp":false,"is_readonly":true,"url":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest","log_url":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/latest/log","site_name":"#REDACTED#","provisioningState":"Succeeded"}}
2024-10-21T08:00:09.3408585Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T08:00:09.3410415Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T08:00:09.3411888Z ##[debug][GET]https://$#REDACTED#:***@#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#
2024-10-21T08:00:09.4990534Z ##[debug]Agent environment resources - Disk: D:\ Available 12313.80 MB out of 14334.00 MB, Memory: Used 1807.00 MB out of 7167.00 MB, CPU: Usage 6.00%
2024-10-21T08:00:09.6302218Z ##[debug]getDeploymentDetails. Data: {"statusCode":200,"statusMessage":"OK","headers":{"content-length":"1318","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 08:00:09 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","pragma":"no-cache","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":{"id":"#REDACTED#","status":4,"status_text":"","author_email":"N/A","author":"N/A","deployer":"VSTS_FUNCTIONS_V2","message":"{\"type\":\"deployment\",\"commitId\":\"#REDACTED#\",\"buildId\":\"50983\",\"buildNumber\":\"50983\",\"repoProvider\":\"TfsGit\",\"repoName\":\"#REDACTED#\",\"collectionUrl\":\"https://#REDACTED#.visualstudio.com/\",\"teamProject\":\"#REDACTED#\",\"buildProjectUrl\":\"https://#REDACTED#.visualstudio.com/#REDACTED#\",\"repositoryUrl\":\"https://#REDACTED#.visualstudio.com/#REDACTED#/_git/#REDACTED#\",\"branch\":\"26985-dotnet8\",\"teamProjectName\":\"#REDACTED#\",\"slotName\":\"production\"}","progress":"","received_time":"2024-10-21T07:59:58.3297236Z","start_time":"2024-10-21T07:59:58.8922284Z","end_time":"2024-10-21T08:00:03.4660932Z","last_success_end_time":"2024-10-21T08:00:03.4660932Z","complete":true,"active":true,"is_temp":false,"is_readonly":true,"url":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#","log_url":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#/log","site_name":"#REDACTED#","provisioningState":"Succeeded"}}
2024-10-21T08:00:09.6305851Z ##[debug]system.debug=true
2024-10-21T08:00:09.6306929Z ##[debug]logs from kudu deploy: https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#/log
2024-10-21T08:00:09.6307911Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T08:00:09.6308909Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T08:00:09.6309474Z ##[debug][GET]https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#/log
2024-10-21T08:00:10.0200264Z ##[debug]getDeploymentLogs. Data: {"statusCode":200,"statusMessage":"OK","headers":{"content-length":"1412","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 08:00:09 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","pragma":"no-cache","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":[{"log_time":"2024-10-21T07:59:58.5797559Z","id":"#REDACTED#","message":"Updating submodules.","type":0,"details_url":null},{"log_time":"2024-10-21T07:59:58.7984902Z","id":"#REDACTED#","message":"Preparing deployment for commit id '448cb4070d'.","type":0,"details_url":null},{"log_time":"2024-10-21T07:59:59.4431619Z","id":"#REDACTED#","message":"Generating deployment script.","type":0,"details_url":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#/log/1677f0e4-7bee-478e-8ad2-a758c2b11192"},{"log_time":"2024-10-21T07:59:59.8181798Z","id":"#REDACTED#","message":"Running deployment command...","type":0,"details_url":"https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#/log/#REDACTED#"},{"log_time":"2024-10-21T08:00:02.8249519Z","id":"#REDACTED#","message":"Running post deployment command(s)...","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:03.0754957Z","id":"#REDACTED#","message":"Triggering recycle (preview mode disabled).","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:03.3567293Z","id":"#REDACTED#","message":"Deployment successful.","type":0,"details_url":null}]}
2024-10-21T08:00:10.0203404Z Updating submodules.
2024-10-21T08:00:10.0204541Z Preparing deployment for commit id '448cb4070d'.
2024-10-21T08:00:10.0204915Z Generating deployment script.
2024-10-21T08:00:10.0205636Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T08:00:10.0206789Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T08:00:10.0207558Z ##[debug][GET]https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#/log/1677f0e4-7bee-478e-8ad2-a758c2b11192
2024-10-21T08:00:10.3327963Z ##[debug]getDeploymentLogs. Data: {"statusCode":200,"statusMessage":"OK","headers":{"content-length":"326","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 08:00:09 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","pragma":"no-cache","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":[{"log_time":"2024-10-21T07:59:59.6150311Z","id":"","message":"Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r \"C:\\local\\Temp\\zipdeploy\\extracted\" -o \"C:\\home\\site\\deployments\\tools\" --basic --sitePath \"C:\\local\\Temp\\zipdeploy\\extracted\"').","type":0,"details_url":null}]}
2024-10-21T08:00:10.3330434Z Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"').
2024-10-21T08:00:10.3331077Z Running deployment command...
2024-10-21T08:00:10.3331923Z ##[debug]setting affinity cookie ["ARRAffinity=#REDACTED#;Path=/;HttpOnly;Secure;Domain=#REDACTED#.scm.azurewebsites.net","ARRAffinitySameSite=#REDACTED#;Path=/;HttpOnly;SameSite=None;Secure;Domain=#REDACTED#.scm.azurewebsites.net"]
2024-10-21T08:00:10.3333124Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined
2024-10-21T08:00:10.3333807Z ##[debug][GET]https://#REDACTED#.scm.azurewebsites.net/api/deployments/#REDACTED#/log/#REDACTED#
2024-10-21T08:00:10.6429005Z ##[debug]getDeploymentLogs. Data: {"statusCode":200,"statusMessage":"OK","headers":{"content-length":"3023","content-type":"application/json; charset=utf-8","date":"Mon, 21 Oct 2024 08:00:10 GMT","server":"Microsoft-IIS/10.0","cache-control":"no-cache","expires":"-1","pragma":"no-cache","x-ms-request-id":"#REDACTED#","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET"},"body":[{"log_time":"2024-10-21T07:59:59.8650322Z","id":"","message":"Command: \"C:\\home\\site\\deployments\\tools\\deploy.cmd\"","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:00.8230394Z","id":"","message":"Handling Basic Web Site deployment.","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.5124738Z","id":"","message":"Creating app_offline.htm","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.5593953Z","id":"","message":"KuduSync.NET from: 'C:\\local\\Temp\\zipdeploy\\extracted' to: 'C:\\home\\site\\wwwroot'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.6218286Z","id":"","message":"Copying file: 'extensions.json'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.6843139Z","id":"","message":"Copying file: 'functions.metadata'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.7311913Z","id":"","message":"Copying file: 'host.json'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.778113Z","id":"","message":"Copying file: '#REDACTED#.deps.json'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.8405836Z","id":"","message":"Copying file: '#REDACTED#.dll'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.9032435Z","id":"","message":"Copying file: '#REDACTED#.exe'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:01.9655728Z","id":"","message":"Copying file: '#REDACTED#.pdb'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.0280794Z","id":"","message":"Copying file: '#REDACTED#.runtimeconfig.json'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.0749464Z","id":"","message":"Copying file: '#REDACTED#.Domain.dll'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.1374494Z","id":"","message":"Copying file: '#REDACTED#.Domain.pdb'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.1999509Z","id":"","message":"Copying file: '#REDACTED#.Infrastructure.dll'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.2780999Z","id":"","message":"Copying file: '#REDACTED#.Infrastructure.pdb'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.3249494Z","id":"","message":"Copying file: 'worker.config.json'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.3718358Z","id":"","message":"Copying file: '.azurefunctions\\function.deps.json'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.4343487Z","id":"","message":"Copying file: '.azurefunctions\\Microsoft.Azure.Functions.Worker.Extensions.dll'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.4968359Z","id":"","message":"Copying file: '.azurefunctions\\Microsoft.Azure.Functions.Worker.Extensions.pdb'","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.5437176Z","id":"","message":"Deleting app_offline.htm","type":0,"details_url":null},{"log_time":"2024-10-21T08:00:02.5905812Z","id":"","message":"Finished successfully.","type":0,"details_url":null}]}
2024-10-21T08:00:10.6435244Z Command: "C:\home\site\deployments\tools\deploy.cmd"
2024-10-21T08:00:10.6436658Z Handling Basic Web Site deployment.
2024-10-21T08:00:10.6437427Z Creating app_offline.htm
2024-10-21T08:00:10.6438524Z KuduSync.NET from: 'C:\local\Temp\zipdeploy\extracted' to: 'C:\home\site\wwwroot'
2024-10-21T08:00:10.6439236Z Copying file: 'extensions.json'
2024-10-21T08:00:10.6440587Z Copying file: 'functions.metadata'
2024-10-21T08:00:10.6441631Z Copying file: 'host.json'
2024-10-21T08:00:10.6442266Z Copying file: '#REDACTED#.deps.json'
2024-10-21T08:00:10.6442880Z Copying file: '#REDACTED#.dll'
2024-10-21T08:00:10.6447520Z Copying file: '#REDACTED#.exe'
2024-10-21T08:00:10.6448060Z Copying file: '#REDACTED#.pdb'
2024-10-21T08:00:10.6448896Z Copying file: '#REDACTED#.runtimeconfig.json'
2024-10-21T08:00:10.6449363Z Copying file: '#REDACTED#.Domain.dll'
2024-10-21T08:00:10.6449966Z Copying file: '#REDACTED#.Domain.pdb'
2024-10-21T08:00:10.6450400Z Copying file: '#REDACTED#.Infrastructure.dll'
2024-10-21T08:00:10.6450853Z Copying file: '#REDACTED#.Infrastructure.pdb'
2024-10-21T08:00:10.6451272Z Copying file: 'worker.config.json'
2024-10-21T08:00:10.6451902Z Copying file: '.azurefunctions\function.deps.json'
2024-10-21T08:00:10.6452411Z Copying file: '.azurefunctions\Microsoft.Azure.Functions.Worker.Extensions.dll'
2024-10-21T08:00:10.6453212Z Copying file: '.azurefunctions\Microsoft.Azure.Functions.Worker.Extensions.pdb'
2024-10-21T08:00:10.6453610Z Deleting app_offline.htm
2024-10-21T08:00:10.6453926Z Finished successfully.
2024-10-21T08:00:10.6454243Z Running post deployment command(s)...
2024-10-21T08:00:10.6454576Z Triggering recycle (preview mode disabled).
2024-10-21T08:00:10.6455058Z Deployment successful.
2024-10-21T08:00:10.6455469Z The web package has been deployed to App Service. Please note that the package mount or extraction errors will be logged in the deployment logs in the location above.
2024-10-21T08:00:10.6456099Z NOTE: Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.
```

**Comment by komjera** [comment]
@FinVamp1 were these logs enough to troubleshoot?

**Comment by ki-dro** [comment]
@FinVamp1  This issue seems to have been occurring more frequently lately.

**Comment by komjera** [comment]
@FinVamp1 This problem is occuring everyday and causes us to manually monitor our deploys, is there any way we can assist in resolving the issue besides providing logs?

**Comment by komjera** [comment]
@FinVamp1 @v-schhabra any news? We are still experiencing this bug every day. Is there anything we can do on our side to mitigate the issue?

**Comment by ki-dro** [comment]
I suppose that being unable to deploy to Azure isn't all that critical.

**Comment by FinVamp1** [comment]
@komjera Can you please send me the unredacted logs to finbarr  At Microsoft.com and I will take a look at this. I'll need to understand which SKU you are targeting to see why this is still happening and see what we can do to fix this?

**Comment by komjera** [comment]
@FinVamp1 I'll look into if there are any parts of the logs that will need to remain redacted. 

The storage account is LRS and the sku of the App Service Plan is 
```
{
    name: 'Y1'
    tier: 'Dynamic'
    size: 'Y1'
    family: 'Y'
    capacity: 0
  }
```

**Comment by FinVamp1** [comment]
@komjera If possible I would like to have a DevOps Pipeline log ran in debug mode with the site not redacted so that I can track the journey through our control plane.

"Setting System.Debug to true configures verbose logs for all runs. You can also configure verbose logs for a single run with the Enable system diagnostics checkbox."

https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemdebug

**Comment by CasaPayal** [comment]
@FinVamp1 Is this issue is resolved?

**Comment by FinVamp1** [comment]
@komjera  is it possible to see the logs between these two times..

2024-10-21T07:58:47.2477651Z Updated App Service Application settings and Kudu Application settings.
...
2024-10-21T07:59:55.2079391Z Validating deployment package for functions app before Zip Deploy
2024-10-21T07:59:55.2197332Z ##[debug]CLIENT_RESETSTREAMONRETRY=undefined

I have additional logging to see if the retry is helping. 
You may need to obscufate the specific of the appsettings.

We should have some logs like this.

UpdatedAppServiceApplicationSettings
retrieving values from Kudu service to check if new values are updated
If Kudu doesn't have the values yet we retry up to 12 times 
New properties are not updated in Kudu service 
Deleted properties are not reflected in Kudu service 
If it works then we log 
'New properties are updated in Kudu service
If it never works we timeout the task.
