### ISSUE TITLE
Copy Files using Clean Target Folder sometimes fails with EPERM: operation not permitted

### ISSUE THREAD

**Issue by perreaultd** [microsoft/azure-pipelines-tasks#5472]
I have release definitions having the "Copy Files" task and "Clean target folder" option checked.
Most of the deployments are successfull, so security seems rights.
Service account is in server local admin group which have full control of folder within NTFS security.

Sometimes the tasks end up giving the EPERM: operation not permitted error message. After getting the error, we can see that the folder deletion occured correctly because the folder exists no more. We just have to press "Deploy" again and the deployment ends up good. The issue seems to be "on and off" because we had 5 straight good release before hitting the problem. Then pressing re-deploy did the job. The next release got again the issue and we needed to re-deploy twice before ending up the release.
When the issue occured, we are sure no Windows Explorer were open by dev team into the folder that got cleanup.

Do you have an idea what can cause this issue?

**Comment by perreaultd** [comment]
Any hint on this? Got the error twice in a row again this moring.

**Comment by ericsciple** [comment]
@perreaultd A workaround is to do the delete yourself. If you have antivirus on, I suspect that adding an exclusion for folder would workaround the issue as well.

I suspect the issue is occurring because node unlink() decrements the ref count on the file, and the OS deletes the file after all ref counts are removed. If contents in the folder are still pretty fresh, then anti-virus may not be done scanning the files yet. Then you are hitting a race condition attempting to recreate the folder/files.

**Comment by ericsciple** [comment]
@bryanmacfarlane we need either a new or updated lib function to do the delete. Either sleep in a loop and wait for the delete to finish, or shell out to do the delete. There are aspects about both options that I am not enthusiastic about (poll and sleep in js, or spawn a process on Windows and handle escaping problems correctly either across an env var or in a batch script).

**Comment by perreaultd** [comment]
@ericsciple thanks for the tips. We'll try to antivirus workaround and will keep you inform. The task is used into a continous deployment release definition so deleting content myself is not an option. We use this step and clean target folder to make sure deployment content does not "inherit" from previous deployments and do a full clean before copying files. We used to do this using robocopy command in previous release management tools.

**Comment by ericsciple** [comment]
Sorry, by do-the-delete-yourself I mean to add a step immediately prior that does something like `rmdir /s /q` on the folder. Or robocopy (mirror copy against an empty folder) with multithreaded option might be quicker if you have a lot of files to delete, or across network IO.

**Comment by perreaultd** [comment]
@ericsciple the antivirus exclusion workaround seems to do the job. No more copy files failed since. I am willing to "patch" all existing deployments servers using an exclusion, but you mentionned earlier in this conversation to @bryanmacfarlane a new version of the function. When can we expect this? I'd prefer having sucessfull releases because i am using a better task than a "sometime-failing" task mixed up with AV exclusion.

**Comment by Calidus** [comment]
This is still an issue, has anyone considered the option of removing the clean folder option? Microsoft already provides a 'Delete Files from' Task.

**Comment by sergienko4** [comment]
I have the same error with Delete Files from' Task.
:-(

**Comment by ryanbuening** [comment]
@sergienko4 same here. Were you able to resolve your issue with Delete Files? I get the following error:

`Failed rmRF: EPERM: operation not permitted, unlink 'D:\Web Apps\FileName.dll`

**Comment by ericsciple** [comment]
@damccorm @stephenmichaelf i think the best path forward is to change the rmrf function in the task lib to shell out to rm on nix and robocopy or rmdir on windows.

Consider bumping major version, otherwise add an overload. And the command line escaping needs to be 100% accurate.

**Comment by codehunter13** [comment]
i still have this issue

**Comment by JGCreator** [comment]
I am also still seeing this issue when trying to clean a directory after the contents are supposed to have been copied over.

**Comment by damccorm** [comment]
This should be fixed in the task-lib by this PR: https://github.com/Microsoft/azure-pipelines-task-lib/pull/518

Once that's in we can consume the new version here. We might want to wait until the task-lib is entirely out of preview though.

**Comment by chaitu89a** [comment]
Hello, i'm facing the same issue with copy task but i see that happening only when i'm attempting to copy files from artifact to target server (windows machine) and redeploy isn't helping too. May i please know when would the update "Fix rmrf and drop version to 2.9.0 #531" be merged so i hope that can fix my issue too. Thanks!

**Comment by turbodrubin** [comment]
I'm also waiting for the release of [the pull request](https://github.com/microsoft/azure-pipelines-task-lib/pull/531); any update on its status or a timeline to get the fix out? Thanks!

**Comment by 0xaryan** [comment]
Giving enough permissions to "NETWORK SERVICE" solved the problem on my side.

![image](https://user-images.githubusercontent.com/9091958/68371582-42ee1000-0154-11ea-92dc-a96c35c3ce23.png)

**Comment by ogarciacapetillo** [comment]
@0xaryan would please elaborate on how to provide privileges to Network service account, it would help for me, thank you.

**Comment by damccorm** [comment]
This should now be fixed - let me know if you're still running into the issue

**Comment by kaushikgayal** [comment]
Still getting the issue with Copy Files task.
![image](https://user-images.githubusercontent.com/22347902/77591776-cc0bb500-6f44-11ea-94a5-f216e8f00794.png)

![image](https://user-images.githubusercontent.com/22347902/77592079-7b488c00-6f45-11ea-8fdd-4787a1e11f3d.png)

**Comment by kaushikgayal** [comment]
Still getting the issue.

![image](https://user-images.githubusercontent.com/22347902/77592242-e09c7d00-6f45-11ea-9b7f-469aa45098af.png)

![image](https://user-images.githubusercontent.com/22347902/77592336-10e41b80-6f46-11ea-96db-6273b8b08533.png)

**Comment by optiks** [comment]
Also still hitting this.

**Comment by MiroKov** [comment]
still a problem here.

**Comment by kaushikgayal** [comment]
Hope this helps.
In my case, Copy files was not able to unlink the root folder coz there were files in subdirectories having path length greater than 256, which the utility was not able to find.

The workaround that worked was to use robocopy with purge.
![image](https://user-images.githubusercontent.com/22347902/78220670-af0b4f00-750d-11ea-9840-38be5b581ebd.png)

**Comment by MehdiSaeedifar** [comment]
@0xaryan Thanks. It worked for me.

**Comment by braydie** [comment]
This is still an issue for me

**Comment by xantari** [comment]
Still an issue here as well.

**Comment by Rayzbam** [comment]
Still an issue here as well. Using .net core app and some Azure client things.

Got : Failed rmRF: EPERM: operation not permitted, unlink '$LocalPath$\Azure.Core.dll'

In my case, i've got everytime the same file, "Azure.Core.dll" and i deploy multiple services in multiple repositories.

**Comment by jpmoura** [comment]
Still an issue here using MSbuild for a .NET Framework 4.7.1 application.

It occours sometimes after the `Publish Quality Gate Result` task with SonarCloud plugin in a task to copy the artifacts originated in build step:

`##[error]Unhandled: Failed rmRF: EPERM: operation not permitted, unlink 'D:\a\1\a\.sqAnalysis'`

**Comment by JoeyCor** [comment]
I still have the same issue here for a .Net 4.7.1 web application.

**Comment by righardtmarais** [comment]
Still an issue for us today.
Using Copy files Task version 2.*
Clean Target Folder ticked.

2020-08-26T08:46:44.1940259Z Cleaning target folder: C:\aaa\aaa.sites\aaa-web\build
2020-08-26T08:46:44.2092589Z C:\aaa\aaa.sites\aaa-web\build\css\semantic - The directory is not empty.
2020-08-26T08:46:44.2184445Z ##[error]Unhandled: Failed rmRF: EPERM: operation not permitted, unlink 'C:\aaa\aaa.sites\aaa-web\build\css'

**Comment by iginzburg** [comment]
I have the same issue as well.

**Comment by charleaux** [comment]
Same issue for me today using Copy Files task 2.* with clean target folder option checked.

2020-09-18T15:30:35.8562671Z ##[error]Unhandled: Failed rmRF: EPERM: operation not permitted, unlink

**Comment by phil-veloso** [comment]
Im also getting the same issue:

Command failed: rd /s /q  - Access is denied.

**Comment by johnybaryah** [comment]
Dont think this is a pipeline-task issue. In my case, I was deploying a windows service but previous installation (.exe) was sitting in a suspended state and it was holding on to one of the dlls hence I wasn't able to clean the folder. I couldn't manually kill the process either.. ended up rebooting the server

**Comment by AroglDarthu** [comment]
We also use this task after stopping a windows service. The service gets killed in case a normal stop fails. Even then, we experience this issue. The workaround that worked for us was to insert an **Inline Powershell** task that simply does a delay:
```
Param (
  [int]$delayInSeconds
)

Start-Sleep -Seconds $delayInSeconds;
```

**Comment by TroyMeOut** [comment]
I'm still running into this issue. It appears that IIS has some of the files locked. If I log onto the server and manually try to delete the files it fails. If i restart the app pool i am able to delete them.

Now I'm running into issues getting elevated permissions for the account running powershell scripts to be able to restart the app pool using 

`Import-Module WebAdministration
Restart-WebAppPool "xx"`

**Comment by trytocatchme** [comment]
I had almost the same issue, maybe is not strictly related this one but looked for solution I found this topic, so on my side, problem was caused by account that was used by azure agent(window service). By default during agent installation service account is set to "NT AUTHORITY\SYSTEM", that doesn't have enough rights to copy files to the destination folder.
I suggest to change folder/shared folder permission for instance grant "Evereyone" group full access and change azure agent account that using(window service).

![image](https://user-images.githubusercontent.com/12458009/115450776-a2db5800-a21c-11eb-88d7-ce5b1c65029c.png)

**Comment by nigeledw** [comment]
I only see potential workarounds and no solution here

**Comment by anatolybolshakov** [comment]
Hi everyone, the EPERM: operation not permitted could happen for variety of reasons during cleaning up of a target folder - but usually this means that some file is being locked by some process (antivirus, or any other).
To avoid flakiness issues with EPERM - you can use 'retryCount' and 'delayBetweenRetries' inputs - to set up count of retry attempts/delay between retries in ms for the task.
