### ISSUE TITLE
[Feature request] Docker build should use cache unless asked not to

### ISSUE THREAD

**Issue by MirzaSikander** [microsoft/azure-pipelines-tasks#6439]
## Environment
- Server - VSTS or TFS on-premises?
 VSTS   

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
Linux Hosted Preview

## Issue Description
Locally, if you manually build docker containers over and over again with small changes, the docker daemon uses cache to speed up docker build.

On VSTS, every time a build is started, the docker build goes through the same steps that it has gone over previously: the base images are fetched and expanded, apt-get installs all the dependencies, files are copied over, etc. This adds a lot of time for each build; In fact the majority of build time for our CI/CD is wasted in this. 

Expectation:
If the host being used is the same for each build, it should make use of the cache from previous builds to 
speed up this step, unless specifically not asked to.

**Comment by borkke** [comment]
+1 for this one.

Does anyone know is it the same on TFS?

**Comment by polys** [comment]
On **Hosted VS2017** agents, some container images are already cached apparently:
https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#docker-images

**Comment by linuxchata** [comment]
Is there information about container images cached on **Hosted Linux Preview** agents?

**Comment by chrisrpatterson** [comment]
The host is not the same for each build, it is a fresh host each time for security and consistency reasons.  We do precache some of those images on the host machines.  We can look at caching others but that cache will always drift from what is currently published simply due to how often the pool is updated.  So it is possible that you build a docker container with a node base and you get a different sha256 base when you build in CI from what you get when you build locally.

**Comment by bryanmacfarlane** [comment]
note that we are going to release a new Ubuntu (released) hosted pool and we're investigating caching a series of more focused containers (node, dotnet core etc...).  We may keep a couple tags of each.  But as @chrisrpatterson noted, you're cache hits will be hit or miss for a number of factors.  We're experimenting now.

This issue should move to vsts-image-generation repo since that's where the hosted VM gen and the new docker images work will happen.

**Comment by andreacassioli** [comment]
I have noticed that the docker build process always delete intermediate containers. Why is that? It is not the default Docker behaviour. We have some use cases in which we would like to split a multi-stage build in multiple tasks, but right know there is no way to cache one stage to the second.

Notice that that does not happen running docker build fro ma bash task.

**Comment by harshil93** [comment]
@andreacassioli Not an expert on docker but the default option in docker build is to remove intermediate containers. Do you want to keep the containers after docker build ?

https://docs.docker.com/engine/reference/commandline/build/#options

See the --rm

**Comment by mattnedrich** [comment]
Any update on this?

**Comment by mattquinn** [comment]
I have a customer interested in this feature. 
They understand running your own private build agent can solve this, but the tradeoff of then having to manage that infrastructure isn't compelling. 

The idea of being able to leverage the cache in a hosted build agent is compelling - quicker builds, without managing infrastructure - and could help get their builds down from tens of minutes to ~1-2 mins, which on their CI/CD "always deploying" plans would be a massive win.

**Comment by AndreyBespamyatnov** [comment]
Have the same issue with Downloading MSSQL image every time, takes ~20 min. 
Thanks

**Comment by nelisbijl** [comment]
> I have a customer interested in this feature.
> They understand running your own private build agent can solve this, but the tradeoff of then having to manage that infrastructure isn't compelling.
> 
> The idea of being able to leverage the cache in a hosted build agent is compelling - quicker builds, without managing infrastructure - and could help get their builds down from tens of minutes to ~1-2 mins, which on their CI/CD "always deploying" plans would be a massive win.

I managed to create a self-hosted agent from https://github.com/Microsoft/azure-pipelines-image-generation using packer. Although the documentation fails to explain how to create a VM from the generated vhd and image file, I got one up and running, installed the agent software and configured it.

However, this agent still fails to cache the costly 'npm install' step in my Dockerfile.
If I run the same docker build command on that machine in the folder created by the pipeline agent, it does use the cached docker image!!
Something must be different between using the commandline and using the azure pipeline agent but I haven't found it yet

**Comment by willemodendaal** [comment]
Hello from 2019. I guess this is still an issue... pity. Would really like to use VSTS hosted agents, but not being able to cache container images makes the build super slow. 20+ minutes instead of 1 minute.

**Comment by cpumanaz** [comment]
I am experiencing the same. using the "FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2016" source image. It was mentioned not every hash is cached and there is drift.  Is it documented which specific tag(s) are cached on the VS2017 server so we can choose those source images?

**Comment by cpumanaz** [comment]
I'm reporting back. The reason that many might have issues is using `:latest`  If you were taught using the `latest` tag was bad then you will not see the performance gains.  By adding a docker image list task, I saw which images were pre-loaded.

```##[section]Starting: List Agent Images
==============================================================================
Task         : Docker
Description  : Build, tag, push, or run Docker images, or run a Docker command. Task can be used with Docker or Azure Container registry.
Version      : 1.1.27
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=848006)
==============================================================================
[command]"C:\Program Files\Docker\docker.exe" image list
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/dotnet-framework    latest              ec599075a73c        7 weeks ago         13.2GB
microsoft/windowsservercore   latest              ea9f7aa13d03        7 weeks ago         11GB
microsoft/aspnet              latest              ddabd3e10c02        3 months ago        13.7GB
microsoft/nanoserver          latest              4c872414bf9d        4 months ago        1.17GB
microsoft/aspnetcore-build    1.0-2.0             5d8be0910d37        6 months ago        3.99GB```

**Comment by andreujuanc** [comment]
That's interesting. At least that's a good start. 
Problem is that many depend on specific versios, and that might be still an issue :(

**Comment by sebnyberg** [comment]
I keep coming back to this thread to check whether anything is happening on the topic. 

As our CI and release pipelines have turned into a sequence of docker and helm commands, the only long running issue is this one. Spending (wasting) almost 90% of build time downloading images and packages due to lack of support for layer caching is disappointing to say the least.

Considering that we no longer have a need for the Azure integration features, we don't depend on using Azure DevOps anymore. Changing all our pipelines to a competitor however is also quite a task so I wish this would see higher priority.

**Comment by bansalaseem** [comment]
@sebnyberg This is something we have planned in our current quarters deliverable, so hopefully next time you visit this page, you should see something moving.

**Comment by damienwebdev** [comment]
@bryanmacfarlane would this be solvable by https://github.com/Microsoft/azure-pipelines-yaml/pull/113 ?

**Comment by BenWalters** [comment]
@chrispat @bryanmacfarlane, do you have any news on this? It's been being discussed for a long time now. Even a timeline would be nice.

**Comment by jarednlivingston** [comment]
> @chrispat @bryanmacfarlane, do you have any news on this? It's been being discussed for a long time now. Even a timeline would be nice.

It looks like it might be coming in June 2019:
https://github.com/microsoft/azure-pipelines-yaml/pull/113#issuecomment-493113099

**Comment by oak-tree** [comment]
Hey!
`Docker cache` is a must have feature for `devops`. We are lossing so much time for rebuilding our `image` for every single relase.. :(
according to the last comment at https://github.com/microsoft/azure-pipelines-yaml/pull/113#issuecomment-505890542, the https://github.com/microsoft/azure-pipelines-yaml/pull/113 does not going to fix this issue. Any ideas when `devops` plans to `release` this feature?

**Comment by jfranki** [comment]
We have a Dockerfile with a base image of more than 2GB (MATLAB Runtime) stored in an Azure Container Registry. So yeah... that one has to be built locally on every update until this is sorted out.

**Comment by BenWalters** [comment]
This feature request has been open 18 months now with the last update over 1 year ago!

@bryanmacfarlane & @chrispat could we have an update please as I don't believe that **microsoft/azure-pipelines-yaml#113** doesn't look like it'll solve it.

**Comment by bryanmacfarlane** [comment]
You are correct that the caching feature won't help you here.  It's also not a task issue.  

Hosted pools re-image and give you a fresh machine every time.
Private / custom agents on your own VM is the only way to get incremental build, images, etc.

There is a feature which is the best of both worlds. 

https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/byos.md
That would give you incremental cached containers with the convenience of hosted pools (spun up and down for you).

You should probably create a feature request here as that's a large feature / service addition (not an issue with a task).  Get some votes.

https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea

@thejoebourneidentity FYI as his team is driving that feature (they own hosted pools).

I'm inclined to close this issue here because it's not a task issue and it just won't get traction here.

**Comment by BenWalters** [comment]
Hi @bryanmacfarlane 
Thanks for the update, although a little surprised that this answer hasn't been given sooner!
Guess we are back of the queue again with this request 👎

**Comment by bryanmacfarlane** [comment]
Time hasn't been wasted on the queue because of this issue.  It has been actively proposed, already designed per the link above and the feature has been postponed by product.  

Closing as this isn't a task issue.

I've forwarded this link to the team ( @thejoebourneidentity ) with the feature and also sent them a mail.

**Comment by gldraphael** [comment]
Relevant link: https://developercommunity.visualstudio.com/idea/365799/improve-hosted-build-agent-performance-with-build.html

https://developercommunity.visualstudio.com/comments/515033/view.html

**Comment by thejoebourneidentity** [comment]
Thanks @bryanmacfarlane. Hey folks, Bryan is right. True E2E docker layer caching won't be achieved in our hosted pools since we refresh machines between jobs. The postponed 'BYOS' feature as it is called on the agent repo is absolutely on our radar and will give you maximum caching flexibility.

In the meantime, if there are base container images you would like to see us include in our hosted pool images, please feel free to request them over on our image gen repo: https://github.com/microsoft/azure-pipelines-image-generation

**Comment by robertoandrade** [comment]
I was able to get this working using the Cache task and some conditional manual `docker save/load` commands after it to dump the desired docker image (and its layers) into a tar ball that the Cache task would then upload and download on the next execution which the `load` command from docker would put back into the local registry. The time it takes the Cache task to perform its thing in combination with the `docker save/load` respective operations pretty much matched that of downloading the base image/layers from a public registry, so not seeing much benefit in doing it.

In an earlier attempt spent a significant amount of time trying to cache the contents of C:\ProgramData\Docker (where the deconstructed images are stored) and even change the docker daemon to point to another location, that was unsuccessful given the container set permissions on the files/folders there.

When running benchmark tests locally in a Windows VM on my Mac, it seems to download and extract files much faster than the Azure Pipeline agents, so thinking the key bottleneck is I/O and perhaps networking.

**Comment by RobertoPrevato** [comment]
On July 2019 I published files to build Docker images for private Azure DevOps agents. One of them has Docker, so it supports Docker workloads. If you can run a container on a machine, this is a possible solution to benefit of caching, and speed up builds.

It takes a few minutes to run a private agent this way - once you know the few steps.

https://github.com/RobertoPrevato/AzureDevOps-agents

**Comment by letmaik** [comment]
@bryanmacfarlane @thejoebourneidentity I think the ask here is not to re-use VMs but still have a fresh VM each time (that's my use case anyway) with the option of defining that Docker layers should be cached across runs, similarly to how regular folders can be cached. For that, BYOS wouldn't bring any benefit. What's the technical limitation to get this going? Is it simply that Docker doesn't easily allow to restore a local cache? Has anyone deeply looked into this already?

**Comment by letmaik** [comment]
Follow-up: Even though not as simple as a "checkbox", I was successful in saving/restoring a Docker build cache by using Docker's [`--cache-from`](https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources) feature. Note that this requires pushing the built images (along with the cache) to a registry, which may not always be available. In another issue, [a prototype was done](https://github.com/microsoft/azure-pipelines-tasks/issues/11034#issuecomment-555236514) on saving the cache to a folder using the Azure Pipelines cache functionality, however, that approach seems much more involved and also requires to install BuildKit separately.

**Comment by adrian-skybaker** [comment]
>The postponed 'BYOS' feature as it is called on the agent repo is absolutely on our radar and will give you maximum caching flexibility.

Relying on this feature seems overkill for a simple, transparent docker cache, which is offered by other CI/CD platforms. The pipeline caching feature seems a better place for this. Caching source docker images is conceptually not very different to caching maven dependencies.

**Comment by keesschollaart81** [comment]
Pulling the :latest and then using `--cache-from` point to it, like the example, below seems to work, or am I missing something?

```yaml
- task: Docker@2
  inputs:
    containerRegistry: '$(ContainerRegistryName)'
    command: 'login'

- script: "docker pull $(ACR_ADDRESS)/$(REPOSITORY):latest"
  displayName: Pull latest for layer caching
  continueOnError: true # for first build, no cache

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: '$(ContainerRegistryName)'
    repository: '$(REPOSITORY)'
    command: 'build'
    Dockerfile: './dockerfile '
    buildContext: '$(BUILDCONTEXT)'
    arguments: '--cache-from=$(ACR_ADDRESS)/$(REPOSITORY):latest' 
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: "push"
  inputs:
    command: push
    containerRegistry: "$(ContainerRegistryName)"
    repository: $(REPOSITORY) 
    tags: |
      $(DOCKERTAG)-amd64
      latest
```

**Comment by mizhgun** [comment]
@keesschollaart81  actually no need to pull, just additional [variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops#buildkit) and [argument](https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources)

Something like that:
```
variables:
  DOCKER_BUILDKIT: 1

...

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: '$(ContainerRegistryName)'
    repository: '$(REPOSITORY)'
    command: 'build'
    Dockerfile: './dockerfile '
    buildContext: '$(BUILDCONTEXT)'
    arguments: '--cache-from $(ACR_ADDRESS)/$(REPOSITORY):latest --build-arg BUILDKIT_INLINE_CACHE=1'
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: "push"
  inputs:
    command: push
    containerRegistry: "$(ContainerRegistryName)"
    repository: $(REPOSITORY) 
    tags: |
      $(Build.BuildNumber)
      latest
```
