### ISSUE TITLE
MSBuild throwing error while deploying SSRS project

### ISSUE THREAD

**Issue by Poseideon** [microsoft/azure-pipelines-tasks#7142]
## Environment
- Server - TFS on-premise
    
    - If using TFS on-premises, provide the version: TFS 2017 Update 3
    
- Agent - Hosted or Private: 
    
   - Private agent hosted on OS Windows 2012 R2 and the agent version: 2.126

## Issue Description
We are trying to deploy SSRS reports via MSBuild; running MSBuild task in release definition to deploy SSRS reports to SQL Server Reporting Server 2012.  Microsoft Reporting Services Projects extension has been installed on build server. MSBuild deploys rdl files but throws an error - 
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): Error :  : Object reference not set to an instance of an object.

### Error logs

2018-05-04T19:00:41.9159442Z ##[section]Starting: Build solution $(System.DefaultWorkingDirectory)/PAWorkflow_DevOps_SSRS_DEVA/DevA/PAWorkflowReports.sln
2018-05-04T19:00:41.9412492Z ==============================================================================
2018-05-04T19:00:41.9412704Z Task         : MSBuild
2018-05-04T19:00:41.9412859Z Description  : Build with MSBuild
2018-05-04T19:00:41.9413047Z Version      : 1.119.0
2018-05-04T19:00:41.9413238Z Author       : Microsoft Corporation
2018-05-04T19:00:41.9413455Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613724)
2018-05-04T19:00:41.9414462Z ==============================================================================
2018-05-04T19:00:43.3321723Z ##[command]"D:\b3_w\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.119.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -latest -format json
2018-05-04T19:00:43.5781857Z ##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\PAWorkflowReports.sln" /nologo /nr:false /t:"Clean" /dl:CentralLogger,"D:\b3_w\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.119.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=b9336ee7-7ded-4891-893b-5f5ed9358376|SolutionDir=d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA"*ForwardingLogger,"D:\b3_w\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.119.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:BuildType=Deploy /p:Configuration=DevA /p:_MSDeployUserAgent="TFS_58ce16b6-8186-4b69-a761-0e4b12cc6918_release_4_113_113_1"
2018-05-04T19:00:43.6729901Z Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
2018-05-04T19:00:43.7129000Z Build started 5/4/2018 2:00:43 PM.
2018-05-04T19:00:43.8649418Z Project "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" on node 1 (Clean target(s)).
2018-05-04T19:00:43.8657339Z ValidateSolutionConfiguration:
2018-05-04T19:00:43.8657645Z   Building solution configuration "DevA|Default".
2018-05-04T19:00:43.9952503Z Done Building Project "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" (Clean target(s)).
2018-05-04T19:00:43.9975606Z 
2018-05-04T19:00:43.9976492Z Build succeeded.
2018-05-04T19:00:43.9980662Z     0 Warning(s)
2018-05-04T19:00:43.9980809Z     0 Error(s)
2018-05-04T19:00:43.9983950Z 
2018-05-04T19:00:43.9984205Z Time Elapsed 00:00:00.28
2018-05-04T19:00:44.0182064Z ##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" /nologo /nr:false /dl:CentralLogger,"D:\b3_w\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.119.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=df19984b-719a-483c-8a21-966f2c2fe186|SolutionDir=d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA"*ForwardingLogger,"D:\b3_w\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.119.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:BuildType=Deploy /p:Configuration=DevA /p:_MSDeployUserAgent="TFS_58ce16b6-8186-4b69-a761-0e4b12cc6918_release_4_113_113_1"
2018-05-04T19:00:44.1905081Z Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
2018-05-04T19:00:44.2313618Z Build started 5/4/2018 2:00:44 PM.
2018-05-04T19:00:44.3991578Z Project "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" on node 1 (default targets).
2018-05-04T19:00:44.3999143Z ValidateSolutionConfiguration:
2018-05-04T19:00:44.3999349Z   Building solution configuration "DevA|Default".
2018-05-04T19:00:44.5049188Z Project "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" (1) is building "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj" (2) on node 1 (default targets).
2018-05-04T19:00:44.5051139Z PrepareForBuild:
2018-05-04T19:00:44.5051389Z   Creating directory "obj\\DevA\".
2018-05-04T19:00:44.5948274Z ReportBuilderTarget:
2018-05-04T19:00:44.5948654Z   Copying 'constrpaint.gif' to the output folder.
2018-05-04T19:00:44.6116751Z   Building the report, Rpt_Report1.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.7017767Z   Building the report, Rpt_Report2.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.7264648Z   Building the report, Rpt_Report3.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.7510327Z   Building the report, Rpt_Report4.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.7884939Z   Building the report, Rpt_Report5.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.8139122Z   Building the report, Rpt_Report6.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.8375649Z   Building the report, Rpt_Report7.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.8646403Z   Building the report, Rpt_Report8.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.8916569Z   Building the report, Rpt_Report9.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.9195420Z   Building the report, Rpt_Report10.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.9466672Z   Building the report, Rpt_Report11.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.9727574Z   Building the report, Rpt_Report12.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:44.9999548Z   Building the report, Rpt_Report13.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:45.0279098Z   Building the report, Rpt_Report14.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:45.1073885Z   Building the report, Rpt_Report15.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0777789Z   Building the report, Rpt_Report16.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0778184Z   Building the report, Rpt_Report17.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0778557Z   Building the report, Rpt_Report18.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0778762Z   Building the report, Rpt_Report19.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0778889Z   Building the report, Rpt_Report20.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779015Z   Building the report, Rpt_Report21.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779178Z   Building the report, Rpt_Report22.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779307Z   Building the report, Rpt_Report23.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779430Z   Building the report, Rpt_Report24.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779568Z   Building the report, Rpt_Report25.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779701Z   Building the report, Rpt_Report26.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779824Z   Building the report, Rpt_Report27.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0779970Z   Building the report, Rpt_Report28.rdl, for SQL Server 2008 R2, 2012 or 2014 Reporting Services.
2018-05-04T19:00:46.0780080Z   Copying 'logo.jpg' to the output folder.
2018-05-04T19:00:46.0781332Z   Building the shared data source 'DataSourcePAWorkFlow.rds'.
2018-05-04T19:00:46.0781458Z   Building 'EndDateDataSet.rsd' Shared Data Set.
2018-05-04T19:00:46.0781560Z   Building 'StartDateDataSet.rsd' Shared Data Set.
2018-05-04T19:00:46.7138469Z   Deploying to http://server1/reportserver
2018-05-04T19:00:46.8161451Z ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): Error :  : Object reference not set to an instance of an object.
2018-05-04T19:00:46.8162138Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): error :  : Object reference not set to an instance of an object. [d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj]
2018-05-04T19:00:46.8720696Z   Deploying data set '/PAWorkflow/EndDateDataSet'.
2018-05-04T19:00:46.9119441Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): Warning : Cannot deploy dataset EndDateDataSet to the server because it already exists and OverwriteDatasets is not specified.
2018-05-04T19:00:46.9120133Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): warning : Cannot deploy dataset EndDateDataSet to the server because it already exists and OverwriteDatasets is not specified. [d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj]
2018-05-04T19:00:46.9619002Z   Deploying data set '/PAWorkflow/StartDateDataSet'.
2018-05-04T19:00:46.9809104Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): Warning : Cannot deploy dataset StartDateDataSet to the server because it already exists and OverwriteDatasets is not specified.
2018-05-04T19:00:46.9809776Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): warning : Cannot deploy dataset StartDateDataSet to the server because it already exists and OverwriteDatasets is not specified. [d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj]
2018-05-04T19:00:47.0244201Z   Deploying report '/PAWorkflow/Rpt_Report1'.
2018-05-04T19:00:47.3550934Z   Deploying report '/PAWorkflow/Rpt_Report2'.
2018-05-04T19:00:47.7445139Z   Deploying report '/PAWorkflow/Rpt_Report3'.
2018-05-04T19:00:48.0808076Z   Deploying report '/PAWorkflow/Rpt_Report4'.
2018-05-04T19:00:48.3807914Z   Deploying report '/PAWorkflow/Rpt_Report5'.
2018-05-04T19:00:48.7567180Z   Deploying report '/PAWorkflow/Rpt_Report6'.
2018-05-04T19:00:49.0610339Z   Deploying report '/PAWorkflow/Rpt_Report7'.
2018-05-04T19:00:49.3524233Z   Deploying report '/PAWorkflow/Rpt_Report8'.
2018-05-04T19:00:49.6570219Z   Deploying report '/PAWorkflow/Rpt_Report9'.
2018-05-04T19:00:49.9305375Z   Deploying report '/PAWorkflow/Rpt_Report10'.
2018-05-04T19:00:50.1938613Z   Deploying report '/PAWorkflow/Rpt_Report11'.
2018-05-04T19:00:50.4475556Z   Deploying report '/PAWorkflow/Rpt_Report12'.
2018-05-04T19:00:50.7320878Z   Deploying report '/PAWorkflow/Rpt_Report13'.
2018-05-04T19:00:51.0385609Z   Deploying report '/PAWorkflow/Rpt_Report14'.
2018-05-04T19:00:51.6781597Z   Deploying report '/PAWorkflow/Rpt_Report15'.
2018-05-04T19:00:52.0588548Z   Deploying report '/PAWorkflow/Rpt_Report16'.
2018-05-04T19:00:52.3759211Z   Deploying report '/PAWorkflow/Rpt_Report17'.
2018-05-04T19:00:52.7598144Z   Deploying report '/PAWorkflow/Rpt_Report18'.
2018-05-04T19:00:53.1114461Z   Deploying report '/PAWorkflow/Rpt_Report19'.
2018-05-04T19:00:53.4468047Z   Deploying report '/PAWorkflow/Rpt_Report20'.
2018-05-04T19:00:53.8232204Z   Deploying report '/PAWorkflow/Rpt_Report21'.
2018-05-04T19:00:54.1796138Z   Deploying report '/PAWorkflow/Rpt_Report22'.
2018-05-04T19:00:54.5269233Z   Deploying report '/PAWorkflow/Rpt_Report23'.
2018-05-04T19:00:54.8421797Z   Deploying report '/PAWorkflow/Rpt_Report24'.
2018-05-04T19:00:55.2274001Z   Deploying report '/PAWorkflow/Rpt_Report25'.
2018-05-04T19:00:55.5390035Z   Deploying report '/PAWorkflow/Rpt_Report26'.
2018-05-04T19:00:55.9619105Z   Deploying report '/PAWorkflow/Rpt_Report27'.
2018-05-04T19:00:56.3205673Z   Deploying report '/PAWorkflow/Rpt_Report28'.
2018-05-04T19:00:56.6517644Z   Deploying resource '/PAWorkflow/constrpaint.gif'.
2018-05-04T19:00:56.7044818Z   Deploying resource '/PAWorkflow/logo.jpg'.
2018-05-04T19:00:56.7532500Z Done Building Project "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj" (default targets) -- FAILED.
2018-05-04T19:00:56.7553757Z Done Building Project "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" (default targets) -- FAILED.
2018-05-04T19:00:56.7573616Z 
2018-05-04T19:00:56.7573822Z Build FAILED.
2018-05-04T19:00:56.7601739Z 
2018-05-04T19:00:56.7610472Z "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" (default target) (1) ->
2018-05-04T19:00:56.7610745Z "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj" (default target) (2) ->
2018-05-04T19:00:56.7610972Z (ReportBuilderTarget target) -> 
2018-05-04T19:00:56.7611679Z   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): warning : Cannot deploy dataset EndDateDataSet to the server because it already exists and OverwriteDatasets is not specified. [d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj]
2018-05-04T19:00:56.7613482Z   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): warning : Cannot deploy dataset StartDateDataSet to the server because it already exists and OverwriteDatasets is not specified. [d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj]
2018-05-04T19:00:56.7613749Z 
2018-05-04T19:00:56.7614092Z 
2018-05-04T19:00:56.7615491Z "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports.sln" (default target) (1) ->
2018-05-04T19:00:56.7615866Z "d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj" (default target) (2) ->
2018-05-04T19:00:56.7616018Z (ReportBuilderTarget target) -> 
2018-05-04T19:00:56.7616241Z   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): error :  : Object reference not set to an instance of an object. [d:\b3_w\r10\a\PAWorkflow_DevOps_SSRS_DEVA\DevA\Reports\Reports.rptproj]
2018-05-04T19:00:56.7616408Z 
2018-05-04T19:00:56.7616626Z     2 Warning(s)
2018-05-04T19:00:56.7616719Z     1 Error(s)
2018-05-04T19:00:56.7617215Z 
2018-05-04T19:00:56.7617413Z Time Elapsed 00:00:12.53
2018-05-04T19:00:56.8772743Z ##[error]Process 'msbuild.exe' exited with code '1'.
2018-05-04T19:00:56.9238199Z ##[section]Finishing: Build solution $(System.DefaultWorkingDirectory)/PAWorkflow_DevOps_SSRS_DEVA/DevA/Reports.sln

**Comment by Poseideon** [comment]
Please help! badly stuck with the error.

**Comment by mwjones10** [comment]
Hello,

Can you try to build/deploy with the latest VS 2017 installed with the latest Reporting Services Project Extension?  I recently made a fix in this space dealing with Shared Datasets and Shared Data Sources.  Please respond on this thread either way.  If it works, we need to update the CI/CD RS VSIX.  If not, I will need to investigate your rsproj file.

Thanks,
Matt

**Comment by esstump** [comment]
I am having similar problems. I ma trying to use msbuild to deploy ssrs reports and shared data sources. That error "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets(30,5): Error : : Object reference not set to an instance of an object." happens when it tries to deploy the data sources.  Reports are deployed with no problems.

Here is a snippet of my project file

<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
	<SourcePath>..\..\Reports\</SourcePath>
    <FullPath>Release</FullPath>
    <OutputPath>bin\Release</OutputPath>
    <ErrorLevel>2</ErrorLevel>
    <OverwriteDatasets>False</OverwriteDatasets>
    <OverwriteDataSources>True</OverwriteDataSources>
    <TargetServerVersion>SSRS2008R2</TargetServerVersion>
    <Platform>AnyCpu</Platform>
    <TargetReportFolder>/CI</TargetReportFolder>
    <TargetDatasetFolder>/CI/Datasets</TargetDatasetFolder>
    <TargetDatasourceFolder>/CI</TargetDatasourceFolder>
    <TargetReportPartFolder>/CI/ReportParts</TargetReportPartFolder>
    <TargetServerURL>http://pcssqltest/ReportServer</TargetServerURL>
  </PropertyGroup>
  <PropertyGroup>
    <State>$base64$.......</State>
    <DataSources>@(DataSource)</DataSources>
    <DataSets>@(DataSet)</DataSets>
    <Reports>@(Report)</Reports>
  </PropertyGroup>
  <ItemGroup>
    <DataSource Include="$(SourcePath)PCSSQL.rds"/>
    <DataSource Include="$(SourcePath)PCSSQL_Admin.rds" />
  </ItemGroup>
  <ItemGroup>
    <Report Include="$(SourcePath)AgingReport.rdl" DataSource="$(TargetDatasourceFolder)/PCSSQL" />
    <Report Include="$(SourcePath)Appointment Status Report.rdl" />
    <Report Include="$(SourcePath)Audit Report.rdl" />
 ..........
..........
</ItemGroup>

**Comment by leegillies2** [comment]
Hi,

Did you manage to solve this issue and if so how?  I have the same problem. When I run my MSBuild to Deploy my reporting services, the reports deploy successfully, but the data source fails and gives:
Microsoft.ReportingServices.MSBuilder.targets(33,5): error : : Object reference not set to an instance of an object.
 
  <PropertyGroup>
    <ErrorLevel>2</ErrorLevel>
        <OutputPath>bin\$(BuildEnvironment)</OutputPath>
        <OverwriteDatasets>True</OverwriteDatasets>
        <OverwriteDataSources>True</OverwriteDataSources>
        <TargetDatasetFolder>Datasets</TargetDatasetFolder>
        <TargetDataSourceFolder>Data Sources</TargetDataSourceFolder>
        <TargetReportFolder>MyProject</TargetReportFolder>
        <TargetReportPartFolder>Report Parts</TargetReportPartFolder>
        <TargetServerURL>http://MyProjectIPAddress/reportserver</TargetServerURL>
    <TargetServerVersion>SSRS2008R2</TargetServerVersion>
  </PropertyGroup>
 
  <PropertyGroup>
    <DataSources>@(DataSource)</DataSources>  
    <DataSets>@(DataSet)</DataSets>     
    <Reports>@(Report)</Reports>
  </PropertyGroup>
  <ItemGroup>
    <DataSource Include="Reporting/MyProject.rds" />
  </ItemGroup>  
  <ItemGroup>
    <Report Include="Reporting/*.rdl" />
  </ItemGroup>

I don't have any DataSets is that a problem?

Please help.

Thanks

Lee

**Comment by superviktor** [comment]
> Hello,
> 
> Can you try to build/deploy with the latest VS 2017 installed with the latest Reporting Services Project Extension? I recently made a fix in this space dealing with Shared Datasets and Shared Data Sources. Please respond on this thread either way. If it works, we need to update the CI/CD RS VSIX. If not, I will need to investigate your rsproj file.
> 
> Thanks,
> Matt

Hi, for my issue  updating to latest Reporting Services Project Extension fixed problem!

**Comment by moswald** [comment]
Problem fixed by updating to latest version.

**Comment by syedhamjath** [comment]
@Poseideon how do you know that you have use /p:BuildType=Deploy  as MsBuild parameters? FYI., you need to allow the data sets to replace from Project Properties so that data set can be replaced if exists.

**Comment by syedhamjath** [comment]
> 
> 
> Hello,
> 
> Can you try to build/deploy with the latest VS 2017 installed with the latest Reporting Services Project Extension? I recently made a fix in this space dealing with Shared Datasets and Shared Data Sources. Please respond on this thread either way. If it works, we need to update the CI/CD RS VSIX. If not, I will need to investigate your rsproj file.
> 
> Thanks,
> Matt

This is not resolved, I have tried using updated extension with Visual studio 2017, x86 and additional parameters. Nothing seems to be working for me. This issue is still exists
