### ISSUE TITLE
Azure App Service Deploy fails with error "Cannot read property 'WEBSITE_RUN_FROM_PACKAGE' of undefined"

### ISSUE THREAD

**Issue by edwiles** [Microsoft/azure-pipelines-tasks#8635]
## Environment

Server: Azure Pipelines. The release that went wrong is https://dev.azure.com/digitalfoundations/upstream_tf_vst/_releaseProgress?_a=release-environment-logs&releaseId=386&environmentId=1128

Agent: Private (for releases). OS and agent version unknown.

## Issue Description

Deployment task Azure App Service Deploy "v4 (preview)" fails with error Cannot read property 'WEBSITE_RUN_FROM_PACKAGE' of undefined.

### Error logs

2018-10-17T09:47:19.9354102Z ##[section]Starting: Azure App Service Deploy: VST
2018-10-17T09:47:19.9363791Z ==============================================================================
2018-10-17T09:47:19.9364033Z Task         : Azure App Service Deploy
2018-10-17T09:47:19.9364780Z Description  : Update Azure App Services on Windows, Web App on Linux with built-in images or Docker containers, ASP.NET, .NET Core, PHP, Python or Node.js based Web applications, Function Apps on Windows or Linux with Docker Containers, Mobile Apps, API applications, Web Jobs using Web Deploy / Kudu REST APIs
2018-10-17T09:47:19.9365150Z Version      : 4.3.7
2018-10-17T09:47:19.9365312Z Author       : Microsoft Corporation
2018-10-17T09:47:19.9365523Z Help         : [More information](https://aka.ms/azurermwebdeployreadme)
2018-10-17T09:47:19.9365746Z ==============================================================================
2018-10-17T09:47:20.9682514Z Got service connection details for Azure App Service:'VST'
2018-10-17T09:47:24.3067256Z App Service Application URL: https://vst-vst-preprod.ze1p3ase00.com
2018-10-17T09:47:24.3096304Z Updating App Service Application settings. Data: {"WEBSITE_RUN_FROM_PACKAGE":"0"}
2018-10-17T09:47:25.8303335Z ##[error]TypeError: Cannot read property 'WEBSITE_RUN_FROM_PACKAGE' of undefined

**Comment by Ajay-MS** [comment]
@edwiles 

Thanks for reporting the issue. We have experienced this as an intermittent issue with Azure App Service and have already reported with the team. 

We will update this thread as per response from app service team.

**Comment by jsheetzati** [comment]
Same here.

We also started getting `
TypeError: Cannot read property 'scmUri' of undefined` error around the same time the error above appeared. This is happening with a v3 task.

**Comment by edwiles** [comment]
Yes, that was the next error we got! (when we modified the task to v3) We then created a new task using v3 and it worked that time, but maybe that was luck...

**Comment by rfcdejong** [comment]
Same issue here, works 4 out of the 5 deployments, redeploy also fails. A new release based on the same build artifact works fine. Looking at the source code it must be a get Credentials issue Kudu promise that is failing.

2018-10-17T13:40:19.6824672Z ##[section]Starting: Azure App Service Deploy
2018-10-17T13:40:19.6831978Z ==============================================================================
2018-10-17T13:40:19.6832103Z Task         : Azure App Service Deploy
2018-10-17T13:40:19.6832194Z Description  : Update Azure App Services on Windows, Web App on Linux with built-in images or Docker containers, ASP.NET, .NET Core, PHP, Python or Node.js based Web applications, Function Apps, Mobile Apps, API applications, Web Jobs using Web Deploy / Kudu REST APIs
2018-10-17T13:40:19.6832467Z Version      : 3.4.7
2018-10-17T13:40:19.6832547Z Author       : Microsoft Corporation
2018-10-17T13:40:19.6832614Z Help         : [More information](https://aka.ms/azurermwebdeployreadme)
2018-10-17T13:40:19.6832688Z ==============================================================================
2018-10-17T13:40:20.4526646Z Got connection details for Azure App Service:'modified...'
2018-10-17T13:40:22.6238208Z ##[error]TypeError: Cannot read property 'scmUri' of undefined
2018-10-17T13:40:22.6294361Z ##[section]Finishing: Azure App Service Deploy

**Comment by samuelbcollie** [comment]
Version 3 Function App Service deploy logs:

2018-10-17T17:33:57.5789456Z ##[debug][POST]https://login.windows.net/***/oauth2/token/
2018-10-17T17:33:57.7999797Z ##[debug][GET]https://anonymized
2018-10-17T17:33:57.9756451Z ##[debug]Resource Group: ANONYMIZED
2018-10-17T17:33:57.9779094Z ##[debug][POST]https://anonymized
2018-10-17T17:33:58.3296135Z ##[debug]Could not parse response: {}
2018-10-17T17:33:58.3297200Z ##[debug]Response: undefined
2018-10-17T17:33:58.3488239Z ##[debug][GET]http://anonymized
2018-10-17T17:33:58.6848591Z ##[debug]Could not parse response: {}
2018-10-17T17:33:58.6849611Z ##[debug]Response: undefined
2018-10-17T17:33:58.6850609Z ##[debug]App Service status Code: '200'. Status Message: 'OK'
2018-10-17T17:33:58.6857473Z ##[debug][POST]https://anonymized
2018-10-17T17:33:59.3899545Z ##[debug]task result: Failed
2018-10-17T17:33:59.3901851Z ##[error]TypeError: Cannot read property 'scmUri' of undefined
2018-10-17T17:33:59.3902629Z ##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'scmUri' of undefined
2018-10-17T17:33:59.3903800Z ##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read property 'scmUri' of undefined
2018-10-17T17:33:59.3904295Z ##[debug]Cannot update deployment status as Kudu is not initialized

**Comment by Ajay-MS** [comment]
This issue seems to be mitigated from Azure App Service end. Please let us know if you are still hitting this issue.

**Comment by roman89remit** [comment]
Had same problem yesterday which occurred sporadically in half of builds. But today everything seems to be ok.

**Comment by vincentdass** [comment]
Closing the issue as the issue is resolved by Azure team.

**Comment by chartsNgraphs** [comment]
This issue is back. Deployments that were successful for weeks suddenly fail, and I'm unable to deploy anything. deployments *immediately* fail with this error. 
I believe the bug has been re-introduced.

**Comment by karinapatel02** [comment]
Cannot read property 'portalUrl' of undefined 

Getting this error for Azure App service extension when using pandas while deploying.

**Comment by OmarSammanKaakajiDM** [comment]
Error: Cannot read properties of undefined (reading 'portalUrl')- I am also facing this error
