### ISSUE TITLE
File Transform task for json file it puts the result in the temp folder and not the artifacts

### ISSUE THREAD

**Issue by fouadroumieh** [Microsoft/azure-pipelines-tasks#9488]
Hi,

I'm trying to use the "File Transfrom" (Preview mode) to do variable substitution in json file but checking the logs it shows that it is substituting in the temp folder and never copy back to artifact folder.

This is from logs:
`Applying JSON variable substitution for D:\Build Agents\vsts-01_work_temp\temp_web_pac...`
<img width="374" alt="capture" src="https://user-images.githubusercontent.com/5886736/52125463-37a20d00-2635-11e9-829c-9a510e7a6bb9.PNG">

**Comment by vincentdass** [comment]
@fouadroumieh , @easyt , 
In File Transform task, the package provided is extracted first (if its a zip) or copied to temp location (if its a folder) and the transformation is applied to that temp folder. Then, the old package is replaced with the new package.

**Comment by easyt** [comment]
@vincentdass, the code that is live for us is broken. I pulled the contents of the task from here: `C:\azagent\A1\_work\_tasks\FileTransform_8ce97e91-56cc-4743-bfab-9a9315be5f27\1.0.0`

This doesn't match the latest code in GitHub which may be fixed. Code from location above:

```
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const tl = require("vsts-task-lib/task");
const packageUtility_1 = require("webdeployment-common/packageUtility");
var deployUtility = require('webdeployment-common/utility.js');
var fileTransformationsUtility = require('webdeployment-common/fileTransformationsUtility.js');
function main() {
    return __awaiter(this, void 0, void 0, function* () {
        let webPackage = new packageUtility_1.Package(tl.getPathInput('folderPath', true));
        let packagePath = webPackage.getPath();
        let JSONFiles = tl.getDelimitedInput('JSONFiles', '\n', false);
        let XmlVariableSubstitution = tl.getBoolInput("enableXmlVariableSubstitution", false);
        let applyFileTransformFlag = JSONFiles.length != 0 || XmlVariableSubstitution;
        if (applyFileTransformFlag) {
            let isFolderBasedDeployment = tl.stats(packagePath).isDirectory();
            let folderPath = yield deployUtility.generateTemporaryFolderForDeployment(isFolderBasedDeployment, packagePath, webPackage.getPackageType());
            let isMSBuildPackage = !isFolderBasedDeployment && (yield deployUtility.isMSDeployPackage(packagePath));
            fileTransformationsUtility.fileTransformations(isFolderBasedDeployment, JSONFiles, false, XmlVariableSubstitution, folderPath, isMSBuildPackage);
        }
        else {
            tl.debug('File Tranformation not enabled');
        }
    });
}
main();

```

When can we expect the latest code to be verified and deployed to production?

**Comment by vincentdass** [comment]
@easyt , the deployment is in progress and the new version should be available in 2-3 weeks.

**Comment by wi1s0n** [comment]
Hi! I have this question.
It looks like you guys above get it to work, but it is stuck in the temp folder.
I always gets this error:
##[warning]Resource file haven\'t set, can\'t find loc string for key: JSONvariablesubstitutionappliedsuccessfully
But I don't find any explanation of this error message. 
I have the Folder Path set to:
$(System.DefaultWorkingDirectory)/my_application/drop/
And in the drop -folder the files exists.
In the "JSON variable substituion", I have added the syntax:
**/appsettings.Production.json
As I want to edit that json file.
Then I added the pipeline variable:
ConnectionStrings.MASTERDB
But still, I got the error message above. What does it mean..?

**Comment by vincentdass** [comment]
@wi1s0n , the localization for `JSONvariablesubstitutionappliedsuccessfully` string is not present, which caused this issue. Both the file copy issue and the localization issue is fixed in new version and will be available in 1-2 weeks. Also, does the warning makes the deployment fail?

**Comment by wi1s0n** [comment]
@vincentdass , I don't really know what you mean by "

> localization for `JSONvariablesubstitutionappliedsuccessfully` string is not present

"  I have added the variable, specified the file and folder..


No, there is a warning but no substitution is performed.

**Comment by wi1s0n** [comment]
@vincentdass could you elaborate in detal what you meant with your previous statement. I have followed the guide, step by step, but still getting the error above..
Thanx!

**Comment by vincentdass** [comment]
@wi1s0n , apologies. I forgot to mention its a issue on our side. 
The deployment is in progress and the fix will be available in ~1 week,

**Comment by fouadroumieh** [comment]
As work around now I ran some copy tasks on the temp folder to bring the files with replaced tokens back to artifact dir.
Thanks guys

**Comment by vincentdass** [comment]
The issue is fixed and the fix is available in all the accounts.
Please feel free to reopen the issue if it still exists.
