### ISSUE TITLE
AZ File Copy Task Warning about `unapproved verbs`

### ISSUE THREAD

**Issue by mydiemho** [microsoft/azure-pipelines-tasks#9922]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureBlob File Copy  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
   https://dev.azure.com/msft-vott/VoTT/_releaseProgress?_a=release-environment-logs&releaseId=164&environmentId=164

- Agent - Hosted 
https://dev.azure.com/msft-vott/VoTT/_releaseProgress?_a=release-environment-logs&releaseId=164&environmentId=164
    
## Issue Description

The task is showing warning

```
2019-03-25T21:48:21.5950954Z ##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
``` 

### Task logs

Pipeline has no "debug" support, but log is attached.
[logs_1957.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/3005666/logs_1957.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
2019-03-25T21:48:21.5950954Z ##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
```

**Comment by niadak** [comment]
@mydiemho, Thanks for reporting the issue. This is an [issue ](https://github.com/Azure/azure-powershell/issues/3007)with Azure PowerShell and they have already fixed it. Unfortunately in hosted agent we are still using V2.1.0 for this task which dont have the fix.

Please ignore the warning.

https://github.com/Azure/azure-powershell/issues/3007

**Comment by mydiemho** [comment]
Is there any plan to update the task? The fix was out 2.5 years old :/

**Comment by BurgerVanDan** [comment]
Has this really been resolved?

Its now May 2019 and I am still encountering the same issue when utilizing the AzCopy task within Azure DevOps:

`##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.`

**Comment by M0ns1gn0r** [comment]
Still not fixed :sigh:

**Comment by motowilliams** [comment]
February 2020 checking in!

**Comment by DannyAguirre** [comment]
### **Can someone please look into resolving this warning. I see it's been open for quite some time when running deployments in DevOps.**

2020-02-15T17:22:46.8827456Z ##[command]Import-Module -Name C:\Modules\azurerm_2.1.0\AzureRM\2.1.0\AzureRM.psd1 -Global
2020-02-15T17:22:58.4134658Z ##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2020-02-15T17:22:58.4210894Z ##[warning]The names of some imported commands from the module 'AzureRM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

**Comment by arjgupta** [comment]
[PR for this change.](https://github.com/microsoft/azure-pipelines-tasks/pull/12406)

**Comment by DannyAguirre** [comment]
Thanks 😊 No more warnings ⚠️
@arjgupta

**Comment by oramoss** [comment]
Still happening, March 2020 :-(

**Comment by SumiranAgg** [comment]
@oramoss The fix has not been deployed to all accounts yet. Should be available in next couple of weeks.

**Comment by evandigby** [comment]
Curious if the fix covers V3/V4? The PR only seems to cover V2.

https://github.com/microsoft/azure-pipelines-tasks/pull/12406#discussion_r393326540

**Comment by SumiranAgg** [comment]
This is the PR we finally merged for this fix #12407

**Comment by 20shivangi** [comment]
The fix will soon be deployed, thereby closing it

**Comment by kambizniktabar** [comment]
Has the fix already deployed? The warning still there.

**Comment by tgutzler** [comment]
I'm also getting the warning. Using task v3

**Comment by AnaAtabajeva** [comment]
06-2020, warnings are still there

**Comment by 20shivangi** [comment]
Please use latest version of azure filecopy i.e. V4 version. The issue has been fixed in that.

**Comment by kambizniktabar** [comment]
@20shivangi the V4 of Azure File copy throws the error message "ExceptionMessage: Not able to fetch token for tenant Id"

**Comment by mohammads-axs** [comment]
Still getting these warnings, is there a fix?

he names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

**Comment by kmkumaran** [comment]
+ @vijayma

**Comment by robkendrick** [comment]
Getting the same thing with the AzureFileCopy@5 task:
##[warning]The names of some imported commands from the module 'Microsoft.Azure.PowerShell.Cmdlets.Network' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

**Comment by thanghq** [comment]
This issue still persist with AzureFileCopy@5.225.1

##[warning]The names of some imported commands from the module 'Microsoft.Azure.PowerShell.Cmdlets.Network' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

##[warning]The names of some imported commands from the module 'Az.Network' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
